- src/init/entry.js
- src/init/init.js
This reverts commit 304fe7a349f35dc1a9a2278834b5f11de4e95e8c.
> DHIS2-3996 Adding the discard unsaved events dialog

- src/core_modules/capture-core/src/components/D2Form/D2Form.component.js
- src/core_modules/capture-core/src/components/DataEntry/actions/dataEntryLoad.utils.js
- src/core_modules/capture-core/src/components/DataEntry/actions/dataEntryLoadEdit.actions.js
- src/core_modules/capture-core/src/components/DataEntry/actions/dataEntryLoadNew.actions.js
- src/core_modules/capture-core/src/components/DataEntry/dataEntryField/dataEntryField.utils.js
- src/core_modules/capture-core/src/components/DataEntry/dataEntryField/withDataEntryField.js
- src/core_modules/capture-core/src/components/Pages/EditEvent/DataEntry/EditEventDataEntry.component.js
- src/core_modules/capture-core/src/components/Pages/EditEvent/DataEntry/editEventDataEntry.actions.js
- src/core_modules/capture-core/src/components/Pages/EditEvent/DataEntry/fieldValidators/eventDate.validatorContainersGetter.js
- src/core_modules/capture-core/src/components/Pages/EditEvent/epics/editEvent.epics.js
- src/core_modules/capture-core/src/components/Pages/MainPage/EventsList/EventsList.container.js
- src/core_modules/capture-core/src/components/Pages/NewEvent/DataEntry/NewEventDataEntry.component.js
- src/core_modules/capture-core/src/components/Pages/NewEvent/DataEntry/fieldValidators/eventDate.validatorContainersGetter.js
- src/core_modules/capture-core/src/components/Pages/NewEvent/DataEntry/newEventDataEntry.actions.js
- src/core_modules/capture-core/src/events/eventRequests.js
- src/core_modules/capture-core/src/reducers/descriptions/dataEntry.reducerDescription.js
- src/core_modules/capture-core/src/reducers/descriptions/editEvent.reducerDescription.js
validate form main data on load
fixed form validation bug
> validations

- public/manifest.webapp
- src/core_modules/capture-core/src/components/DownloadTable/DownloadTable.component.js
- src/core_modules/capture-core/src/components/DownloadTable/DownloadTable.container.js
- src/core_modules/capture-core/src/components/Pages/MainPage/EventsList/EventsList.component.js
- Ability to download the list of events in JSON, XML and CSV.
> Download Event List

- public/manifest.webapp
- src/core_modules/capture-core/src/components/D2Form/field/buildField.js
- src/core_modules/capture-core/src/components/D2Form/field/validators.js
- src/core_modules/capture-core/src/metaData/DataElement/elementTypes.js
New elementType URL with validator.
> URL element type

- src/core_modules/capture-core/src/api/apiSpecifications/programs.apiSpecification.js
- src/core_modules/capture-core/src/components/QuickSelector/ProgramSelector.component.js
- src/core_modules/capture-core/src/metaData/Program/Program.js
- src/core_modules/capture-core/src/metaDataFactory/program/programFactory.js
https://jira.dhis2.org/browse/DHIS2-4282
> Hide programs that user does not have data read access for

- src/core_modules/capture-core/src/components/DownloadTable/DownloadTable.component.js
- src/core_modules/capture-core/src/components/DownloadTable/DownloadTable.container.js
- Fixed issue for programs with category combinations where events would not be in the downloaded file.
> Download fix

- i18n/en.pot
- package.json
- src/core_modules/capture-core-utils/src/storage/StorageController.js
- src/core_modules/capture-core/src/components/FeedbackBar/FeedbackBar.component.js
- src/core_modules/capture-core/src/reducers/descriptions/feedback.reducerDescriptionGetter.js
- src/reducers/descriptions/feedback.reducerDescription.js
- src/reducers/descriptions/trackerCapture.reducerDescriptions.js
- show dialog if fallback encountered
> Storage fallback on opening

- public/index.html
See https://jira.dhis2.org/browse/DHIS2-6122 and my comment for why this change is needed.
> fix: manifest credential bug in chrome

- public/index.html
> v31: fix: manifest credentials bug in chrome

- src/core_modules/capture-core/src/components/D2Form/D2Form.component.js
- src/core_modules/capture-core/src/components/D2Form/field/Components/ViewModeField/ViewModeFieldCustomForm.mod.css
- src/core_modules/capture-core/src/components/D2Form/field/Components/ViewModeField/ViewModeFieldForCustomForm.component.js
- src/core_modules/capture-core/src/components/D2Form/field/Components/index.js
- src/core_modules/capture-core/src/components/D2Form/field/configs/index.js
- src/core_modules/capture-core/src/components/D2Form/field/configs/viewModeField/getViewModeFieldConfigForCustomForm.js
- src/core_modules/capture-core/src/components/D2Form/field/customFormFieldGetter.js
- src/core_modules/capture-core/src/components/DataEntry/DataEntry.component.js
- Moved scroll to prevent clipping of the dropdown
- ViewModeField when displaying custom form in ViewEvent
> [DHIS2-6637] Custom form fixes

- src/core_modules/capture-core/components/FormFields/New/Fields/AgeField/AgeField.component.js
- src/core_modules/capture-core/components/FormFields/New/Fields/DateAndTimeFields/DateField/DateField.component.js
- src/core_modules/capture-ui/AgeField/AgeField.component.js
- src/core_modules/capture-ui/internal/AgeInput/AgeDateInput.component.js
- src/core_modules/capture-ui/internal/ShrinkLabel/shrinkLabel.module.css
(cherry picked from commit 152050ff9c4cc1badc94cecbb6d4684ebd8edf3d)
> fix: add placeholder to date and age field (#142)

- .env.development
- src/core_modules/capture-core-utils/parsers/date.parser.js
- src/core_modules/capture-core-utils/parsers/index.js
- src/core_modules/capture-core-utils/parsers/time.parser.js
- src/core_modules/capture-core-utils/validators/form/time.validator.js
- src/core_modules/capture-core/components/TeiSearch/epics/teiSearch.epics.js
- src/core_modules/capture-core/components/TeiSearch/serverToFilters.js
- src/core_modules/capture-core/converters/clientToForm.js
- src/core_modules/capture-core/converters/clientToList.js
- src/core_modules/capture-core/converters/clientToServer.js
- src/core_modules/capture-core/converters/clientToView.js
- src/core_modules/capture-core/converters/formToClient.js
- src/core_modules/capture-core/converters/serverToClient.js
- src/core_modules/capture-core/rulesEngineActionsCreator/converters/inputValueConverter.js
(cherry picked from commit fc429d655a6b0ae94a107f6eb9bdbe45ac4c8f40)
> fix: DHIS2-7554 follow up; date format and interface language issues

- i18n/en.pot
- src/core_modules/capture-core-utils/storage/StorageController.js
- src/core_modules/capture-core/storageControllers/mainStorageController.js
- src/core_modules/capture-core/storageControllers/storageControllers.js
- src/core_modules/capture-core/storageControllers/userStorageController.js
- src/core_modules/capture-core/utils/exceptions/DisplayException.js
- src/init/entry.js
- src/init/init.js
(cherry picked from commit 09c9dde43931ed85c51e7b47919c429879743532)
> fix: DHIS2-7749 use IndexedDB storage only

- i18n/en.pot
- src/core_modules/capture-core/metaDataMemoryStoreBuilders/programs/factory/category/CategoryFactory.js
- src/init/init.js
(cherry picked from commit c81d90de729da00f1bcf1b8f5b0e67d93498db37)
> fix: minification fix for category factory (#247)

- src/core_modules/capture-core/components/D2Form/D2Form.component.js
(cherry picked from commit 86c8a1feff2a39d2449099d896cec00aecac7f72)
> fix: DHIS2-7894 save form with hidden section (#375)

- src/core_modules/capture-core/src/components/D2Form/D2Form.component.js
(cherry picked from commit fcab95f35514acec41e3253ae762ca7df5c7b92c)
> fix: DHIS2-7894 save form with hidden section (#377)

- src/core_modules/capture-core/components/Pages/MainPage/EventsList/FilterSelectors/FilterButton/filterButton.selectors.js
(cherry picked from commit 717eafd38d10450a661445dfc59fc5270ff12d6a)
> fix: reset filter text timing update (#379)

- i18n/en.pot
- src/core_modules/capture-core/components/Pages/MainPage/EventsList/ListWrapper/ListWrapperMenu.component.js
- src/core_modules/capture-core/components/Pages/MainPage/WorkingLists/EventListConfigMenuContent.component.js
- src/core_modules/capture-core/components/Pages/MainPage/WorkingLists/EventListLoader.component.js
- src/core_modules/capture-core/components/Pages/MainPage/WorkingLists/TemplateMaintenance/DeleteConfirmationDialog.component.js
- src/core_modules/capture-core/components/Pages/MainPage/WorkingLists/TemplateMaintenance/NewTemplateContents.component.js
- src/core_modules/capture-core/components/Pages/MainPage/WorkingLists/workingLists.actions.js
- src/core_modules/capture-core/reducers/descriptions/workingLists/meta/meta.reducerDescription.js
- src/core_modules/capture-core/reducers/descriptions/workingLists/workingLists.reducerDescription.js
- src/locales/en/translations.json
- src/locales/index.js
- changed menu items text and visibility logic
- fixed an issue where the view would appear as modified when loading
- minor text fixes (template -> view)
> fix: DHIS2-4440 updates menu items and minor fixes

- src/core_modules/capture-core-utils/RulesEngine/RulesEngine.js
- src/core_modules/capture-core-utils/RulesEngine/VariableService/VariableService.js
- src/core_modules/capture-core/components/D2Form/D2Form.component.js
- src/core_modules/capture-core/rulesEngineActionsCreator/runRulesForSingleEvent.js
- add missing context variables to rules engine
- add missing validation strategy to horizontal form
- clean up variable builder
> fix: DHIS2-8519 field validation bug

- src/core_modules/capture-core/components/Pages/NewEvent/DataEntry/epics/newEventDataEntry.epics.js
- prevent the app from crashing with tracker programs in the new event page
> fix: DHIS2-8602 tracker program crash fix

- src/core_modules/capture-ui/CoordinateField/CoordinateField.component.js
> fix: changes the order of lat and long in the new event page

- src/core_modules/capture-core-utils/RulesEngine/OptionSetHelper/OptionSetHelper.js
- src/core_modules/capture-core-utils/RulesEngine/RulesEngine.js
- src/core_modules/capture-core-utils/RulesEngine/RulesEngine.test.js
- src/core_modules/capture-core-utils/RulesEngine/__snapshots__/RulesEngine.test.js.snap
- src/core_modules/capture-core-utils/RulesEngine/executionService/executionService.js
- src/core_modules/capture-core/metaData/Program/Program.js
- src/core_modules/capture-core/metaData/Program/ProgramStage.js
- src/core_modules/capture-core/metaData/index.js
- src/core_modules/capture-core/rulesEngineActionsCreator/rulesEngineActionsCreator.js
- src/core_modules/capture-core/rulesEngineActionsCreator/runRulesForSingleEvent.js
This one is based on https://github.com/dhis2/capture-app/pull/565
What we are doing here is 
* cleaning up code that is never used on the files that I touched or read through. I hope you agree we don't need to have code that is never used. : ) 
* removed variables that we pass in functions that are never used such as `onTranslate` or `formId`
* try to make the code more readable for the developer by explicitly showing to the reader which variables I am passing in functions instead of passing object properties that are not used. see [here](https://github.com/dhis2/capture-app/compare/cp/writes-first-tests-on-runRulesForSingleEvent...cp/refactors-on-runRulesForSingleEvent?expand=1#diff-91f832c4094c3bd7b657665929a0d27cR103) 
I am trying to split the PRs to as small as possible so that it is …
> refactor: refactors on runRulesForSingleEvent and removes unused code.

- src/core_modules/capture-core-utils/RulesEngine/RulesEngine.js
- src/core_modules/capture-core-utils/RulesEngine/RulesEngine.test.js
- src/core_modules/capture-core-utils/RulesEngine/__snapshots__/RulesEngine.test.js.snap
- src/core_modules/capture-core/rulesEngineActionsCreator/rulesEngineActionsCreator.js
- src/core_modules/capture-core/rulesEngineActionsCreator/runRulesForSingleEvent.js
- src/core_modules/capture-core/rulesEngineActionsCreator/runRulesForTEI.js
based on: https://github.com/dhis2/capture-app/pull/617
Hey @JoakimSM 👋 
As we talked about some days ago we wanted to have the same changes being applied for TEI. This is what this PR is about. 
NOTE: Can we please validate that this works also by manual browser testing?
> refactor: applies the changes for TEI on `runRulesForTEI ` 05

- src/core_modules/capture-core-utils/RulesEngine/RulesEngine.js
- src/core_modules/capture-core-utils/RulesEngine/VariableService/VariableService.js
- src/core_modules/capture-core-utils/RulesEngine/rulesEngine.types.js
- src/core_modules/capture-core/rulesEngineActionsCreator/postProcessRulesEffects.js
- src/core_modules/capture-core/rulesEngineActionsCreator/rulesEngineActionsCreator.js
- src/core_modules/capture-core/rulesEngineActionsCreator/runRulesForSingleEvent.js
based on https://github.com/dhis2/capture-app/pull/624
Hey 👋 This is again a small PR that annotates and sets some default variables
Since you for sure more experienced than me can you please have a look and let me know your thoughts?
> refactor: annotates 06

- src/core_modules/capture-core-utils/RulesEngine/RulesEngine.js
- src/core_modules/capture-core-utils/RulesEngine/executionService/executionService.js
- src/core_modules/capture-core-utils/RulesEngine/rulesEngine.types.js
- src/core_modules/capture-core/rulesEngineActionsCreator/rulesEngineActionsCreator.js
based on https://github.com/dhis2/capture-app/pull/625
Hey @JoakimSM!! 
I have moved the logic of calculating the `variablesHash` to the `RulesEngine`. This way the signature of the `getEffects` gets simpler! 🎉
> refactor: slimens get effects 07

- src/core_modules/capture-core-utils/RulesEngine/VariableService/VariableService.js
- src/core_modules/capture-core-utils/RulesEngine/__tests__/RulesEngine.test.js
- src/core_modules/capture-core-utils/RulesEngine/__tests__/__snapshots__/RulesEngine.test.js.snap
- src/core_modules/capture-core-utils/RulesEngine/rulesEffectsProcessor/rulesEffectsProcessor.js
- src/core_modules/capture-core-utils/RulesEngine/rulesEngine.types.js
- src/core_modules/capture-core/rulesEngineActionsCreator/rulesEngineActionsCreator.js
based on https://github.com/dhis2/capture-app/pull/628
👋 @JoakimSM another one with actual 🐛 fixes. 
I am writing tests to capture the functionality of each the functions we have available at the moment in the `capture-app`. 
At the moment tests have not been written for the functions:
* `d2:countIfZeroPos` since this function is not implemented yet in our app
* `d2:inOrgUnitGroup` since this function is not implemented yet in our app
* `d2:addDays` since this function is not implemented yet in our app
* `d2:zScoreHFA ` since this function is not implemented yet in our app
* `d2:zScoreWFH` since this function is not implemented yet in our app
* `d2:zScoreWFA` since the functionality of this is yet unknown to me
* `d2:checkControlDigits` since the functionality of this is yet unknown to me …
> chore: writes tests on functions 09

- src/core_modules/capture-core-utils/RulesEngine/RulesEngine.js
Hey @JoakimSM thanks for catching this! 
I am fixing the flow errors here. My flow was not configured well and I missed those. Will make sure same wont happen in the future ;)
> fix: flow errors

- i18n/en.pot
- src/core_modules/capture-core/components/D2Form/D2SectionFields.component.js
- src/core_modules/capture-core/components/D2Form/field/configs/base/configBase.js
- src/core_modules/capture-core/components/D2Form/field/configs/dateField/getDateFieldConfig.js
- src/core_modules/capture-core/components/D2Form/field/configs/dateField/getDateFieldConfigForCustomForm.js
- src/core_modules/capture-core/components/D2Form/field/validators/constants/index.js
- src/core_modules/capture-core/components/D2Form/field/validators/constants/validatorTypes.const.js
- src/core_modules/capture-core/components/D2Form/field/validators/getValidators.js
- src/core_modules/capture-core/components/D2Form/field/validators/index.js
- src/core_modules/capture-core/metaData/DataElement/DateDataElement.js
- src/core_modules/capture-core/metaData/DataElement/Unique/Unique.js
- src/core_modules/capture-core/metaData/DataElement/index.js
- src/core_modules/capture-core/metaData/index.js
- src/core_modules/capture-core/metaDataMemoryStoreBuilders/programs/factory/enrollment/DataElementFactory.js
- src/core_modules/capture-core/metaDataMemoryStoreBuilders/programs/factory/programStage/DataElementFactory.js
- src/core_modules/capture-core/storageControllers/cache.types.js
- src/core_modules/capture-core/utils/validators/form/index.js
- src/core_modules/capture-core/utils/validators/form/isValidNonFutureDate.js
- src/locales/en/translations.json
- for program stage data elements and program tracked entity attributes
> fix: DHIS2-8333 Comply with allow future date selection

- src/components/AppLoader/init.js
- src/core_modules/capture-core/HOC/withFullPageLoadingIndicator.js
- src/core_modules/capture-core/HOC/withLoadingIndicator.js
- src/core_modules/capture-core/HOC/withStateBoundLoadingIndicator.js
- src/core_modules/capture-core/components/App/withAppUrlSync.js
- src/core_modules/capture-core/components/Buttons/ProgressButton.component.js
- src/core_modules/capture-core/components/CardList/CardList.component.js
- src/core_modules/capture-core/components/FormFields/File/D2File.component.js
- src/core_modules/capture-core/components/FormFields/Image/D2Image.component.js
- src/core_modules/capture-core/components/FormFields/New/HOC/messages/withDisplayMessages.js
- src/core_modules/capture-core/components/List/OnlineList/List.component.js
- src/core_modules/capture-core/components/LoadingMasks/index.js
- src/core_modules/capture-core/components/Pages/MainPage/EventsList/ListWrapper/EventsListWrapper.component.js
- src/core_modules/capture-core/components/Pages/NewRelationship/TeiRelationship/SearchResults/TeiRelationshipSearchResults.component.js
- src/core_modules/capture-core/components/TeiSearch/TeiSearchResults/TeiSearchResults.component.js
Part eight of [TECH-344](https://jira.dhis2.org/browse/TECH-344)
This basically uses the created index files for importing.
Should resolve:
1. [#664(comment)](https://github.com/dhis2/capture-app/pull/664#discussion_r425883746)
2. [#664(comment)](https://github.com/dhis2/capture-app/pull/664#discussion_r425888854)
> refactor: 8. Importing using created index files [TECH-344] 

- src/core_modules/capture-core/components/Pages/ViewEvent/epics/viewEvent.epics.js
- resolved an issue in the epic chain when opening the view event page directly from url.
> fix: open view event page directly from url

- src/core_modules/capture-core/components/Pages/NewEvent/DataEntry/epics/newEventDataEntry.epics.js
Hey this is fixing https://jira.dhis2.org/browse/DHIS2-8847 thanks for helping me with this! 
To test I would follow the steps described in the ticket itself. It should be easier this way then. 
Let me know if you find something odd!
> fix: DHIS2-8847 Rule variable with source type "Data element for the newest event for a program stage" does not show on Feedback Indicator 

- src/core_modules/capture-core/components/Pages/NewEvent/DataEntry/epics/newEventDataEntry.epics.js
backport https://github.com/dhis2/capture-app/pull/753
> fix: DHIS2-8847 v33 Rule variable with source type "Data element for the newest event for a program stage" does not show on Feedback Indicator

- package.json
- src/core_modules/capture-core/src/components/Pages/NewEvent/DataEntry/epics/newEventDataEntry.epics.js
backport https://github.com/dhis2/capture-app/pull/753
> fix: DHIS2-8847 v32 Rule variable with source type "Data element for the newest event for a program stage" does not show on Feedback Indicator

- src/core_modules/capture-core/components/Pages/NewEvent/DataEntry/epics/newEventDataEntry.epics.js
backport https://github.com/dhis2/capture-app/pull/753
> fix: DHIS2-8847 v34 Rule variable with source type "Data element for the newest event for a program stage" does not show on Feedback Indicator

- src/core_modules/capture-ui/DateAndTimeFields/DateField/DateCalendar.component.js
JIRA ticket: [DHIS2-9067](https://jira.dhis2.org/browse/DHIS2-9067)
> fix: DHIS2-9067 extend year range

- README.md
I ve never realised those were simply comments.
> docs: removes comments from example

- src/core_modules/capture-core/components/List/OnlineList/List.component.js
- src/core_modules/capture-core/components/LockedSelector/QuickSelector/ActionButtons.component.js
- src/core_modules/capture-core/components/LockedSelector/QuickSelector/OrgUnitSelector.component.js
- src/core_modules/capture-core/components/LockedSelector/QuickSelector/Program/ProgramSelector.component.js
- src/core_modules/capture-core/components/Pages/MainPage/EventsList/EventContentMenu/EventContentMenu.component.js
- src/core_modules/capture-core/components/Pages/MainPage/MainPage.component.js
- src/core_modules/capture-core/components/Pages/NewEvent/DataEntry/DataEntry.component.js
- src/core_modules/capture-core/components/Pages/NewEvent/DataEntry/withMainButton.js
- src/core_modules/capture-ui/DataTable/Row.component.js
- src/core_modules/capture-ui/DateAndTimeFields/DateField/Date.component.js
Attributes that help with test case implemented in [ this PR. ](https://github.com/dhis2/e2e-tests/pull/48). The test case should cover this scenario https://jira.dhis2.org/browse/DHIS2-5287, that is part of QA teams regression testing activities. 
Tested locally.
> test: adds attributes for testing

- src/core_modules/capture-core/components/Notes/Notes.component.js
Adds identifiers to make testing notes easier.
> test: adds identifiers to the Note component

- src/core_modules/capture-core/components/List/OnlineList/List.component.js
- src/core_modules/capture-core/components/Notes/Notes.component.js
- src/core_modules/capture-core/components/Pages/MainPage/EventsList/EventContentMenu/EventContentMenu.component.js
- src/core_modules/capture-core/components/Pages/MainPage/MainPage.component.js
- src/core_modules/capture-core/components/Pages/NewEvent/DataEntry/DataEntry.component.js
- src/core_modules/capture-core/components/Pages/NewEvent/DataEntry/withMainButton.js
- src/core_modules/capture-core/components/QuickSelector/ActionButtons.component.js
- src/core_modules/capture-core/components/QuickSelector/OrgUnitSelector.component.js
- src/core_modules/capture-core/components/QuickSelector/Program/ProgramSelector.component.js
- src/core_modules/capture-ui/DataTable/Row.component.js
- src/core_modules/capture-ui/DateAndTimeFields/DateField/Date.component.js
> test: adds attributes for testing (v34)

- src/core_modules/capture-core/components/Buttons/SimpleSplitButton.component.js
This will fix the https://jira.dhis2.org/browse/DHIS2-9348 ticket @JoakimSM.
Another very small one :)
> fix: DHIS2-9348 Button dropdown items doesn't display correctly in "batch mode"

- src/core_modules/capture-core/components/Pages/NewEvent/DataEntry/Assignee/Assignee.component.js
- src/core_modules/capture-core/components/Pages/NewEvent/DataEntry/DataEntry.component.js
Hey @JoakimSM a short one.
This will fix the bug from this https://jira.dhis2.org/browse/DHIS2-9347 ticket.
> fix: DHIS2-9347 Align assigned user field in row view

- src/core_modules/capture-core/components/MinimalCoordinates/MinimalCoordinates.js
- src/core_modules/capture-core/components/MinimalCoordinates/index.js
- src/core_modules/capture-core/converters/clientToList.js
- src/core_modules/capture-core/converters/clientToView.js
- src/core_modules/capture-ui/CoordinateField/CoordinateField.component.js
v34 back port on the https://jira.dhis2.org/browse/DHIS2-9373
> fix: DHIS2-9373

- .env.cypress
- cypress/integration/NewEvent/index.js
- cypress/support/helpers.js
- cypress/support/index.js
- cypress/support/login.js
- scripts/startAppForCypress.js
This PR capitalizes the Cypress environment variables and does some minor changes to the tests.
> refactor: Cypress capitalize env vars and minor

- cypress/integration/LockedSelector/index.js
- src/core_modules/capture-core/components/LockedSelector/QuickSelector/ActionButtons.component.js
As Gintare mentioned chaning this test-id broke some of their tests. 
This PR reverts this change.
> fix: reverts test id on button

- src/core_modules/capture-core/components/Pages/MainPage/WorkingLists/TemplateMaintenance/NewTemplateContents.component.js
- src/core_modules/capture-core/components/Pages/MainPage/WorkingLists/TemplateMaintenance/NewTemplateTextField.component.js
- src/core_modules/capture-core/components/Pages/MainPage/WorkingLists/epics/eventFiltersInterface/toListConfigConverter/toListConfigConverter.js
- use userLookup endpoint in assignee filter
- view / working list name can now be filled in
> fix: use userLookup in filter and bugfix

- src/core_modules/capture-core/components/Pages/MainPage/WorkingLists/TemplateMaintenance/NewTemplateContents.component.js
- src/core_modules/capture-core/components/Pages/MainPage/WorkingLists/TemplateMaintenance/NewTemplateTextField.component.js
- src/core_modules/capture-core/components/Pages/MainPage/WorkingLists/epics/eventFiltersInterface/toListConfigConverter/toListConfigConverter.js
[DHIS2-9663](https://jira.dhis2.org/browse/DHIS2-9663)
[DHIS2-9664](https://jira.dhis2.org/browse/DHIS2-9664)
same as [this PR for v35](https://github.com/dhis2/capture-app/pull/985).
> fix: DHIS2-9663 and DHIS2-9664

- src/core_modules/capture-core/components/Pages/NewEvent/DataEntry/Assignee/Assignee.component.js
- src/core_modules/capture-core/components/Pages/NewEvent/DataEntry/DataEntry.component.js
DHIS2-9664 use userLookup in assignee filter
DHIS2-9663 view name can now be filled in 
Waiting for the approval from the release control board
> fix: userLookup in assignee filter and view name input fix

- i18n/en.pot
- src/core_modules/capture-core/components/LockedSelector/QuickSelector/ActionButtons.component.js
Hello 👋 
Ticket: https://jira.dhis2.org/browse/DHIS2-9646
> feat : DHIS2-9646 change the positions of the buttons in the LockedSelector

- src/core_modules/capture-core/rules/engine/__tests__/programRuleActionsForEvent.test.js
- src/core_modules/capture-core/rules/engine/converters/rulesEffectsValueConverter.js
fix for [JIRA-issue](https://jira.dhis2.org/browse/DHIS2-9709)
> fix: DHIS2-9709 rules engine assigned values of type boolean and true only

- i18n/en.pot
- src/core_modules/capture-core/components/CardList/CardList.component.js
- src/core_modules/capture-core/components/CardList/CardList.selectors.js
- src/core_modules/capture-core/components/CardList/CardListItem.component.js
- src/core_modules/capture-core/components/CardList/ListEntry.component.js
- src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/DataEntry/UniqueTEADuplicate/ExistingTEIContents.component.js
- src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/DataEntry/UniqueTEADuplicate/ExistingTEIContents.container.js
- src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/DataEntry/UniqueTEADuplicate/ExistingTEILoader.component.js
- src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/GeneralOutput/WarningsSection/SearchGroupDuplicate/ReviewDialog.component.js
- src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/GeneralOutput/WarningsSection/SearchGroupDuplicate/ReviewDialogContents.component.js
- src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/GeneralOutput/WarningsSection/SearchGroupDuplicate/ReviewDialogContents.container.js
- src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/GeneralOutput/WarningsSection/SearchGroupDuplicate/searchGroupDuplicate.epics.js
- src/core_modules/capture-core/components/Pages/NewRelationship/TeiRelationship/SearchResults/TeiRelationshipSearchResults.component.js
- src/core_modules/capture-core/components/Pages/Search/SearchForm/SearchForm.epics.js
- src/core_modules/capture-core/components/Pages/Search/SearchPage.component.js
- src/core_modules/capture-core/components/Pages/Search/SearchResults/SearchResults.component.js
- src/core_modules/capture-core/components/Pages/Search/SearchResults/SearchResults.container.js
- src/core_modules/capture-core/components/Pages/Search/SearchResults/SearchResults.types.js
- src/core_modules/capture-core/components/TeiSearch/TeiSearch.container.js
- src/core_modules/capture-core/components/TeiSearch/TeiSearchResults/TeiSearchResults.container.js
- src/core_modules/capture-core/components/TeiSearch/epics/teiSearch.epics.js
- src/core_modules/capture-core/reducers/descriptions/searchPage.reducerDescription.js
https://jira.dhis2.org/browse/DHIS2-9551 
This is fixing the related to the profile image display bug. Now the image should be displayed correctly when there is one. 
_BUT_ more importantly is displaying the CardList in the same manner across the capture app. As we discussed this was not really the case before
The places that are affected are:
1. Finding a TEI under using search page
2. finding a TEI under the malaria case program
3. Registering a TEI under malaria case scope
> 22 fix: DHIS2-9551 Display the CardList component the same across the capture app

- src/core_modules/capture-core/components/Pages/MainPage/WorkingLists/TemplateMaintenance/NewTemplateContents.component.js
- src/core_modules/capture-core/components/Pages/MainPage/WorkingLists/TemplateMaintenance/NewTemplateTextField.component.js
- src/core_modules/capture-core/components/Pages/MainPage/WorkingLists/epics/eventFiltersInterface/toListConfigConverter/toListConfigConverter.js
- src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/RegisterTei.component.js
- src/core_modules/capture-core/rules/engine/__tests__/programRuleActionsForEvent.test.js
- src/core_modules/capture-core/rules/engine/converters/rulesEffectsValueConverter.js
Sorry for the mess @JoakimSM. Can you please look if there is something I am missing?
> fix: erased chain merge code

- .env.cypress
- .github/workflows/cypress-tests.yml
- cypress/integration/NewEvent/index.js
Somehow I think I erased the changes from this one.
https://github.com/dhis2/capture-app/pull/978/
Would you mind having a quick look on it again Joakim?
> fixes: failing new event test

- src/core_modules/capture-core/components/D2Form/D2Form.component.js
- src/core_modules/capture-core/components/D2Form/field/buildField.module.css
- src/core_modules/capture-core/components/DataEntries/Enrollment/fieldLabels.module.css
- src/core_modules/capture-core/components/Pages/EditEvent/DataEntry/dataEntryFieldLabels.module.css
- src/core_modules/capture-core/components/Pages/NewEvent/DataEntry/dataEntryFieldLabels.module.css
- src/core_modules/capture-core/components/Pages/ViewEvent/EventDetailsSection/ViewEventDataEntry/viewEventDataEntryFieldLabels.module.css
- src/core_modules/capture-ui/AgeField/AgeField.component.js
- src/core_modules/capture-ui/AgeField/ageField.module.css
- src/core_modules/capture-ui/CoordinateField/coordinateField.module.css
- src/core_modules/capture-ui/DateAndTimeFields/DateRangeField/DateRangeField.component.js
- src/core_modules/capture-ui/HOC/withShrinkLabel.module.css
- src/core_modules/capture-ui/internal/SelectionBoxes/SingleSelectionBoxes/SingleSelectBox/singleSelectBox.module.css
- src/core_modules/capture-ui/internal/ShrinkLabel/shrinkLabel.module.css
👋 Joakim this solves the https://jira.dhis2.org/browse/DHIS2-9793
If you have a look in the ticker you will see that the bug is described pretty well there from Geetha.
Basically this ticket fixes this for the different inputs that had the same behaviour.
> DHIS2-9793 Text is not aligned correctly

- src/core_modules/capture-core/components/Pages/Search/SearchResults/SearchResults.component.js
Joakim just realised after looking at the design that those buttons are small. Since the change is three lines I went on and changed it.
You might ask youself what small means. Means the buttons have a shorter height :)
> chore: adding small property for CardList buttons

- src/core_modules/capture-core/components/Pages/New/NewPage.component.js
- src/core_modules/capture-core/components/Pages/New/NewPage.container.js
- src/core_modules/capture-core/components/Pages/Search/SearchPage.component.js
- src/core_modules/capture-core/components/Pages/Search/SearchPage.container.js
- src/core_modules/capture-core/components/Pages/Search/SearchPage.types.js
- src/core_modules/capture-core/components/TrackedEntityTypeSelector/TrackedEntityTypeSelector.component.js
- src/core_modules/capture-core/components/TrackedEntityTypeSelector/TrackedEntityTypeSelector.types.js
- src/core_modules/capture-core/hooks/useTrackedEntityTypesWithCorrelatedPrograms.js
@JoakimSM 👋 
this is adding the TEType selector to the new page. 
You will see something like this. It is _only_ rendering the component basically.
Next PR will take care of the url manipulation.
> feat: DHIS2-9649 Display dropdown menu in which the user can select TEType 

- src/core_modules/capture-core/components/D2Form/D2Form.component.js
Looks like my previous efforts to fix this one didnt produce the results I would expect.
> fix: styles of the horizontal form

- cypress.json
- cypress/support/index.js
- i18n/en.pot
- package.json
- yarn.lock
Updates cypress to latest version.
> chore: updates cypress to v4

- src/core_modules/capture-core/components/Pages/MainPage/EventWorkingLists/RowMenuSetup/EventWorkingListsRowMenuSetup.component.js
- broken after introducing tei working lists
> fix: delete event

- cypress/integration/EventWorkingLists/EventWorkingListsDev.feature
- cypress/integration/EventWorkingLists/EventWorkingListsDev/index.js
- cypress/integration/EventWorkingLists/EventWorkingListsUser.feature
- cypress/integration/EventWorkingLists/EventWorkingListsUser/index.js
- cypress/integration/TeiWorkingLists/TeiWorkingListsDev.feature
- cypress/integration/TeiWorkingLists/TeiWorkingListsDev/index.js
- cypress/integration/TeiWorkingLists/TeiWorkingListsUser.feature
- cypress/integration/TeiWorkingLists/TeiWorkingListsUser/index.js
- src/core_modules/capture-core/components/DataTable/SortLabelWrapper.component.js
- src/core_modules/capture-core/components/List/OnlineList/OnlineList.component.js
- src/core_modules/capture-core/components/ListView/Filters/Contents/FilterSelectorContents.component.js
- src/core_modules/capture-core/components/ListView/Filters/Contents/withButtons.js
- src/core_modules/capture-core/components/Pages/MainPage/EventWorkingLists/EventWorkingLists.component.js
- src/core_modules/capture-core/components/Pages/MainPage/TeiWorkingLists/TeiWorkingLists.component.js
- src/core_modules/capture-core/components/Pages/MainPage/TeiWorkingLists/epics/teiViewEpics/helpers/initTeiWorkingListsView.js
- src/core_modules/capture-core/components/Pagination/withRowsPerPageSelector.js
e2e tests and integration tests for [DHIS2-9276](https://jira.dhis2.org/browse/DHIS2-9276) and the old event working lists.
> test: DHIS2-9276 cypress tests

- cypress/integration/TeiWorkingLists/TeiWorkingListsUser.feature
- cypress/integration/TeiWorkingLists/TeiWorkingListsUser/index.js
some text errors @geethaalwan found in my tests.
> chore: DHIS2-9276 minor text changes for tests

- cypress/integration/LockedSelector.feature
- cypress/integration/LockedSelector/index.js
- i18n/en.pot
- src/core_modules/capture-core/components/LockedSelector/LockedSelector.epics.js
- src/core_modules/capture-core/components/LockedSelector/QuickSelector/OrgUnitSelector.component.js
- src/core_modules/capture-core/components/LockedSelector/QuickSelector/Program/ProgramSelector.component.js
- src/core_modules/capture-core/components/LockedSelector/QuickSelector/SingleLockedSelect.component.js
- src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPage.component.js
Hey Joakim! We are reaching the end of this!! 🌿  
This one coves the locked selector with e2e tests
> fix: DHIS2-10161 [part 09] Create enrollment page with routing | writes e2e tests

- cypress/integration/LockedSelector.feature
- cypress/integration/LockedSelector/index.js
- i18n/en.pot
- src/core_modules/capture-core/components/LockedSelector/LockedSelector.epics.js
- src/core_modules/capture-core/components/LockedSelector/QuickSelector/OrgUnitSelector.component.js
- src/core_modules/capture-core/components/LockedSelector/QuickSelector/Program/ProgramSelector.component.js
- src/core_modules/capture-core/components/LockedSelector/QuickSelector/SingleLockedSelect.component.js
- src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPage.component.js
- src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPage.container.js
- src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPage.types.js
https://jira.dhis2.org/browse/DHIS2-10373
Adds links that when clicking them you are taken to either working lists or registration page. 
Perhaps we want to rephrase the text. Please let me know
> fix: DHIS2-10161 [part 08] Create enrollment page with routing | adds links on the informative message for Event programs

- cypress/integration/LockedSelector.feature
- cypress/integration/LockedSelector/index.js
- i18n/en.pot
- src/core_modules/capture-core/components/LockedSelector/LockedSelector.epics.js
- src/core_modules/capture-core/components/LockedSelector/QuickSelector/OrgUnitSelector.component.js
- src/core_modules/capture-core/components/LockedSelector/QuickSelector/Program/ProgramSelector.component.js
- src/core_modules/capture-core/components/LockedSelector/QuickSelector/QuickSelector.component.js
- src/core_modules/capture-core/components/LockedSelector/QuickSelector/QuickSelector.container.js
- src/core_modules/capture-core/components/LockedSelector/QuickSelector/SingleLockedSelect.component.js
- src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPage.actions.js
- src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPage.component.js
- src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPage.container.js
- src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPage.epics.js
- src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPage.types.js
- src/core_modules/capture-core/reducers/descriptions/enrollmentPage.reducerDescription.js
https://jira.dhis2.org/browse/DHIS2-10370
We are having better wording on the locked selector. Replacing the "Tracked entrity type" with the actual tet name. In the case bellow is Person. Could be anything tho :)
> fix: DHIS2-10161 [part 07] Create enrollment page with routing | adds the tet name on the locked selector

- cypress/integration/EnrollmentPage/index.js
- cypress/integration/LockedSelector.feature
- cypress/integration/LockedSelector/index.js
- cypress/support/helpers.js
- src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPage.container.js
- src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPage.epics.js
hey :wave: another bug I found. Is described here https://jira.dhis2.org/browse/DHIS2-10372. Also fixed some flaky tests
> feat: DHIS2-10161 [part 08] Create enrollment page with routing | fixes bug where page will be in infinite loop

- cypress/integration/EnrollmentPage/index.js
- cypress/integration/LockedSelector.feature
- cypress/integration/LockedSelector/index.js
- cypress/support/helpers.js
- src/core_modules/capture-core/components/LockedSelector/LockedSelector.actions.js
- src/core_modules/capture-core/components/LockedSelector/LockedSelector.epics.js
- src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPage.container.js
- src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPage.epics.js
- src/core_modules/capture-core/reducers/descriptions/activePage.reducerDescription.js
- src/core_modules/capture-core/reducers/descriptions/app.reducerDescriptionGetter.js
- src/core_modules/capture-core/reducers/descriptions/currentSelections.reducerDescriptionGetter.js
Basically I am trying to avoid that we fetch org units when they are already in the store
> feat: DHIS2-10161 [part 07] Create enrollment page with routing | avoid unnecessary fetching of orgUnits on the locked selector

- cypress/integration/EnrollmentPage.feature
- cypress/integration/EnrollmentPage/index.js
- cypress/integration/LockedSelector.feature
- cypress/integration/LockedSelector/index.js
- cypress/support/helpers.js
- src/core_modules/capture-core/components/LockedSelector/LockedSelector.actions.js
- src/core_modules/capture-core/components/LockedSelector/LockedSelector.epics.js
- src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPage.container.js
- src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPage.epics.js
- src/core_modules/capture-core/components/Pages/New/NewPage.container.js
- src/core_modules/capture-core/components/Pages/New/NewPage.types.js
- src/core_modules/capture-core/hooks/useMissingCategoriesInProgramSelection.js
- src/core_modules/capture-core/reducers/descriptions/activePage.reducerDescription.js
- src/core_modules/capture-core/reducers/descriptions/app.reducerDescriptionGetter.js
- src/core_modules/capture-core/reducers/descriptions/currentSelections.reducerDescriptionGetter.js
Hey 👋, the bug is described here https://jira.dhis2.org/browse/DHIS2-10471. Also covering this use-case with tests
> feat: DHIS2-10161 [part 06] Create enrollment page with routing | fixes bug on new page 

- cypress/integration/EnrollmentPage.feature
- cypress/integration/EnrollmentPage/index.js
- cypress/integration/LockedSelector.feature
- cypress/integration/LockedSelector/index.js
- cypress/integration/NewPage/index.js
- cypress/support/helpers.js
- i18n/en.pot
- src/core_modules/capture-core/components/LockedSelector/LockedSelector.actions.js
- src/core_modules/capture-core/components/LockedSelector/LockedSelector.epics.js
- src/core_modules/capture-core/components/LockedSelector/QuickSelector/Program/ProgramSelector.component.js
- src/core_modules/capture-core/components/LockedSelector/QuickSelector/QuickSelector.container.js
- src/core_modules/capture-core/components/LockedSelector/QuickSelector/SingleLockedSelect.component.js
- src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPage.actions.js
- src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPage.component.js
- src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPage.container.js
- src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPage.epics.js
- src/core_modules/capture-core/components/Pages/Enrollment/MissingMessage.component.js
- src/core_modules/capture-core/components/Pages/New/NewPage.container.js
- src/core_modules/capture-core/components/Pages/New/NewPage.types.js
- src/core_modules/capture-core/hooks/useMissingCategoriesInProgramSelection.js
- src/core_modules/capture-core/metaData/helpers/getScopeInfo.js
- src/core_modules/capture-core/reducers/descriptions/activePage.reducerDescription.js
- src/core_modules/capture-core/reducers/descriptions/app.reducerDescriptionGetter.js
- src/core_modules/capture-core/reducers/descriptions/currentSelections.reducerDescriptionGetter.js
- src/core_modules/capture-core/reducers/descriptions/enrollmentPage.reducerDescription.js
Hey 👋 
This adds the suggestions from Joe on wording and also I am adding the case where the selected program accepts "building" tracked entity type, not "person".
> feat: DHIS2-10161 [part 05] Create enrollment page with routing | demo improvements

- src/core_modules/capture-core/components/LockedSelector/LockedSelector.component.js
- src/core_modules/capture-core/components/LockedSelector/LockedSelector.types.js
- src/core_modules/capture-core/components/Pages/New/newPage.epics.js
- src/core_modules/capture-core/components/Pages/Search/SearchPage.epics.js
There was a bug in that I found out. 
The bug was that if you were in a view event page and you would press "New person in '....' program" then you will be in an endless loading state. 
I am fixing this here.
> feat: DHIS2-10161 [part 04]  Create enrollment page with routing | bug on the view Page while you press new button

- cypress/integration/EventWorkingLists/EventWorkingListsDev/index.js
- cypress/integration/EventWorkingLists/EventWorkingListsUser/index.js
- cypress/integration/NewPage/index.js
Minor cypress test fixes after updating the ca-test-2.36 instance.
> fix: broken cypress tests

- src/core_modules/capture-core/components/DataEntries/Enrollment/actions/open.actionBatchs.js
I like it when prs are close to one line! 
https://jira.dhis2.org/browse/DHIS2-10312
Basically adds default value in the enrollment date
> feat: DHIS2-10312 adds default value in enrolment date

- src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.epics.js
- src/core_modules/capture-core/metaData/Program/ProgramStage.js
- src/core_modules/capture-core/metaDataMemoryStoreBuilders/programs/factory/programStage/ProgramStageFactory.js
- src/core_modules/capture-core/metaDataStoreLoaders/programs/quickStoreOperations/storePrograms.js
- src/core_modules/capture-core/storageControllers/cache.types.js
The ticker is here Joakim :) https://jira.dhis2.org/browse/DHIS2-10315
Ehm basically I would look in the design doc and specifically in the [Enrollment auto generated events](https://docs.google.com/document/d/1E5dBP5_BZZ0pLt573Xd0GQB6kve2WUpNdoew3kCFnUo/edit#heading=h.e4oyflha5yjy) header for information on how this works.
> feat: DHIS2-10315 Autogenerate event when submitting enrollment

- cypress/integration/EventWorkingLists/EventWorkingListsUser.feature
- cypress/integration/EventWorkingLists/EventWorkingListsUser/index.js
- src/core_modules/capture-core/components/Pages/MainPage/EventWorkingLists/helpers/eventFilters/apiEventFilterToClientConfigConverter/convertToClientConfig.js
- src/core_modules/capture-core/components/Pages/MainPage/EventWorkingLists/helpers/eventFilters/clientConfigToApiEventFilterQueryCriteriaConverter/convertToEventFilterEventQueryCriteria.js
- src/core_modules/capture-core/components/Pages/MainPage/EventWorkingLists/types/apiTemplate.types.js
JIRA-issue: [DHIS2-10461](https://jira.dhis2.org/browse/DHIS2-10461)
Fixed an issue that caused the date filters to not save properly when saving a working list (eventFilters in the api)
> fix: DHIS2-10461 Date filters

- i18n/en.pot
- src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/EnrollmentRegistrationEntry.component.js
- src/core_modules/capture-core/components/DataEntries/TeiRegistrationEntry/TeiRegistrationEntry.component.js
For ticket and description Joakim please see https://jira.dhis2.org/browse/DHIS2-10136
> feat: adds the cancel button

- cypress/integration/EventWorkingLists/EventWorkingListsDev/index.js
- cypress/integration/EventWorkingLists/EventWorkingListsUser/index.js
- cypress/integration/NewPage/index.js
- src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.epics.js
- src/core_modules/capture-core/components/Pages/Search/SearchForm/SearchForm.epics.js
- src/core_modules/capture-core/components/Pages/Search/SearchResults/SearchResults.component.js
- src/core_modules/capture-core/utils/navigateToTrackedEntityDashboard.js
Hey both 
ticket is https://jira.dhis2.org/browse/DHIS2-10525
As we have discussed I encoded the url, let me know if you find that I missed anything.
> feat: DHIS2-10525 adds url

- src/core_modules/capture-core/components/Pages/MainPage/TeiWorkingLists/ReduxProvider/TeiWorkingListsReduxProvider.container.js
ticket: [DHIS2-10326](https://jira.dhis2.org/browse/DHIS2-10326)
Open enrollment in the old tracker capture app from the working lists
> feat: DHIS2-10326 open enrollment from working list

- .env
> chore: update to 36

- cypress/integration/EnrollmentPage/index.js
- cypress/integration/LockedSelector.feature
- cypress/integration/LockedSelector/index.js
- cypress/integration/NewEventThroughAddRelationship/index.js
- cypress/integration/NewPage.feature
- cypress/integration/NewPage/index.js
- cypress/integration/SearchForDuplicatesThroughAddRelationship/index.js
- cypress/integration/SearchPage.feature
- cypress/integration/SearchPage/index.js
- cypress/integration/SearchThroughAddRelationship/index.js
- cypress/integration/WorkingLists/EventWorkingLists/EventWorkingListsDev.feature
- cypress/integration/WorkingLists/EventWorkingLists/EventWorkingListsDev/index.js
- cypress/integration/WorkingLists/EventWorkingLists/EventWorkingListsUser.feature
- cypress/integration/WorkingLists/EventWorkingLists/EventWorkingListsUser/index.js
- cypress/integration/WorkingLists/TeiWorkingLists/TeiWorkingListsDev.feature
- cypress/integration/WorkingLists/TeiWorkingLists/TeiWorkingListsDev/index.js
- cypress/integration/WorkingLists/TeiWorkingLists/TeiWorkingListsUser.feature
- cypress/integration/WorkingLists/TeiWorkingLists/TeiWorkingListsUser/index.js
- cypress/integration/WorkingLists/sharedSteps.js
- cypress/integration/sharedSteps.js
- src/core_modules/capture-core/components/LockedSelector/LockedSelector.epics.js
backports the [ticket](https://jira.dhis2.org/browse/DHIS2-10584) and the tests to v36
> fix: backport on v36 DHIS2-10584-program-error

- cypress/integration/SearchPage/index.js
- i18n/en.pot
- src/core_modules/capture-core/components/LockedSelector/QuickSelector/ActionButtons.component.js
- src/core_modules/capture-core/components/Pages/Search/SearchForm/SearchForm.component.js
- src/core_modules/capture-core/components/Pages/Search/SearchPage.component.js
https://jira.dhis2.org/browse/DHIS2-9931
> fix: DHIS2-9931 wording from Find to Search

- i18n/en.pot
- src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.component.js
On testing there was a bug found here. You can see it in the comment of the ticket. https://jira.dhis2.org/browse/DHIS2-10525
> fix: DHIS2-10525 adds back functionality for the view dashboard in case of douplicate modal

- src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.epics.js
- src/core_modules/capture-core/metaData/Program/ProgramStage.js
- src/core_modules/capture-core/metaDataMemoryStoreBuilders/programs/factory/programStage/ProgramStageFactory.js
- src/core_modules/capture-core/metaDataStoreLoaders/programs/quickStoreOperations/storePrograms.js
- src/core_modules/capture-core/storageControllers/cache.types.js
fixes bug related to the min days from start
> chore: uses minDayFromStart

- cypress/integration/WorkingLists/TeiWorkingLists/TeiWorkingListsDev.feature
- cypress/integration/WorkingLists/TeiWorkingLists/TeiWorkingListsDev/index.js
- cypress/integration/WorkingLists/TeiWorkingLists/TeiWorkingListsUser.feature
- cypress/integration/WorkingLists/TeiWorkingLists/TeiWorkingListsUser/index.js
- src/core_modules/capture-core/components/Pages/MainPage/TeiWorkingLists/epics/teiViewEpics/helpers/initTeiWorkingListsView.js
ticket: [DHIS2-10715](https://jira.dhis2.org/browse/DHIS2-10715)
> fix: DHIS2-10715 working lists default sorting 

- cypress/integration/WorkingLists/TeiWorkingLists/TeiWorkingListsDev.feature
- cypress/integration/WorkingLists/TeiWorkingLists/TeiWorkingListsDev/index.js
- cypress/integration/WorkingLists/TeiWorkingLists/TeiWorkingListsUser.feature
- cypress/integration/WorkingLists/TeiWorkingLists/TeiWorkingListsUser/index.js
- src/core_modules/capture-core/components/Pages/MainPage/TeiWorkingLists/epics/teiViewEpics/helpers/initTeiWorkingListsView.js
Ticket: [DHIS2-10715](https://jira.dhis2.org/browse/DHIS2-10715)
> fix: DHIS2-10715 working lists default sorting

- src/core_modules/capture-core/components/Pages/MainPage/WorkingListsCommon/hooks/useDataSource.js
ticket: [DHIS2-10716](https://jira.dhis2.org/browse/DHIS2-10716)
> fix: DHIS2-10716 use code if option not found

- cypress/integration/SearchPage.feature
- cypress/integration/SearchPage/index.js
- src/core_modules/capture-core/reducers/descriptions/currentSelections.reducerDescriptionGetter.js
https://jira.dhis2.org/browse/DHIS2-10738
Fixes the bug as it is described in the ticket and covers the case with tests
> fix: DHIS2-10738 pressing the back button after a fallback crashes app

- cypress/integration/SearchPage.feature
- cypress/integration/SearchPage/index.js
- src/core_modules/capture-core/reducers/descriptions/currentSelections.reducerDescriptionGetter.js
backports https://jira.dhis2.org/browse/DHIS2-10738
> fix: 10738 backport the crash of the button to 2.36.0

- src/core_modules/capture-core/components/Pages/Search/SearchForm/SearchForm.epics.js
Backports https://jira.dhis2.org/browse/DHIS2-10739 to 2.36.0
> fix: backports max count to 2.36.0

- src/core_modules/capture-core/components/Pages/MainPage/TeiWorkingLists/Setup/useDefaultColumnConfig.js
- src/core_modules/capture-core/metaDataMemoryStoreBuilders/programs/factory/enrollment/DataElementFactory.js
- src/core_modules/capture-core/metaDataMemoryStoreBuilders/trackedEntityTypes/factory/TrackedEntityType/DataElementFactory.js
- src/core_modules/capture-core/metaDataStoreLoaders/trackedEntityAttributes/quickStoreOperations/storeTrackedEntityAttributes.js
- src/core_modules/capture-core/storageControllers/cache.types.js
[DHIS2-10765](https://jira.dhis2.org/browse/DHIS2-10765)
- Use "form name" as label (instead of name) for forms. 
- Use "name" as header (instead of form name) for working lists.
Note: 1 test failing because of backend problem
> fix: DHIS2-10765 use form names

- src/core_modules/capture-core/components/DataEntries/index.js
- src/core_modules/capture-core/components/DataEntryWidgetOutput/DataEntryWidgetOutput.container.js
- src/core_modules/capture-core/components/Pages/New/NewPage.container.js
- src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/DataEntry/useSaveButtonText.js
- src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/RegisterTei.component.js
- src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/RegisterTei.container.js
- src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/RegisterTei.types.js
- src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/open.epics.js
- src/core_modules/capture-core/reducers/descriptions/activePage.reducerDescription.js
- src/core_modules/capture-core/reducers/descriptions/newRelationship.reducerDescription.js
- src/core_modules/capture-ui/FormBuilder/FormBuilder.component.js
hey this is cherry picking and porting the https://jira.dhis2.org/browse/DHIS2-10711 into `patch/2.36.0`
> fix: porting DHIS2-10711-double-calls into 2.36.0

- src/core_modules/capture-core/components/D2Form/asyncHandlerHOC/actions.js
- src/core_modules/capture-core/components/D2Form/asyncHandlerHOC/withAsyncHandler.js
- src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/NewRelationshipWrapper/NewEventNewRelationshipWrapper.actions.js
- src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/NewRelationshipWrapper/NewEventNewRelationshipWrapper.component.js
- src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/NewRelationshipWrapper/NewEventNewRelationshipWrapper.container.js
- src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/SingleEventRegistrationEntry.container.js
- src/core_modules/capture-core/components/DataEntry/CancelButton.container.js
- src/core_modules/capture-core/components/DataEntry/common/dataEntryHasChanges.js
- src/core_modules/capture-core/components/DataEntry/withBrowserBackWarning.js
- src/core_modules/capture-core/components/Dialogs/ConfirmDialog.component.js
- src/core_modules/capture-core/components/LockedSelector/LockedSelector.component.js
- src/core_modules/capture-core/components/LockedSelector/LockedSelector.container.js
- src/core_modules/capture-core/components/Pages/New/NewPage.actions.js
- src/core_modules/capture-core/components/Pages/New/NewPage.component.js
- src/core_modules/capture-core/components/Pages/New/NewPage.container.js
- src/core_modules/capture-core/components/Pages/New/NewPage.types.js
- src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.container.js
- src/core_modules/capture-core/components/Pages/ViewEvent/ViewEventPage.container.js
- src/core_modules/capture-core/reducers/descriptions/dataEntry.reducerDescription.js
- src/core_modules/capture-core/reducers/descriptions/form.reducerDescription.js
- src/core_modules/capture-ui/FormBuilder/FormBuilder.component.js
Back ports the https://jira.dhis2.org/browse/DHIS2-10206 on `2.36.0`
> fix: backport [DHIS2-10206] displays dialog when data has entered and user is exiting the page

- cypress/integration/NewEventThroughAddRelationship/index.js
- cypress/integration/SearchPage/index.js
- src/core_modules/capture-core/components/Pages/Search/SearchForm/SearchForm.epics.js
- src/core_modules/capture-core/components/PossibleDuplicatesDialog/possibleDuplicatesDialog.epics.js
> fix: DHIS2-10713 when optionSet use EQ to filter 

- src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.epics.js
Hey this is fixing the https://jira.dhis2.org/browse/DHIS2-10723 on branch v36
> fix: DHIS2-10723

- src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.epics.js
covers all cases for the ticket
> fix: DHIS2-10723 covers all cases

- cypress/integration/NewEventThroughAddRelationship/index.js
- cypress/integration/SearchPage/index.js
- src/core_modules/capture-core/components/Pages/Search/SearchForm/SearchForm.epics.js
- src/core_modules/capture-core/components/PossibleDuplicatesDialog/possibleDuplicatesDialog.epics.js
> fix: DHIS2-10713 when optionSet use EQ to filter

- cypress/integration/NewEventThroughAddRelationship/index.js
- cypress/integration/SearchPage/index.js
- src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.epics.js
Backports the missing part for the fix on the the polygon https://jira.dhis2.org/browse/DHIS2-10723 
Also fixes some broken tests.
> fix: DHIS2-10723 completes for all cases

- cypress/integration/EnrollmentPage/WidgetEnrollment.feature
- cypress/integration/EnrollmentPage/WidgetEnrollment/index.js
- cypress/integration/EnrollmentPage/sharedSteps.js
- src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/EnrollmentPageDefault.component.js
- src/core_modules/capture-core/components/WidgetEnrollment/WidgetEnrollment.component.js
- src/core_modules/capture-core/components/WidgetEnrollment/enrollment.types.js
- src/core_modules/capture-core/components/WidgetEnrollment/index.js
[DHIS2-10941]( https://jira.dhis2.org/browse/DHIS2-10941) Added an empty version of the enrollment widget.
> feat: [DHIS2-10941] Enrollment widget

- cypress/integration/WorkingLists/EventWorkingLists/EventWorkingListsUser/index.js
Backport of the sharing settings test fix.
> fix: sharing settings test

- src/core_modules/capture-core/flow/app-runtime_v2.x.x.js
Fix and simplify the type definition for useDataQuery.
> chore: useDataQuery type definition

- package.json
Upgrade version capture-app to the new release
> fix: upgrade version to v37

- i18n/en.pot
- src/core_modules/capture-core/components/Pages/EditEvent/DataEntry/EditEventDataEntry.component.js
- src/core_modules/capture-core/components/Pages/NewEvent/DataEntry/DataEntry.component.js
- src/core_modules/capture-core/components/Pages/NewEvent/DataEntry/epics/defaultColumnConfiguration/defaultConfigGetter.js
- src/core_modules/capture-core/components/Pages/ViewEvent/EventDetailsSection/EditEventDataEntry/EditEventDataEntry.component.js
- src/core_modules/capture-core/components/Pages/ViewEvent/EventDetailsSection/EventDetailsSection.component.js
- src/core_modules/capture-core/components/Pages/ViewEvent/EventDetailsSection/ViewEventDataEntry/ViewEventDataEntry.component.js
- src/core_modules/capture-core/components/Section/SectionHeaderSimple.component.js
- src/core_modules/capture-core/components/TeiSearch/SearchOrgUnitSelector/SearchOrgUnitSelector.component.js
- src/core_modules/capture-core/converters/clientToList.js
- src/core_modules/capture-core/converters/clientToView.js
- src/core_modules/capture-ui/CoordinateField/CoordinateField.component.js
Backporting to 34 from https://github.com/dhis2/capture-app/pull/1617
(cherry picked from commit 70b103e619d12360fc0f6dca371bb129f31abdb2)
> fix(translations): [DHIS2-8998] missing translation

- src/core_modules/capture-core/components/DataEntry/withSaveHandler/withSaveHandler.js
- src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/Enrollment/ConfiguredEnrollment.component.js
Error showing regardless of complete status. Backport to version 35. 
Please follow https://github.com/dhis2/capture-app/pull/1582 for instructions on how to test and review.
https://jira.dhis2.org/browse/DHIS2-10394
> DHIS2-10394 Error on complete showing regardless of status

- src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/EnrollmentRegistrationEntry.component.js
- src/core_modules/capture-core/components/DataEntry/withSaveHandler/withSaveHandler.js
Error showing regardless of complete status. Backport to version 36.
Please follow #1582 for instructions on how to test and review.
https://jira.dhis2.org/browse/DHIS2-10394
> DHIS2-10394 Error on complete v36

- src/core_modules/capture-core/components/DataEntry/withSaveHandler/withSaveHandler.js
- src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/Enrollment/ConfiguredEnrollment.component.js
https://jira.dhis2.org/browse/DHIS2-10394
Backport to v34. 
See https://github.com/dhis2/capture-app/pull/1582 for original PR.
> DHIS2-10394 Error on complete v34

- package.json
Automize eslint and flow code checks.
> chore: add lint and flow checks to pre-push hook

- src/core_modules/capture-core/components/WidgetFeedback/WidgetFeedback.component.js
- src/core_modules/capture-core/components/WidgetFeedback/WidgetFeedback.types.js
- src/core_modules/capture-core/components/WidgetFeedback/index.js
Using the widget-component to create a generic feedback-wrapper component.
https://jira.dhis2.org/browse/DHIS2-10977
> feat: DHIS2-10977 Create generic wrapper WidgetComponent 

- cypress/integration/LockedSelector.feature
Let's temporary remove these flaky tests until the locked selector is refactored here: https://jira.dhis2.org/browse/TECH-580
> chore: temporary remove flaky locked selector tests

- cypress/integration/WorkingLists/TeiWorkingLists/TeiWorkingListsUser/index.js
Fix cypress tests by rolling back changes from https://github.com/dhis2/capture-app/pull/1809/files#diff-321a77d9cabfbb873a01dccb6ebfd4db62186022dda09854ae9d1934ac05d368
> fix: TeiWorkingListsUsers.feature rollback previous changes

- src/core_modules/capture-core/components/Pages/ViewEvent/epics/getCategoriesDataFromEvent.js
Small change to fix the bug where posting the link would break the capture app. 
https://jira.dhis2.org/browse/DHIS2-10330
> DHIS2-10330 viewEvent URL link for category options

- src/core_modules/capture-core/components/Pages/ViewEvent/epics/getCategoriesDataFromEvent.js
Backport to v36 for https://github.com/dhis2/capture-app/pull/1881
Jira-issue: https://jira.dhis2.org/browse/DHIS2-10330
> DHIS2-10330 viewEvent URL link for category options V36

- src/core_modules/capture-core/components/Pages/ViewEvent/epics/getCategoriesDataFromEvent.js
Backport to v35 for https://github.com/dhis2/capture-app/pull/1881
Jira-issue: https://jira.dhis2.org/browse/DHIS2-10330
> DHIS2-10330 viewEvent URL link for category options V35

- src/core_modules/capture-core/components/Pages/ViewEvent/epics/getCategoriesDataFromEvent.js
Backport to v34 for https://github.com/dhis2/capture-app/pull/1881
Jira-issue: https://jira.dhis2.org/browse/DHIS2-10330
> DHIS2-10330 viewEvent URL link for category options V34

- src/core_modules/capture-core/components/WidgetIndicator/WidgetIndicatorContent/WidgetIndicatorContent.js
- src/core_modules/capture-core/components/WidgetIndicator/WidgetIndicatorContent/sortIndicatorsFn.js
Sorted the indicators in alphabetical order in the indicator widgets.
> [DHIS2-11573] Sort indicators alphabetically in indicator widget

- src/core_modules/capture-core/components/ListView/Menu/ListViewMenu.component.js
Migrate Material-UI Divider component to DHIS2/ui
> refactor: [TECH-605][TECH-654] Divider

- src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/Comments.component.js
- src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/StageDetail.component.js
- src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/hooks/helpers.js
- src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/hooks/useEventList.js
- src/core_modules/capture-core/events/getEnrollmentEvents.js
Add new column in stage list with icon and number of comments
> feat: [DHIS2-11594] implement comments in stages&events page

- src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/Comments.component.js
As discussion, I rename the `nbComments` to `commentsCount` to represent the total of comments in event
> chore: rename variable

- src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/StageDetail.component.js
Add plus icon on new event button `<IconPlus24 />`. Adjust the button to `secondary/small` to fit the design
> feat: [DHIS2-11615] add plus icon on new event button

- cypress/integration/EnrollmentPage/StagesAndEventsWidget.feature
- cypress/integration/EnrollmentPage/StagesAndEventsWidget/index.js
- i18n/en.pot
- src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/Stage.component.js
In case there is no event in the list, there should be a button to add new event. Clicking this button will navigate to `Add new event` page
> feat: [DHIS2-11652] show the add button for empty event stage

- cypress/integration/EnrollmentAddEventPage/EnrollmentAddEventPageNavigation.feature
- cypress/integration/LockedSelector.feature
- cypress/integration/LockedSelector/index.js
- i18n/en.pot
- src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/EnrollmentAddEventPage.component.js
- src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/EnrollmentAddEventPage.constants.js
- src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/EnrollmentAddEventPage.container.js
- src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/EnrollmentAddEventPage.types.js
- And the `ScopeSelector` in the `EnrollmpentEventNew` page
- If the user tries to leave the page after it has interacted with the form, the warning pop-up is triggered.
> feat: [DHIS2-11389] add ScopeSelector in enrollmentEventNew page 

- src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/EnrollmentAddEventPage.component.js
- src/core_modules/capture-core/components/WidgetEnrollmentEventNew/DataEntry/DataEntry.component.js
- src/core_modules/capture-core/components/WidgetEnrollmentEventNew/Validated/Validated.component.js
- Remove duplicate headers
- Add padding left
> fix: [DHIS2-11694] remove duplicate header and add padding

- src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/StageDetail.component.js
> fix: Fix sorting error on comment column

- cypress/integration/WidgetsForEnrollmentPages/WidgetsForEnrollmentAddEventPage.feature
- cypress/integration/WidgetsForEnrollmentPages/WidgetsForEnrollmentDashboard.feature
- cypress/integration/WidgetsForEnrollmentPages/WidgetsForEnrollmentEditEvent.feature
- i18n/en.pot
disable flaky test cases related to enrollment status edit.
> fix: [DHIS2-11482] disable flaky Cypress test cases

- cypress/integration/EnrollmentPage/StagesAndEventsWidget.feature
- src/core_modules/capture-core/components/Pages/StageEvent/StageEventList/StageEventList.component.js
- src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/StageDetail.component.js
Page can not go to program type TRACKER 
- I keep the code in place for TRACKER_PROGRAM but hide the `Go to xxx` button until the page is fully developed
> fix: [DHIS2-11733] fix program stage list for tracker program

- cypress/integration/EnrollmentPage/StagesAndEventsWidget.feature
- src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/StageDetail.component.js
> fix: [DHIS2-11733] hide go to Program stage list v37

- src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/EnrollmentAddEventPage.container.js
- src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/EnrollmentAddEventPage.types.js
- src/core_modules/capture-core/components/WidgetEnrollmentEventNew/AccessVerification/AccessVerification.component.js
- src/core_modules/capture-core/components/WidgetEnrollmentEventNew/AccessVerification/AccessVerification.container.js
- src/core_modules/capture-core/components/WidgetEnrollmentEventNew/AccessVerification/accessVerification.types.js
- src/core_modules/capture-core/components/WidgetEnrollmentEventNew/WidgetEnrollmentEventNew.types.js
(cherry picked from commit c85f0f03ec9e400437b5a92e97aed5eb2346f148)
Backport to v37.
> fix: [DHIS2] Change reducer name in widgets-hook

- src/core_modules/capture-core/components/DataEntry/withSaveHandler/withSaveHandler.js
- src/core_modules/capture-core/components/WidgetEnrollmentEventNew/Validated/Validated.container.js
- Trigger the error popup when the user clicks the "Complete" button in the new enrollment event form. [DHIS2-11669](https://jira.dhis2.org/browse/DHIS2-11669). 
- send the correct event status when the user clicks the "Save without competing"
> fix: [DHIS2-11669][DHIS2-11746] save new enrollment event validation & statuses

- src/core_modules/capture-core/components/DataEntry/withSaveHandler/withSaveHandler.js
- src/core_modules/capture-core/components/WidgetEnrollmentEventNew/Validated/Validated.container.js
Backport to v37 with cherry picked from commit 814bd3c5a33c70b22747c446e9ebaa1742eda3c1 for the bugs https://jira.dhis2.org/browse/DHIS2-11669 and https://jira.dhis2.org/browse/DHIS2-11746
> fix: [DHIS2-11669][DHIS2-11746] save new enrollment event validation 

- src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/epics/eventList.epics.js
- src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/epics/getEventListData.js
- src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/types/apiTemplate.types.js
> [TECH-681] Refactor the api-calls to /event from WorkingList

- cypress/integration/WidgetsForEnrollmentPages/WidgetEnrollmentComment/index.js
- cypress/integration/WidgetsForEnrollmentPages/WidgetsForEnrollmentDashboard.feature
- cypress/integration/WidgetsForEnrollmentPages/WidgetsForEnrollmentDashboard/index.js
- i18n/en.pot
- src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/EnrollmentPageDefault.component.js
- src/core_modules/capture-core/components/WidgetComment/CommentSection/CommentSection.js
- src/core_modules/capture-core/components/WidgetComment/WidgetComment.component.js
- src/core_modules/capture-core/components/WidgetComment/WidgetComment.types.js
- src/core_modules/capture-core/components/WidgetEnrollmentComment/WidgetEnrollmentComment.actions.js
- src/core_modules/capture-core/components/WidgetEnrollmentComment/WidgetEnrollmentComment.component.js
- src/core_modules/capture-core/components/WidgetEnrollmentComment/WidgetEnrollmentComment.epics.js
- src/core_modules/capture-core/components/WidgetEnrollmentComment/WidgetEnrollmentComment.types.js
- src/core_modules/capture-core/components/WidgetEnrollmentComment/index.js
- src/core_modules/capture-core/components/WidgetEventComment/WidgetEventComment.component.js
- src/core_modules/capture-core/reducers/descriptions/enrollment.reducerDescription.js
- src/epics/trackerCapture.epics.js
* feat: [DHIS2-11616] add comment widget
* feat: [DHIS2-11616] add event note
* feat: [DHIS2-11616] update comment
* feat: [DHIS2-11616] add number of notes in header
* feat: [DHIS2-11616] update folders name
* feat: [DHIS2-11616] extract comment component
* chore: [DHIS2-11616] update action naming
* chore: [DHIS2-11616] add cypress test
* chore: [DHIS2-11616] update url
* feat: [DHIS2-11632] implement enrollment comment
* chore: [DHIS2-11632] fix flow
* chore: [DHIS2-11632] add cypress test
* chore: [DHIS2-11632] custom title and placeholder
* chore: [DHIS2-11616] minor change
* chore: [DHIS2-11616] add max height to section and handle empty section
* chore: [DHIS2-11632] update enrollment comment
* chore: [DHIS2-11632] fix flow
* chore: solve issue post merge
* chore: [DHIS2-11632] put …
> feat: [DHIS2-11632] Widget enrollment comment (#2088) backport to v37

- cypress/integration/WidgetsForEnrollmentPages/WidgetsForEnrollmentDashboard.feature
- cypress/integration/WidgetsForEnrollmentPages/WidgetsForEnrollmentDashboard/index.js
- src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/EnrollmentPageDefault.container.js
- src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/hooks/index.js
- src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/hooks/useOrganisationUnit.js
[Ticket](https://jira.dhis2.org/browse/DHIS2-11783) Program rules are not executed the first time 
Fetch the `orgUnit` if it's not present
> fix: [DHIS2-11783] fetch orgUnit if none present

- cypress/integration/LockedSelector.feature
- cypress/integration/LockedSelector/index.js
- src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPage.epics.js
- src/core_modules/capture-core/components/Pages/common/EnrollmentOverviewDomain/useTeiDisplayName.js
- src/core_modules/capture-core/components/ScopeSelector/QuickSelector/SingleLockedSelect.component.js
backport to `v37` with cherry picked from commit c2376b2aac209e442d39f96f185876d8fad6ed3f
> fix: [DHIS2-11814][DHIS2-11822] add fallback for tei missing name

- src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/EnrollmentRegistrationEntry.component.js
- src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/epics/addRelationshipForNewSingleEvent.epics.js
- src/core_modules/capture-core/components/DataEntries/TeiRegistrationEntry/TeiRegistrationEntry.component.js
- src/core_modules/capture-core/components/DataEntries/withErrorMessagePostProcessor/UniqueTEADuplicate/ErrorMessageCreator.component.js
- src/core_modules/capture-core/components/FormFields/New/HOC/withLabel.js
- src/core_modules/capture-core/components/LockedSelector/QuickSelector/ActionButtons.component.js
- src/core_modules/capture-core/components/Pages/Enrollment/MissingMessage.component.js
- src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/DataEntry/Enrollment/DataEntryEnrollment.component.js
- src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/DataEntry/TrackedEntityInstance/DataEntryTrackedEntityInstance.component.js
- src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/RegisterTei.component.js
- src/core_modules/capture-core/components/Pages/NewRelationship/TeiRelationship/SearchResults/TeiRelationshipSearchResults.component.js
- src/core_modules/capture-core/components/TopBarActions/TopBarActions.component.js
- src/core_modules/capture-core/components/WidgetEnrollment/WidgetEnrollment.component.js
- src/core_modules/capture-core/components/WidgetEnrollmentEventNew/SavingText/SavingText.component.js
- src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/Stage.component.js
- src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/StageDetail.component.js
Ticket: [DHIS2-11832](https://jira.dhis2.org/browse/DHIS2-11832) Special characters do not display properly in capture app
Using `{ interpolation : true }`
This is hard to test with cypress
> fix: [DHIS2-11832] escape special characters in i18n

- src/core_modules/capture-core/components/ListView/Filters/Filters.component.js
- src/core_modules/capture-core/components/ListView/types/listView.types.js
- src/core_modules/capture-core/components/WorkingLists/EventWorkingListsCommon/types/eventWorkingListsCommon.types.js
- src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/Setup/TeiWorkingListsSetup.component.js
- src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/Setup/useDefaultColumnConfig.js
- src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/types/concept.types.js
- src/core_modules/capture-core/components/WorkingLists/WorkingListsBase/workingListsBase.types.js
- src/core_modules/capture-core/metaData/DataElement/DataElement.js
- src/core_modules/capture-core/metaDataMemoryStoreBuilders/programs/factory/enrollment/DataElementFactory.js
https://jira.dhis2.org/browse/DHIS2-11795
Fix permission issue when using the ACCESSIBLE-mode in WorkingList-component.
> [DHIS2-11795] - Hide Non-searchable filters when in ACCESSIBLE-mode

- .env.cypress
- cypress/integration/EnrollmentAddEventPage/EnrollmentAddEventPageNavigation/index.js
- cypress/integration/EnrollmentEditEventPage/EnrollmentEditEventPageForm.feature
- cypress/integration/EnrollmentEditEventPage/EnrollmentEditEventPageForm/index.js
- cypress/integration/NewPage/index.js
- cypress/integration/TopBarActions.feature
- cypress/integration/TopBarActions/index.js
- cypress/integration/WidgetsForEnrollmentPages/WidgetsForEnrollmentAddEventPage.feature
- cypress/integration/WidgetsForEnrollmentPages/WidgetsForEnrollmentDashboard.feature
- cypress/integration/WidgetsForEnrollmentPages/WidgetsForEnrollmentEditEvent.feature
- cypress/integration/WorkingLists/EventWorkingLists/EventWorkingListsDev/index.js
- cypress/integration/WorkingLists/EventWorkingLists/EventWorkingListsUser/index.js
- cypress/integration/WorkingLists/sharedSteps.js
Need this to make the tests pass when we push changes to the branch.
> chore: change cypress instance and update tests

- package.json
- yarn.lock
Don't merge until approved by RCB/QA.
> fix: [DHIS2-11838] react-leaflet-draw rollback

- src/core_modules/capture-core/components/ListView/Filters/Filters.component.js
- src/core_modules/capture-core/components/ListView/types/listView.types.js
- src/core_modules/capture-core/components/WorkingLists/EventWorkingListsCommon/types/eventWorkingListsCommon.types.js
- src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/Setup/TeiWorkingListsSetup.component.js
- src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/Setup/useDefaultColumnConfig.js
- src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/types/concept.types.js
- src/core_modules/capture-core/components/WorkingLists/WorkingListsBase/workingListsBase.types.js
- src/core_modules/capture-core/metaData/DataElement/DataElement.js
- src/core_modules/capture-core/metaDataMemoryStoreBuilders/programs/factory/enrollment/DataElementFactory.js
> fix: [DHIS2-11795] -  Hide filter when in ACCESSIBLE mode

- src/core_modules/capture-core/components/ListView/Filters/Filters.component.js
- src/core_modules/capture-core/components/ListView/types/listView.types.js
- src/core_modules/capture-core/components/WorkingLists/EventWorkingListsCommon/types/eventWorkingListsCommon.types.js
- src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/Setup/TeiWorkingListsSetup.component.js
- src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/Setup/useDefaultColumnConfig.js
- src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/types/concept.types.js
- src/core_modules/capture-core/components/WorkingLists/WorkingListsBase/workingListsBase.types.js
- src/core_modules/capture-core/metaData/DataElement/DataElement.js
- src/core_modules/capture-core/metaDataMemoryStoreBuilders/programs/factory/enrollment/DataElementFactory.js
Backport to 2.37.0
https://jira.dhis2.org/browse/DHIS2-11795
> fix: [DHIS2-11795] Hide filter when in ACCESSIBLE mode - 2.37.0

- src/core_modules/capture-core/actions/navigateToEnrollmentOverview/navigateToEnrollmentOverview.epics.js
- src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getTeiListData/convertToClientTeis.js
- src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getTeiListData/getTeiListData.js
- src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getTeiListData/types/getiTeiListDataConcept.types.js
Fetch the ownerOrgUnit from the API and push with the navigation to TC.
https://jira.dhis2.org/browse/DHIS2-11850
> fix: [DHIS2-11850] Tracker fails to load when opening TEI without orgUnit

- src/core_modules/capture-core/actions/navigateToEnrollmentOverview/navigateToEnrollmentOverview.epics.js
- src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getTeiListData/convertToClientTeis.js
- src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getTeiListData/getTeiListData.js
- src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getTeiListData/types/getiTeiListDataConcept.types.js
> fix: [DHIS2-11850] OrgUnit undefined when navigating to tracker - 2.37.0

- src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/EnrollmentRegistrationEntry.component.js
- src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/epics/addRelationshipForNewSingleEvent.epics.js
- src/core_modules/capture-core/components/DataEntries/TeiRegistrationEntry/TeiRegistrationEntry.component.js
- src/core_modules/capture-core/components/DataEntries/withErrorMessagePostProcessor/UniqueTEADuplicate/ErrorMessageCreator.component.js
- src/core_modules/capture-core/components/FormFields/New/HOC/withLabel.js
- src/core_modules/capture-core/components/LockedSelector/QuickSelector/ActionButtons.component.js
- src/core_modules/capture-core/components/Pages/Enrollment/MissingMessage.component.js
- src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/DataEntry/Enrollment/DataEntryEnrollment.component.js
- src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/DataEntry/TrackedEntityInstance/DataEntryTrackedEntityInstance.component.js
- src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/RegisterTei.component.js
- src/core_modules/capture-core/components/Pages/NewRelationship/TeiRelationship/SearchResults/TeiRelationshipSearchResults.component.js
- src/core_modules/capture-core/components/TopBarActions/TopBarActions.component.js
- src/core_modules/capture-core/components/WidgetEnrollment/WidgetEnrollment.component.js
- src/core_modules/capture-core/components/WidgetEnrollmentEventNew/SavingText/SavingText.component.js
- src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/Stage.component.js
- src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/StageDetail.component.js
* fix: [DHIS2-11832] escape special charaters in i18n
* fix: [DHIS2-11832] fix special characters display
> fix: [DHIS2-11832] escape special characters in i18n (#2137)

- cypress/integration/EnrollmentPage/EnrollmentPageNavigation.feature
- cypress/integration/EnrollmentPage/EnrollmentPageNavigation/index.js
- src/core_modules/capture-core/actions/navigateToEnrollmentOverview/navigateToEnrollmentOverview.epics.js
- src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPage.component.js
- src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPage.container.js
- src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPage.epics.js
- src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/EnrollmentPageDefault.component.js
- src/core_modules/capture-core/components/Pages/Enrollment/useEnrollmentInfo.js
- src/core_modules/capture-core/components/ScopeSelector/hooks/useSetEnrollmentId.js
- src/core_modules/capture-core/reducers/descriptions/enrollmentDomain.reducerDescription.js
Ticket: [DHIS2-11830](https://jira.dhis2.org/browse/DHIS2-11830) Auto-select enrollment when opening enrollment dashboard
> feat: [DHIS2-11830] implement auto select enrollment

- cypress/integration/EnrollmentPage/EnrollmentPageNavigation.feature
- cypress/integration/EnrollmentPage/EnrollmentPageNavigation/index.js
- src/core_modules/capture-core/actions/navigateToEnrollmentOverview/navigateToEnrollmentOverview.epics.js
- src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPage.component.js
- src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPage.container.js
- src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPage.epics.js
- src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/EnrollmentPageDefault.component.js
- src/core_modules/capture-core/components/Pages/Enrollment/useEnrollmentInfo.js
- src/core_modules/capture-core/components/ScopeSelector/hooks/useSetEnrollmentId.js
- src/core_modules/capture-core/reducers/descriptions/enrollmentDomain.reducerDescription.js
* feat: [DHIS2-11830] implement auto select enrollment
* chore: [DHIS2-11830] add cypress test
* chore: [DHIS2-11830] replace epic by hook call
* chore: [DHIS2-11830] fix flow
* chore: [DHIS2-11830] add replace optional
* chore: [DHIS2-11830] fix flow
> feat: [DHIS2-11830] implement auto select enrollment (#2138) backport v37

- package.json
- yarn.lock
Align dependency resolution; reasons mentioned here: https://github.com/dhis2/capture-app/pull/2227
> chore: align dependency resolution

- i18n/en.pot
- src/core_modules/capture-core/components/DataSection/DataSection.component.js
- src/core_modules/capture-core/components/WidgetComment/CommentSection/CommentSection.js
- src/core_modules/capture-core/components/WidgetComment/index.js
- src/core_modules/capture-core/components/WidgetEventSchedule/InfoBox/InfoBox.component.js
- src/core_modules/capture-core/components/WidgetEventSchedule/ScheduleButtons/ScheduleButtons.component.js
- src/core_modules/capture-core/components/WidgetEventSchedule/ScheduleDate/ScheduleDate.component.js
- src/core_modules/capture-core/components/WidgetEventSchedule/WidgetEventSchedule.component.js
- src/core_modules/capture-core/components/WidgetEventSchedule/WidgetEventSchedule.container.js
- src/core_modules/capture-core/components/WidgetEventSchedule/widgetEventSchedule.types.js
[DHIS2-11863](https://jira.dhis2.org/browse/DHIS2-11863): Comment widget in scheduling tab
> feat: [DHIS2-11863] Add comment section to Schedule page

- src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/hooks/helpers.js
Test will be added when Schedule function finished
> fix: [DHIS2-12122] fix overdue condition

- cypress/integration/NewPage.feature
- cypress/integration/NewPage/index.js
- i18n/en.pot
- src/core_modules/capture-ui/CoordinateField/CoordinateField.component.js
[DHIS2-12179](https://jira.dhis2.org/browse/DHIS2-12179): Can’t Manually Write in GPS Coordinates into Event Capture
> fix: [DHIS2-12179] fix coordinate fields v36

- src/core_modules/capture-ui/CoordinateField/CoordinateField.component.js
[DHIS2-12179](): Fix coordinate fields Backporting to v34
> fix: [DHIS2-12179] fix coordinate fields v34

- src/core_modules/capture-core/metaData/Program/ProgramStage.js
- src/core_modules/capture-core/metaData/RenderFoundation/RenderFoundation.js
- src/core_modules/capture-core/metaDataMemoryStoreBuilders/programs/buildPrograms.js
- src/core_modules/capture-core/rules/actionsCreator/runRulesForEnrollmentEvent.js
- src/core_modules/capture-core/rules/actionsCreator/runRulesForSingleEvent.js
Program rules restricted to a specific program stage were not included in the program rules execution.
This only fixes the new enrollment event page. Will fix the edit page in a different ticket.
> fix: [DHIS2-12112] add missing programStage rules

- src/core_modules/capture-core/components/WidgetEventSchedule/hooks/useDetermineSuggestedScheduleDate.js
- src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageOverview/StageOverview.component.js
[DHIS2-11862](https://jira.dhis2.org/browse/DHIS2-11862?focusedCommentId=46078&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-46078): Verify eventDate exists when calculating the schedule date
> fix: [DHIS2-11862] verify if eventDate exists

- src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/StageDetail.component.js
- src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/epics/eventList.epics.js
[TECH-808](): Add ouMode to the events request from the working lists 
I also fixed the missing key in Enrollment page
> chore: [TECH-808] add ouMode

- cypress/integration/WorkingLists/EventWorkingLists/EventWorkingListsDev/index.js
- cypress/integration/WorkingLists/TeiWorkingLists/TeiWorkingListsDev/index.js
- src/components/AppLoader/AppLoader.component.js
- src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/epics/defaultColumnConfiguration/defaultConfigGetter.js
- src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/ViewMenuSetup/DownloadDialog/DownloadDialog.component.js
- src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/epics/getEventListData.js
- src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/epics/initEventWorkingList.js
- src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/epics/updateEventWorkingList.js
- src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/helpers/eventFilters/apiEventFilterToClientConfigConverter/convertToClientConfig.js
- src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/helpers/eventFilters/clientConfigToApiEventFilterQueryCriteriaConverter/convertToEventFilterEventQueryCriteria.js
- src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/types/apiTemplate.types.js
- src/core_modules/capture-core/components/WorkingLists/EventWorkingListsCommon/useDefaultColumnConfiguration/useDefaultColumnConfig.js
- src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/Setup/TeiWorkingListsSetup.component.js
- src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/Setup/useDefaultColumnConfig.js
- src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getTeiListData/convertToClientTeis.js
- src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getTeiListData/getTeiListData.js
- src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getTeiListData/types/getiTeiListDataConcept.types.js
- src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/initTeiWorkingListsView.js
- src/core_modules/capture-core/events/eventRequests.js
- src/core_modules/capture-core/events/mainConverters/mainEventClientToServerConverter.js
- src/core_modules/capture-core/events/mainPropertyNames.const.js
- src/core_modules/capture-core/metaData/Event/Event.js
- src/core_modules/capture-core/metaDataMemoryStoreBuilders/programs/factory/programStage/ProgramStageFactory.js
This is a PR on the replacement of the GET tracker endpoint in the WorkingList-component.
Event-WorkingList is working fine in this PR, but waiting on Api-change before implementing the TEI.
NB: Tests are failing, but this will be fixed in the upcoming PR's. Splitting it up in separate PR's to make it simpler to review. Please also note that this is not merging into master, but to a separate branch. 
All tests regarding the WorkingLists is green.
> feat: [TECH-898] Replaced new endpoint in WorkingLists

- cypress/integration/EventWorkingLists/EventWorkingListsUser.feature
- cypress/integration/EventWorkingLists/EventWorkingListsUser/index.js
- cypress/support/login.js
- i18n/en.pot
- src/core_modules/capture-core/components/Pages/MainPage/WorkingLists/EventListConfigMenuContent.component.js
- src/core_modules/capture-core/components/Pages/MainPage/WorkingLists/TemplateMaintenance/SharingDialog.component.js
- src/core_modules/capture-core/components/Pages/MainPage/WorkingLists/TemplateMaintenance/TemplateMaintenance.component.js
- src/core_modules/capture-core/components/Pages/MainPage/WorkingLists/TemplateSelectorChip.component.js
- src/core_modules/capture-core/components/Pages/MainPage/WorkingLists/WorkingLists.container.js
- src/core_modules/capture-core/components/Pages/MainPage/WorkingLists/epics/eventFiltersInterface/eventFilterRequests.js
- src/core_modules/capture-core/components/Pages/MainPage/WorkingLists/epics/templates.epics.js
- src/core_modules/capture-core/components/Pages/MainPage/WorkingLists/workingLists.actions.js
- src/core_modules/capture-core/components/Pages/MainPage/WorkingLists/workingLists.types.js
- src/core_modules/capture-core/reducers/descriptions/workingLists/workingLists.reducerDescription.js
[DHIS2-10651](https://jira.dhis2.org/browse/DHIS2-10651): Preserve sharing settings Backport to v35
Original [PR](https://github.com/dhis2/capture-app/pull/1514)
Since v35 and v36 have too many differences, I can not simply cherry-pick the commit as it brings a lot of unexpected files.
> fix: [DHIS2-10651] Preserve sharing settings backport to v35

- cypress/integration/NewPage/index.js
(cherry picked from commit b658b10195e2e8dc16a8990ea26fc79ae3450b78)
> fix: cypress test with hardcored 2021 year (#2390)

- src/core_modules/capture-core/components/WidgetProfile/WidgetProfile.component.js
- src/core_modules/capture-core/components/WidgetProfile/getSubValueForTei.js
- src/core_modules/capture-core/components/WidgetProfile/hooks.js
- src/core_modules/capture-core/metaDataStoreLoaders/programs/quickStoreOperations/types/apiPrograms.types.js
* chore: [DHIS2-12142] fix profile tei
* [DHIS2-12142] minor change
* chore: [DHIS2-12142] update list attributes fetching
* chore: [DHIS2-12142] view value and client value
* chore: [DHIS2-12142] format subvalue result
* chore: [DHIS2-12142] useListAttributes
* fix: [DHIS2-12142] fix flow
* fix: [DHIS2-12142] fix flow
* fix: [DHIS2-12142] minor fix
> chore: [DHIS2-12142] fix profile tei (#2308) back port to v37

- src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.component.js
* fix: [DHIS2-12139] add programId to navigation
* chore: [DHIS2-12139] move programId to url
> fix: [DHIS2-12139] add programId to navigation (#2332) backport to v37

- i18n/en.pot
- src/core_modules/capture-core/components/D2Form/field/configs/base/configBaseDefaultForm.js
- src/core_modules/capture-core/components/FormFields/New/HOC/withDescription.js
- src/core_modules/capture-core/components/FormFields/New/HOC/withLabel.js
- src/core_modules/capture-core/metaData/DataElement/DataElement.js
- src/core_modules/capture-core/metaDataMemoryStoreBuilders/programs/factory/programStage/DataElementFactory.js
- src/core_modules/capture-core/metaDataStoreLoaders/programs/quickStoreOperations/storePrograms.js
- src/core_modules/capture-core/storageControllers/cache.types.js
… (#2326)
* feat: [DHIS2-5345] implement data element description and url popover
* chore: [DHIS2-5345] update base props
* fix: [DHIS2-5345] minor fix
> feat: [DHIS2-5345] implement data element description and url popover backport to v37

- src/core_modules/capture-core/components/DataEntry/dataEntryField/withDefaultShouldUpdateInterface.js
- src/core_modules/capture-core/components/DataEntry/withSaveHandler/withSaveHandler.js
- src/core_modules/capture-core/components/FormFields/New/HOC/withDefaultShouldUpdateInterface.js
- src/core_modules/capture-core/components/WidgetEnrollmentEventNew/AccessVerification/AccessVerification.component.js
- src/core_modules/capture-core/components/WidgetEnrollmentEventNew/DataEntry/DataEntry.component.js
- src/core_modules/capture-ui/internal/SelectionBoxes/SingleSelectionBoxes/SingleSelectBox/SingleSelectBox.component.js
* fix: [DHIS2-11837] validate compulsory fields
* fix: [DHIS2-11837] unnecessary onSave
* fix: [DHIS2-11837] fix is completing
* chore: [DHIS2-11837] use saveTypes
> fix: [DHIS2-11837] Saving message for compulsory fields (#2368) backporting to v37

- src/core_modules/capture-core/components/D2Form/field/Components/OrgUnitField/orgUnitFieldForForms.epics.js
- src/core_modules/capture-core/components/FormFields/New/Fields/OrgUnitField/SingleOrgUnitSelectField.component.js
- src/core_modules/capture-core/components/FormFields/New/Fields/OrgUnitField/withInternalFilterHandler/withInternalFilterHandler.js
- src/core_modules/capture-core/components/FormFields/OrgUnitTree/OrgUnitTree.component.js
- src/core_modules/capture-core/components/LockedSelector/LockedSelector.epics.js
- src/core_modules/capture-core/components/LockedSelector/QuickSelector/epics/orgUnitList.epics.js
- src/core_modules/capture-core/components/TeiSearch/SearchOrgUnitSelector/searchOrgUnitSelector.epics.js
- src/core_modules/capture-core/init/getOrgUnitRootsActions.js
Backport to `v35`
Add the missing org unit code
> fix: [DHIS2-12172] missing org unit code

- src/core_modules/capture-core/components/WidgetEventSchedule/hooks/useScheduleConfigFromProgram.js
> fix: [DHIS2-11862] get program config

- src/core_modules/capture-core/components/D2Form/field/configs/base/configBaseDefaultForm.js
- src/core_modules/capture-core/components/FormFields/New/HOC/withDescription.js
- src/core_modules/capture-core/components/FormFields/New/HOC/withLabel.js
- src/core_modules/capture-core/metaData/DataElement/DataElement.js
- src/core_modules/capture-core/metaDataMemoryStoreBuilders/programs/factory/programStage/DataElementFactory.js
- src/core_modules/capture-core/metaDataStoreLoaders/programs/quickStoreOperations/storePrograms.js
- src/core_modules/capture-core/storageControllers/cache.types.js
… (#2326)
* feat: [DHIS2-5345] implement data element description and url popover
* chore: [DHIS2-5345] update base props
* fix: [DHIS2-5345] minor fix
> feat: [DHIS2-5345] implement data element description and url popover backport to v36

- cypress/integration/EnrollmentEditEventPage/EnrollmentEditEventPageForm.feature
- cypress/integration/EnrollmentPage/EnrollmentPageNavigation/index.js
- cypress/integration/EnrollmentPage/StagesAndEventsWidget/index.js
- cypress/integration/LockedSelector/index.js
- cypress/integration/WidgetsForEnrollmentPages/WidgetEnrollment/index.js
- cypress/integration/WidgetsForEnrollmentPages/WidgetsForEnrollmentAddEventPage.feature
- cypress/integration/WidgetsForEnrollmentPages/WidgetsForEventSchedule/index.js
- src/core_modules/capture-core/components/LockedSelector/QuickSelector/QuickSelector.container.js
- src/core_modules/capture-core/components/ScopeSelector/ScopeSelector.utils.js
Change enrollment-label from created to enrollmentDate
> fix: [DHIS2-12324] Change label to enrollmentDate in ScopeSelector

- src/core_modules/capture-core-utils/rulesEngine/RulesEngine.js
- src/core_modules/capture-core-utils/rulesEngine/rulesEngine.types.js
[DHIS2-12473](https://jira.dhis2.org/browse/DHIS2-12473)
Fixed a problem that caused the calculated program rule variables to not populate.
> fix: [DHIS2-12473] calculated program rule variables

- cypress/integration/WorkingLists/EventWorkingLists/EventWorkingListsUser.feature
- cypress/integration/WorkingLists/EventWorkingLists/EventWorkingListsUser/index.js
> fix: [TECH-927] Tests for Category Options

- i18n/en.pot
- src/core_modules/capture-core/components/Pages/MainPage/EventWorkingListsInit/EventWorkingListsInit.container.type.js
- src/core_modules/capture-core/components/Pages/MainPage/WorkingListsType/WorkingListsType.component.js
- src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/ColumnSetup/EventWorkingListsColumnSetup.component.js
- src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/ColumnSetup/eventWorkingListsColumnSetup.types.js
- src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/EventWorkingLists.component.js
- src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/EventWorkingLists.types.js
- src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/ReduxProvider/EventWorkingListsReduxProvider.container.js
- src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/ReduxProvider/eventWorkingListsReduxProvider.types.js
- src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/ViewMenuSetup/DownloadDialog/DownloadDialog.component.js
- src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/ViewMenuSetup/DownloadDialog/downloadDialog.types.js
- src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/ViewMenuSetup/EventWorkingListsViewMenuSetup.component.js
- src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/epics/getEventListData.js
- src/core_modules/capture-core/metaDataMemoryStores/programCollection/helpers/index.js
- src/core_modules/capture-core/metaDataMemoryStores/programCollection/helpers/useProgramStageInfo.js
[DHIS2-12480](https://jira.dhis2.org/browse/DHIS2-12480)
> fix: [DHIS2-12480] working lists download

- src/core_modules/capture-core/components/WidgetEnrollment/constants/status.const.js
[DHIS2-12584](): Change the status `complete` to `completed`
> fix: [DHIS2-12584] fix complete status

- cypress/integration/SearchPage.feature
- cypress/integration/SearchPage/index.js
- src/core_modules/capture-core/components/Pages/Search/SearchResults/SearchResults.component.js
[DHIS2-12528](): fix View dashboard navigation from search page
> fix: [DHIS2-12528] fix View dashboard navigation from search page

- src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/open.epics.js
* fix: [DHIS2-11280] add default program value
* fix: [DHIS2-11280] add program id
> fix: [DHIS2-11280] add default program value (#2435) backport to v37

- src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/open.epics.js
* fix: [DHIS2-11280] add default program value
* fix: [DHIS2-11280] add program id
> fix: [DHIS2-11280] add default program value (#2435) backport to v36

- cypress/integration/EnrollmentPage/EnrollmentPageNavigation/index.js
The behavior is expected so I only adapt the tests
> fix: [DHIS2-12119] fix cypress test

- src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.actions.js
- src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.component.js
- src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.container.js
- src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.epics.js
- src/core_modules/capture-ui/FormBuilder/FormBuilder.component.js
(cherry picked from commit 854e7dc9571a351c8970615d326232d86615d4b4)
> [DHIS2-11610] fix: convert the orgUnit attribute to server values

- src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/epics/addRelationshipForNewSingleEvent.epics.js
https://jira.dhis2.org/browse/DHIS2-12726
https://jira.dhis2.org/browse/DHIS2-12727
> fix: [DHIS2-12727] [DHIS2-12726] Error when trying to create new events with relationship

- src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/epics/addRelationshipForNewSingleEvent.epics.js
https://jira.dhis2.org/browse/DHIS2-12726
https://jira.dhis2.org/browse/DHIS2-12727
> fix: [DHIS2-12727] [DHIS2-12726] Error when trying to create new events with relationship 

- src/core_modules/capture-core/metaDataStoreLoaders/optionSets/loadOptionSets.js
Handle null values for options.
> fix: fiter options

- src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/Setup/TeiWorkingListsSetup.component.js
- src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/templates.epics.js
(cherry picked from commit 0e98781e994c671002b834bac98b6729e29286cc)
> fix: [DHIS2-12575] displayColumnOrder name (#2586)

- src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/StageDetail.component.js
[DHIS2-12778]: Fix tooltip in create new button
> fix: [DHIS2-12778] tooltip display

- src/core_modules/capture-core/metaDataMemoryStoreBuilders/programs/factory/programStage/ProgramStageFactory.js
(cherry picked from commit c5168b22c7f8831fb06a4dcb8d718731f1175256)
> fix: [DHIS2-12667] report date label (#2599)

- cypress/integration/WidgetsForEnrollmentPages/WidgetsForEnrollmentAddEventPage.feature
- src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/NewEventWorkspace/NewEventWorkspace.component.js
* chore: [DHIS2-12783] hide refer tab
* chore: [DHIS2-12783] cypress test
* chore: [DHIS2-12783] cypress test
> fix: [DHIS2-12783] hide refer tab (#2590) backport to v38

- src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/StageDetail.component.js
* chore:[DHIS2-12778] fix tooltip
* chore: [DHIS2-12778] trigger build
> fix: [DHIS2-12778] tooltip display (#2600) backport to v38

- i18n/en.pot
- src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/EnrollmentPageDefault.component.js
- src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/EnrollmentPageDefault.container.js
- src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/EnrollmentPageDefault.types.js
- src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/EnrollmentAddEventPageDefault/EnrollmentAddEventPageDefault.component.js
- src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/EnrollmentAddEventPageDefault/EnrollmentAddEventPageDefault.container.js
- src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/EnrollmentAddEventPageDefault/EnrollmentAddEventPageDefault.types.js
- src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.component.js
- src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.container.js
- src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.types.js
- src/core_modules/capture-core/components/WidgetEnrollment/Actions/Actions.component.js
- src/core_modules/capture-core/components/WidgetEnrollment/Actions/Actions.container.js
- src/core_modules/capture-core/components/WidgetEnrollment/Actions/AddNew/AddNew.component.js
- src/core_modules/capture-core/components/WidgetEnrollment/Actions/AddNew/addNew.types.js
- src/core_modules/capture-core/components/WidgetEnrollment/Actions/AddNew/index.js
- src/core_modules/capture-core/components/WidgetEnrollment/Actions/actions.types.js
- src/core_modules/capture-core/components/WidgetEnrollment/WidgetEnrollment.component.js
- src/core_modules/capture-core/components/WidgetEnrollment/WidgetEnrollment.container.js
- src/core_modules/capture-core/components/WidgetEnrollment/enrollment.types.js
- src/core_modules/capture-core/components/WidgetEnrollment/hooks/useProgram.js
- src/core_modules/capture-core/components/WidgetEnrollment/hooks/useTrackedEntityInstances.js
* feat: [DHIS2-12514] add new when enrollment completed
* feat: [DHIS2-12514] add new when enrollment completed
* feat: [DHIS2-12514] add new when enrollment completed
* feat: [DHIS2-12514] add new when enrollment completed
* chore: [DHIS2-12514] add teiId in url
* chore: [DHIS2-12514] move add new to page level
* chore: [DHIS2-12514] move add new to page level
* chore: [DHIS2-12514] move add new to page level
* fix: [DHIS2-12514] minor fix
* chore: [DHIS2-12514] check if all enrollments have status active
* chore: [DHIS2-12514] check if there is no active enrollment in tei
* chore: [DHIS2-12514] get tetName from widget
> feat: [DHIS2-12514] Add new option in enrollment widget (#2531) backport to v38

- src/core_modules/capture-core/components/WidgetEventEdit/EditEventDataEntry/editEventDataEntry.epics.js
https://jira.dhis2.org/browse/DHIS2-12837
> fix: [DHIS2-12837] Edit single event epic fix

- src/core_modules/capture-core/components/WidgetEventEdit/EditEventDataEntry/editEventDataEntry.epics.js
https://jira.dhis2.org/browse/DHIS2-12740
> fix: [DHIS2-12740] Send null for erased values

- src/core_modules/capture-core/components/WidgetProfile/hooks/getSubValueForTei.js
(cherry picked from commit 329ccc0178c60b800da33c25e7f1014e13f11ea1)
> fix: [DHIS2-12873] missing propriety for files/images dataElements

- src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/helpers/eventFilters/apiEventFilterToClientConfigConverter/convertToClientConfig.js
- src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/helpers/TEIFilters/apiTEIFilterToClientConfigConverter/convertSortToClient.js
(cherry picked from commit e3413ea49aa83f2dd22ad095af9fe5234b11c7b7)
> fix: [DHIS2-12883] use first from multiple order arguments

- src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/Setup/TeiWorkingListsSetup.component.js
- src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/Setup/useDefaultColumnConfig.js
- src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/getTemplates.js
- src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getTeiListData/convertToClientTeis.js
- src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getTeiListData/getTeiListData.js
- src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/initTeiWorkingListsView.js
- src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/helpers/TEIFilters/apiTEIFilterToClientConfigConverter/convertSortToClient.js
- src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/helpers/TEIFilters/getCustomColumnsConfiguration.js
- src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/types/concept.types.js
- src/core_modules/capture-core/components/WorkingLists/WorkingListsCommon/helpers/buildFilterQueryArgs/filterConverters/dateConverter.js
The fix was approved by the RCB. 
(cherry picked from commit b7066bc080a9ea2190fa52f748219206a072bd77)
> fix: [DHIS2-12870] use api fields name for TEIFilters

- src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/epics/getEventListData.js
- src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/Setup/TeiWorkingListsSetup.component.js
- src/core_modules/capture-core/components/WorkingLists/WorkingListsCommon/helpers/buildFilterQueryArgs/filterConverters/dateConverter.js
It was approved by the RCB
(cherry picked from commit 67809ab56610ce52f0aee09c33e7555782e73bb8)
> fix: [DHIS2-11796] adapt the date shape to the API requirements

- src/core_modules/capture-core/relationships/relationshipRequests.js
[DHIS2-13008](https://jira.dhis2.org/browse/DHIS2-13008): Fix relationship request missing fields param
> fix: [DHIS2-13008] fix relationship missing data

- src/core_modules/capture-core/components/WidgetEnrollment/Actions/Actions.container.js
- src/core_modules/capture-core/components/WidgetEnrollment/Actions/actions.types.js
- src/core_modules/capture-core/components/WidgetEnrollment/WidgetEnrollment.component.js
- src/core_modules/capture-core/components/WidgetEnrollment/WidgetEnrollment.container.js
- src/core_modules/capture-core/components/WidgetEnrollment/enrollment.types.js
- src/core_modules/capture-core/components/WidgetEnrollment/hooks/useTrackedEntityInstances.js
[DHIS2-12880](https://jira.dhis2.org/browse/DHIS2-12880): refetch TEI after updating widget enrollment
> fix: [DHIS2-12880] refetch tei after updating

- .github/workflows/verify-app.yml
- .github/workflows/verify-pr-title.yml
- commitlint.config.js
Replaces our old Semantic Pull Request checks.
> chore: update semantic checks

- package.json
There was a missing part in the previous PR regarding pr previews (for v36). Tested and working now.
> chore: pr preview fix

- .github/workflows/dhis2-preview-pr.yml
- .gitignore
- package.json
Makes pr previews available on the v35 branch.
> chore: add pr preview

- cypress/integration/SmokeTests/LoginWithUserEnglish.feature
- cypress/integration/SmokeTests/LoginWithUserEnglish/index.js
[DHIS2-13289](https://jira.dhis2.org/browse/DHIS2-13289)
> fix: [DHIS2-13289] disable non-admin user cypress scenario

- src/core_modules/capture-core/components/D2Form/D2Section.component.js
- src/core_modules/capture-core/components/DataEntry/withSaveHandler/withSaveHandler.js
- src/core_modules/capture-core/reducers/descriptions/form.reducerDescription.js
Sort of a continuation on https://github.com/dhis2/capture-app/pull/1791
> fix: [DHIS2-12707] hidden sections must be marked as initialised

- jest.config.js
- fixed an issue where jest was using stale code for internal core modules
> chore: jest config update

- src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.container.js
- src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/hooks/useEvent.js
Add fallback to maintain compatibility with 2.38 API
> fix: [DHIS2-13551] fallback missing trackedEntity field in the events api

- src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/ReduxProvider/EventWorkingListsReduxProvider.container.js
- src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/ReduxProvider/downloadRequest.js
- src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/epics/eventList.epics.js
- src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/epics/getEventListData.js
- src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/epics/updateEventWorkingList.js
- src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/types/concept.types.js
- src/core_modules/capture-core/components/WorkingLists/WorkingListsBase/ListViewLoader/ListViewLoader.component.js
- src/core_modules/capture-core/components/WorkingLists/WorkingListsBase/ListViewLoader/listViewLoader.types.js
- src/core_modules/capture-core/components/WorkingLists/WorkingListsBase/ListViewUpdater/ListViewUpdater.component.js
- src/core_modules/capture-core/components/WorkingLists/WorkingListsBase/ListViewUpdater/listViewUpdater.types.js
- src/core_modules/capture-core/components/WorkingLists/WorkingListsCommon/hooks/useWorkingListsCommonStateManagement.js
- src/core_modules/capture-core/components/WorkingLists/WorkingListsCommon/index.js
- src/core_modules/capture-core/components/WorkingLists/WorkingListsCommon/types/workingListCommon.types.js
- src/core_modules/capture-core/reducers/descriptions/workingLists/workingLists.reducerDescription.js
Backport of https://github.com/dhis2/capture-app/pull/2850 to 2.37
> fix: [DHIS2-13305] compute and inject the download link

- i18n/en.pot
- src/core_modules/capture-core-utils/validators/form/percentage.validator.js
- src/core_modules/capture-core/components/D2Form/field/validators/getValidators.js
- src/core_modules/capture-core/converters/clientToForm.js
- src/core_modules/capture-core/converters/clientToList.js
- src/core_modules/capture-core/converters/clientToServer.js
- src/core_modules/capture-core/converters/clientToView.js
- src/core_modules/capture-core/converters/formToClient.js
- src/core_modules/capture-core/converters/serverToClient.js
- src/core_modules/capture-core/rules/engine/converters/inputValueConverter.js
- Only allow integer values between 0 and 100
> fix: [DHIS2-13476] percentage value type

- src/core_modules/capture-core/metaDataMemoryStoreBuilders/programs/factory/enrollment/EnrollmentFactory.js
Backport of https://github.com/dhis2/capture-app/pull/2987
Slighty smaller than the original PR because this Capture version doesn't support editing TEIs through the profile widget.
> fix: [DHIS2-8210] display order of tracked entity attributes

- cypress/integration/EnrollmentEditEventPage/EnrollmentEditEventPageForm.feature
- cypress/integration/EnrollmentEditEventPage/EnrollmentEditEventPageNavigation.feature
- cypress/integration/EnrollmentEditEventPage/EnrollmentEditEventPageNavigation/index.js
- cypress/integration/EnrollmentPage/StagesAndEventsWidget/index.js
- cypress/integration/LockedSelector/index.js
- cypress/integration/WidgetsForEnrollmentPages/WidgetEnrollment/index.js
- cypress/integration/WorkingLists/EventWorkingLists/EventWorkingListsUser/index.js
- cypress/support/date.js
Backport of https://github.com/dhis2/capture-app/pull/3162
> fix: [TECH-1495] cypress tests with dynamic dates

- src/core_modules/capture-core/components/WidgetEventEdit/ViewEventDataEntry/viewEventDataEntry.epics.js
Problem: https://dhis2.atlassian.net/browse/DHIS2-14740
Solution: If `enrollment` is undefined and selected program is a Tracker program, wait until the action which initializes the enrollment has been dispatched. I'm not confident I've covered every relevant case in this patch, nor am I confident in the implementation!
> fix: [DHIS2-14740] enrollment data missing in rules engine during page reload

- .github/workflows/e2e-tests.yml
- .github/workflows/verify-app.yml
- cypress/integration/WorkingLists/EventWorkingLists/EventWorkingListsUser.feature
- cypress/integration/WorkingLists/TeiWorkingLists/TeiWorkingListsDev.feature
- cypress/integration/WorkingLists/TeiWorkingLists/TeiWorkingListsUser.feature
> chore: readd tests fixed on the backend

- .github/workflows/cypress-tests.yml
Backport of https://github.com/dhis2/capture-app/pull/3369
> ci: skip cypress for translations

- src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getEventListData/getEventListData.js
[DHIS2-15365](https://dhis2.atlassian.net/browse/DHIS2-15365)
> fix: [DHIS2-15365] remove orgUnit and ouMode query args

- cypress/integration/EnrollmentPage/BreakingTheGlass/index.js
[TECH-1623](https://dhis2.atlassian.net/browse/TECH-1623)
> fix: [TECH-1623] rename TEI "Launchpad McQuack" -> "Breaking TheGlass"

- src/core_modules/capture-core/components/PossibleDuplicatesDialog/possibleDuplicatesDialog.epics.js
- src/core_modules/capture-core/components/SearchBox/SearchForm/SearchForm.epics.js
- src/core_modules/capture-core/components/SearchBox/SearchForm/SearchFormElementConverter/SearchFormElementConverter.js
- src/core_modules/capture-core/components/TeiSearch/serverToFilters.js
[DHIS2-15229](https://dhis2.atlassian.net/browse/DHIS2-15229)
Use `like` when searching for a `MULTI_TEXT` element in the [search page](https://github.com/dhis2/capture-app/pull/3395/files#diff-8fab50c67010fed00a3aa5556fe944ac8a97ea4ba7720638875877b8d0576a48R9), [relationship search](https://github.com/dhis2/capture-app/pull/3395/files#diff-3b401d0fc8a27472575382733c836d9199b7e0f8d3d0d3b18463506b9e70b26aR24), and [possible duplicate search](https://github.com/dhis2/capture-app/pull/3395/files#diff-654f5465d20654888b61e1ec78e9301aa1f013dca14bd0a9c3564aad82f4b306R69)
[DHIS2-15229]: https://dhis2.atlassian.net/browse/DHIS2-15229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: [DHIS2-15229] search for MULTI_TEXT

- src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/hooks/useLifecycle.js
TECH Summary:
- Invalidate dataEntryReadyRef if selectedScopeId changes
> fix: [DHIS2-15693] Rules not triggered on program update

- cypress/e2e/WorkingLists/TeiWorkingLists/TeiWorkingListsUser/index.js
I found the hardcoded template id in another test.
> fix: [TECH-1676] wait for url to update before reloading page

- i18n/en.pot
- src/core_modules/capture-core/components/Pages/ViewEvent/RightColumn/RightColumnWrapper.component.js
Tech-summary:
- Added spacing between event overview cards
> fix: [DHIS2-16352] Add spacing between event overview cards

- i18n/en.pot
- src/core_modules/capture-core/components/WidgetsRelationship/WidgetTrackedEntityRelationship/NewTrackedEntityRelationship/Breadcrumbs/Breadcrumbs.component.js
- src/core_modules/capture-core/components/WidgetsRelationship/WidgetTrackedEntityRelationship/NewTrackedEntityRelationship/Breadcrumbs/breadcrumbs.types.js
- src/core_modules/capture-core/components/WidgetsRelationship/WidgetTrackedEntityRelationship/NewTrackedEntityRelationship/NewTrackedEntityRelationship.component.js
- src/core_modules/capture-core/components/WidgetsRelationship/WidgetTrackedEntityRelationship/NewTrackedEntityRelationship/NewTrackedEntityRelationship.container.js
- src/core_modules/capture-core/components/WidgetsRelationship/WidgetTrackedEntityRelationship/NewTrackedEntityRelationship/NewTrackedEntityRelationship.types.js
- src/core_modules/capture-core/components/WidgetsRelationship/WidgetTrackedEntityRelationship/WidgetTrackedEntityRelationship.component.js
- src/core_modules/capture-core/components/WidgetsRelationship/WidgetTrackedEntityRelationship/hooks/useTrackedEntityTypeName.js
TECH-summary:
- Passed down `trackedEntityTypeName` to the Breadcrumbs-component
- Used this to display dynamic title
> feat: [DHIS2-16745] dynamic naming to relationship widget

- src/core_modules/capture-core/components/FormFields/Image/D2Image.component.js
- src/core_modules/capture-core/components/WidgetProfile/WidgetProfile.component.js
- src/core_modules/capture-core/components/WidgetProfile/hooks/getSubValueForTei.js
- src/core_modules/capture-core/components/WidgetProfile/hooks/useClientAttributesWithSubvalues.js
- src/core_modules/capture-core/converters/clientToView.js
- src/core_modules/capture-ui/PreviewImage/PreviewImage.component.js
Feature summary:
- Show image previews in forms in view mode (event widget and profile widget). Images are left-aligned in this mode.
- Using new source url for the image field preview in edit event/edit profile mode.
> feat: [DHIS2-15392] preview images in forms

- i18n/en.pot
- src/core_modules/capture-core/components/TopBarActions/TopBarActions.component.js
minor fix to change a translations key (to something that already exists)
> fix: change translations key

- src/core_modules/capture-core/components/DataEntries/common/trackerEvent/withAskToCompleteEnrollment/withAskToCompleteEnrollment.js
[DHIS2-17037](https://dhis2.atlassian.net/browse/DHIS2-17037)
[DHIS2-17037]: https://dhis2.atlassian.net/browse/DHIS2-17037?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: [DHIS2-17037] edit event page crashes for event programs

- i18n/en.pot
- src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/EnrollmentPageDefault.container.js
- src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/EnrollmentAddEventPageDefault/EnrollmentAddEventPageDefault.component.js
- src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.component.js
- src/core_modules/capture-core/components/Pages/common/EnrollmentOverviewDomain/EnrollmentPageLayout/LayoutComponentConfig/LayoutComponentConfig.js
- src/core_modules/capture-core/components/WidgetFeedback/WidgetFeedback.types.js
TECH Summary:
- Change static empty text to be sent in as a prop from page component
> fix: [DHIS2-16767] Refactor widgets empty text to be dynamic

- cypress/e2e/NewPage.feature
- cypress/e2e/NewPage/index.js
- cypress/e2e/WidgetsForEnrollmentPages/WidgetEnrollment/index.js
- cypress/e2e/WidgetsForEnrollmentPages/WidgetProfile/index.js
- cypress/e2e/WidgetsForEnrollmentPages/WidgetsForEnrollmentAddEventPage.feature
- cypress/e2e/WidgetsForEnrollmentPages/WidgetsForEnrollmentDashboard.feature
- cypress/e2e/WidgetsForEnrollmentPages/WidgetsForEnrollmentEditEvent.feature
- src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/EnrollmentRegistrationEntry.types.js
- src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/hooks/useBuildEnrollmentPayload.js
- src/core_modules/capture-core/components/DataEntries/TeiRegistrationEntry/hooks/useBuildTeiPayload.js
- src/core_modules/capture-core/components/DataEntries/common/TEIAndEnrollment/geometry.js
- src/core_modules/capture-core/components/DataEntries/common/TEIAndEnrollment/index.js
- src/core_modules/capture-core/components/WidgetEnrollment/hooks/useEnrollment.js
- src/core_modules/capture-core/components/WidgetProfile/hooks/useTrackedEntityInstances.js
- src/core_modules/capture-core/converters/clientToServer.js
- src/core_modules/capture-core/converters/serverToClient.js
- src/core_modules/capture-core/reducers/descriptions/trackedEntityInstance.reducerDescription.js
[DHIS2-17108](https://dhis2.atlassian.net/browse/DHIS2-17108)
[DHIS2-17108]: https://dhis2.atlassian.net/browse/DHIS2-17108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: [DHIS2-17108][DHIS2-15681] enrollment and TET geometry are not stored and properly displayed

- src/core_modules/capture-core/components/FormFields/Image/D2Image.component.js
- src/core_modules/capture-core/components/Pages/ViewEvent/ViewEventPage.component.js
- src/core_modules/capture-core/components/WidgetEventEdit/EditEventDataEntry/EditEventDataEntry.component.js
- src/core_modules/capture-core/components/WidgetEventEdit/WidgetEventEdit.container.js
[DHIS2-17001](https://dhis2.atlassian.net/browse/DHIS2-17001)
[DHIS2-17001]: https://dhis2.atlassian.net/browse/DHIS2-17001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: [DHIS2-17001] show image previews after editing event

- src/core_modules/capture-core/components/WidgetEventEdit/ViewEventDataEntry/viewEventDataEntry.actions.js
- src/core_modules/capture-core/rules/filterApplicableRuleEffects.js
- src/core_modules/capture-core/rules/index.js
[DHIS2-16999](https://dhis2.atlassian.net/browse/DHIS2-16999)
[DHIS2-16999]: https://dhis2.atlassian.net/browse/DHIS2-16999?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: [DHIS2-16999] filter assign rule effects in the view event page

- packages/rules-engine/src/d2Functions/getD2Functions.js
- packages/rules-engine/src/d2Functions/getD2Functions.types.js
- packages/rules-engine/src/services/expressionService/executeExpression.js
- src/core_modules/capture-core/rules/__tests__/ruleEffectsForEventProgram.test.js
[DHIS2-17195](https://dhis2.atlassian.net/browse/DHIS2-17195)
[DHIS2-17195]: https://dhis2.atlassian.net/browse/DHIS2-17195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: [DHIS2-17195] implement d2:condition

- src/core_modules/capture-core-utils/featuresSupport/support.js
- src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/hooks/useBuildEnrollmentPayload.js
- src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/epics/getConvertedNewSingleEvent.js
- src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/epics/saveNewSingleEvent.epics.js
- src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/epics/saveNewSingleEventAddAnother.epics.js
- src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/epics/saveNewSingleEventStage.epics.js
- src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/EnrollmentAddEventPageDefault/EnrollmentAddEventPageDefault.container.js
- src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/helpers/deriveAutoGenerateEvents.js
- src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/helpers/deriveFirstStageDuringRegistrationEvent.js
- src/core_modules/capture-core/components/Pages/ViewEvent/ViewEventComponent/ViewEvent.container.js
- src/core_modules/capture-core/components/Pages/ViewEvent/ViewEventComponent/viewEvent.selectors.js
- src/core_modules/capture-core/components/Pages/ViewEvent/ViewEventPage.component.js
- src/core_modules/capture-core/components/WidgetEnrollmentEventNew/Validated/getConvertedAddEvent.js
- src/core_modules/capture-core/components/WidgetEnrollmentEventNew/Validated/useBuildNewEventPayload.js
- src/core_modules/capture-core/components/WidgetEventEdit/EditEventDataEntry/editEventDataEntry.epics.js
- src/core_modules/capture-core/components/WidgetEventEdit/ViewEventDataEntry/viewEventDataEntry.actions.js
- src/core_modules/capture-core/components/WidgetEventEdit/ViewEventDataEntry/viewEventDataEntry.epics.js
- src/core_modules/capture-core/components/WidgetEventSchedule/WidgetEventSchedule.epics.js
- src/core_modules/capture-core/converters/clientToServer.js
- src/core_modules/capture-core/events/convertEventAttributeOptions.js
- src/core_modules/capture-core/events/mainConverters/mainEventClientToServerConverter.js
Tech-summary:
- Use server version to send correct AOC payload when there are multiple categories in a category combo assigned to a program.
> fix: [DHIS2-17399] use server version to send correct aoc payload

- .github/workflows/e2e-tests.yml
- .github/workflows/verify-app.yml
- cypress/support/generateTestMatrix.js
Optimise Cypress Test Groups from 10 to 5
> chore: [DHIS2-17372] reduce test groups to 5 for improved CI performance

- cypress/e2e/EnrollmentPage/StagesAndEventsWidget.feature
- src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/EnrollmentPageDefault.container.js
- src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/EnrollmentPageDefault.types.js
- src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/hooks/useProgramMetadata.js
- src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/hooks/useProgramStages.js
- src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stages.component.js
- src/core_modules/capture-core/components/WidgetStagesAndEvents/types/common.types.js
Cypress tests are coming in https://dhis2.atlassian.net/browse/DHIS2-17590
> fix: [DHIS2-17488] hide program stage if no data read access

- src/core_modules/capture-core/components/ListView/Filters/FilterRestMenu/FilterRestMenu.component.js
Implements [DHIS2-16196](https://dhis2.atlassian.net/browse/DHIS2-16196)
[DHIS2-16196]: https://dhis2.atlassian.net/browse/DHIS2-16196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: [DHIS2-16196] set MaxHeight to "more filters" in working lists

- cypress/e2e/NewPage/NewPage.js
[DHIS2-17733](https://dhis2.atlassian.net/browse/DHIS2-17733)
- check that the required Unique ID attribute is filled with a randomly generated value
[DHIS2-17733]: https://dhis2.atlassian.net/browse/DHIS2-17733?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: [DHIS2-17733] flaky scenario in NewPage.feature 

- i18n/en.pot
- src/core_modules/capture-core/components/CardList/CardList.types.js
- src/core_modules/capture-core/components/CardList/CardListItem.component.js
- src/core_modules/capture-core/components/WidgetEnrollment/WidgetEnrollment.component.js
- src/core_modules/capture-core/components/WidgetEnrollment/hooks/useEnrollment.js
- src/core_modules/capture-core/components/WidgetNote/NoteSection/NoteSection.js
- src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageOverview/StageOverview.component.js
Implement [DHIS2-17589](https://dhis2.atlassian.net/browse/DHIS2-17589)
[DHIS2-17589]: https://dhis2.atlassian.net/browse/DHIS2-17589?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: [DHIS2-17589] show absolute date when hovering over relative dates

- src/core_modules/capture-core/components/WidgetEventEdit/ViewEventDataEntry/viewEventDataEntry.actions.js
Implements [DHIS2-16373](https://dhis2.atlassian.net/browse/DHIS2-16373)
[DHIS2-16373]: https://dhis2.atlassian.net/browse/DHIS2-16373?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: [DHIS2-16373] cannot change AOC on existing events in Tracker program

- cypress/e2e/EnrollmentPage/StagesAndEventsWidget/StagesAndEventsWidget.feature
- cypress/e2e/WorkingLists/TeiWorkingLists/TeiWorkingListsUser/TeiWorkingListsUser.feature
- d2.config.js
- src/core_modules/capture-core-utils/featuresSupport/support.js
- src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/Setup/hooks/useProgramStageFilters.js
- Set minDHISVersion to 2.39
- Removed some dead code
- Adding "BREAKING CHANGE" to the commit message footer should increase the version to 101.0.0 when merged.
> chore(release): stop support for 2.38

- src/core_modules/capture-core/components/CardList/CardListItem.component.js
- src/core_modules/capture-core/components/IncompleteSelectionsMessage/index.js
- src/core_modules/capture-core/components/InfoIconText/InfoIconText.js
- src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.component.js
[DHIS2-17840](https://dhis2.atlassian.net/browse/DHIS2-17840)
Removes `Grid` from:
- IncompleteSelectionsMessage
- CardListItem
- InfoIconText
- RegistrationDataEntryComponent
[DHIS2-17840]: https://dhis2.atlassian.net/browse/DHIS2-17840?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor: [DHIS2-17840]replace Material UI Grid

- src/core_modules/capture-core-utils/validators/form/date.validator.js
- src/core_modules/capture-core/components/WidgetEnrollmentEventNew/Validated/getConvertedRelatedStageEvent/getConvertedRelatedStageEvent.js
- src/core_modules/capture-core/utils/converters/date/stringToMomentDateFormat.js
Summary:
- Changed the logic around converting the related stages date to the correct format
> fix: [DHIS2-17953] Invalid dateFormat conversion in related stages

- cypress/e2e/WorkingLists/TeiWorkingLists/TeiWorkingListsUser/TeiWorkingListsUser.feature
- cypress/e2e/WorkingLists/TeiWorkingLists/TeiWorkingListsUser/TeiWorkingListsUser.js
- i18n/en.pot
- src/core_modules/capture-core/components/Pages/MainPage/MainPage.container.js
Summary:
- Working list was not persisted when navigating back from the enrollment dashboard
- Check if there is a stored selected working list in redux before adding the default template
> fix: [DHIS2-18215] selected working list not persisted on navigate

- src/core_modules/capture-core/components/WidgetProfile/DataEntry/dataEntry.actions.js
Implements [DHIS2-18673](https://dhis2.atlassian.net/browse/DHIS2-18673)
[DHIS2-18673]: https://dhis2.atlassian.net/browse/DHIS2-18673?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: [DHIS2-18673] prevent saving in profile widget when validation errors are present

- .github/workflows/preview.yml
- .github/workflows/verify-app.yml
Fixes broken push-triggered github-actions.
> fix: update github actions cache v2 -> v4

- package.json
- yarn.lock
[DHIS2-19196](https://dhis2.atlassian.net/browse/DHIS2-19196) bump @dhis2-ui/calendar from 10.0.3 to 10.4.0 to include the changes done in [LIBS-726](https://dhis2.atlassian.net/browse/LIBS-726)
[LIBS-726]: https://dhis2.atlassian.net/browse/LIBS-726?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DHIS2-19196]: https://dhis2.atlassian.net/browse/DHIS2-19196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: [DHIS2-19196][LIBS-726] bump @dhis2-ui/calendar from 10.0.3 to 10.4.0

- cypress/e2e/WidgetsForEnrollmentPages/WidgetEnrollment/index.js
- cypress/e2e/WorkingLists/TeiWorkingLists/TeiWorkingListsDev/TeiWorkingListsDev.js
- src/core_modules/capture-core-utils/featuresSupport/support.js
- src/core_modules/capture-core/components/WidgetEnrollment/Actions/Transfer/hooks/useUpdateOwnership.js
- src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/Setup/hooks/useFiltersOnly.js
https://dhis2.atlassian.net/browse/DHIS2-19530
> fix: [DHIS2-19530] deprecated api query params

- package.json
- src/core_modules/capture-core/rules/__tests__/ruleEffectsForEventProgram.test.js
- yarn.lock
Corrects the order of execution for program rules (makes program rules without priority run last).
> chore: bump rule engine version 3.3.9 -> 3.3.10

- src/core_modules/capture-core/components/Pages/common/TEIRelationshipsWidget/TeiSearch/TeiSearchForm/TeiSearchForm.component.js
- src/core_modules/capture-core/components/TeiSearch/TeiSearchForm/TeiSearchForm.component.js
[DHIS2-11104](https://dhis2.atlassian.net/browse/DHIS2-11104)
[DHIS2-11104]: https://dhis2.atlassian.net/browse/DHIS2-11104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: [DHIS2-11104] Translation for Unique Search

- i18n/en.pot
- i18n/es.po
- src/core_modules/capture-core/components/ScopeSelector/QuickSelector/OrgUnitSelector.component.js
[DHIS2-19767](https://dhis2.atlassian.net/browse/DHIS2-19767)
[DHIS2-19767]: https://dhis2.atlassian.net/browse/DHIS2-19767?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: [DHIS2-19767] Translate Choose Org Unit label

- src/core_modules/capture-core/components/CardList/CardListItem.component.js
- src/core_modules/capture-core/components/CardList/ListEntry.component.js
- src/core_modules/capture-core/components/PossibleDuplicatesDialog/ReviewDialogContents/ReviewDialogContents.container.js
- src/core_modules/capture-core/components/SearchBox/SearchForm/SearchForm.types.js
- src/core_modules/capture-core/components/SearchBox/SearchResults/SearchResults.container.js
- src/core_modules/capture-core/components/SearchBox/SearchResults/SearchResults.types.js
- src/core_modules/capture-core/metaData/helpers/DataElements/convertValues.js
[DHIS2-19632](https://dhis2.atlassian.net/browse/DHIS2-19632)
_Wrong ticket number in branch name (DHIS2-16907 &rarr; DHIS2-19632)._
[DHIS2-19632]: https://dhis2.atlassian.net/browse/DHIS2-19632?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: [DHIS2-19632] Search result cards display option codes instead of names/texts

- src/core_modules/capture-core/components/DataEntryWidgetOutput/DataEntryWidgetOutput.component.tsx
- src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.component.tsx
- src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/registrationDataEntry.css
The registration/enrolling page was having a major problem as well that I fixed.
> feat: [DHIS2-20077] Responsive layout part 2
