src/init/entry.js

When hydrating the persisted state, e.g. in the situation where:
1. User inputs events offline
2. User closes tab with capture app
3. User re-opens capture app
We have the state persisted, and as soon as the Store is initialised
redux-offline will try to run the events in the outbox to sync them. At
this point D2 *has* to be available or the App will crash.
The `initialize` function does not depend on any state so it can be run
before the `getStore` functions. We still get the loader while d2 loads.

Allow D2 to initialize before setting up the Redux Store

---

src/getStore.js
src/init/entry.js

The problem: persist/REHYDRATE executes after other app-actions, resulting in some unwanted behavior. 
This PR utilizes the persistCallback option on the offline config to make sure rehydrate executes before the app runs (initialize d2 => rehydrate => run app)

render app after rehydrated

---

.gitignore
src/core_modules/capture-ui/CoordinateField/CoordinateField.component.js

closes: https://jira.dhis2.org/browse/DHIS2-7348
@JoakimSM 👋 
As the ticket describes and you very well know already I have changed the order that long and lat is being displayed in the new event page. This way the metadata regarding long and lat on the new event page are in the same order as in the table where it's been displayed. 
Have a look when you got the time
A visual representation:
PS. Webstorm generates some files that dont need to be added in the code base therefore its been ignored.

fix: DHIS2-7348 switches the order of long and lat when adding a new Event

---

package.json

@JoakimSM as we talked this morning in this PR I am changing the pre-commit command that comes with husky to commit only i18n related files. 
Let me know what you think!

fix: husky pre-commit the translations files

---

.dependabot/config.yml

Hey @JoakimSM  👋 Please have a look at those rules when you find the time 😃.
Are copied from the [`data-visualiser-app`](https://github.com/dhis2/data-visualizer-app/blob/master/.dependabot/config.yml) and  are the default ones that the [`app-platform`](https://github.com/dhis2/data-visualizer-app/blob/master/.dependabot/config.yml) would generate when you execute [`init`](https://platform.dhis2.nu/#/scripts/init) script.
closes: https://jira.dhis2.org/browse/TECH-349
Please let me know your thoughts!

chore: adds configuration for dependabot from application-platform

---

src/core_modules/capture-core-utils/date/date.utils.js
src/core_modules/capture-core-utils/date/index.js
src/core_modules/capture-core/components/Pages/EditEvent/DataEntry/epics/saveEditSingleEvent.epics.js
src/core_modules/capture-core/components/Pages/MainPage/WorkingLists/epics/eventsQueryArgsBuilder/filterConverters/dateConverter.js
src/core_modules/capture-core/components/Pages/NewEvent/DataEntry/epics/getConvertedNewSingleEvent.js
src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/exposedHelpers/getRelationshipNewTei.js
src/core_modules/capture-core/components/Pages/ViewEvent/EventDetailsSection/EditEventDataEntry/editEventDataEntry.epics.js
src/core_modules/capture-core/rulesEngineActionsCreator/converters/momentConverter.js

Resolved some issues caused by using a moment locale with non european glyphs.
- Saving an event when the event was marked for completion caused the post request to fail due to the complete date being posted using non european glyphs.
- Filtering a view using a date field caused the filtering to fail.
- Program rules would interpret dates wrong.

fix: DHIS2-8612 moment locale using non european glyphs fix

---

src/core_modules/capture-ui/CoordinateField/CoordinateField.component.js

Hey @JoakimSM  👋 👋 
As we talked and after your suggestions which were very helpful I am opening this PR which addresses the https://jira.dhis2.org/browse/DHIS2-7300. 
We are dealing with two cases here as you already know. 
* The first case where the user opens the map and drops a pin on the map. When the user closes the map then the `lat` and `long` will be put in the input form. In this case we sanitise the values on the `onMapPositionChange `
* The second case is when the user adds the value manually in the input. Here we sanitise the value on the blur event of the input. This way the user can type as much decimals as they like and when they "leave" the input then the value gets sanitised to 6 decimals. 
Let me know your thoughts or suggestions!!

fix: sanitises the long and lat value to be a six decimal

---

src/core_modules/capture-core-utils/RulesEngine/RulesEngine.js
src/core_modules/capture-core-utils/RulesEngine/RulesEngine.test.js
src/core_modules/capture-core-utils/RulesEngine/VariableService/VariableService.js
src/core_modules/capture-core-utils/RulesEngine/converters/inputValueConverter.js
src/core_modules/capture-core-utils/RulesEngine/converters/momentConverter.js
src/core_modules/capture-core-utils/RulesEngine/converters/rulesEffectsValueConverter.js
src/core_modules/capture-core-utils/RulesEngine/executionService/executionService.js
src/core_modules/capture-core-utils/RulesEngine/rulesEffectsProcessor/rulesEffectsProcessor.js
src/core_modules/capture-core-utils/RulesEngine/rulesEngine.types.js
src/core_modules/capture-core/rulesEngineActionsCreator/postProcessRulesEffects.js
src/core_modules/capture-core/rulesEngineActionsCreator/rulesEngineActionsCreator.js
src/core_modules/capture-core/rulesEngineActionsCreator/runRulesForSingleEvent.js

hey Joakim good morning! 
Opening this PR which continues what we have started with the RulesEngine. There will be few PRs following probably 3 of the same size which will finalise the refactoring. 
There are few touch points I would like to stress so that reviewing this gets easier.
I am focusing here only in simplifying the signature of the RulesEngine class. That means I mostly move around functions that dont have to exist as parameters on the RulesEngine class. One of those is for instance `dateUtils`. Instead of passing this as an argument to the functions I now import it to the files that is used. After these changes we can call `RulesEngine` class without giving it any parameters which is simplifies the code for the developer who wants to use it.
Another change is that now …

refactor: on RulesEngine class 03

---

.env.development
package.json

Hey Joakim! This adds back the `env.developement`. Also would change the auto commit on the branch `v33`. This was original the reason why I went into the loop of thinking that I reversed the auto-committed changes that the `.env` file had and instead I deleted it. 😅 
Thanks for caching this, I would never have seen it.

fix: re-adds env dev file

---

package.json
yarn.lock

Hey @paschalidi 
I'm readding the `eslint-import-resolver-webpack` dependency. Without it the import statements using aliases for `capture-core-utils`, `capture-core` and so on throws an eslint error.

chore: readding eslint-import-resolver-webpack

---

src/core_modules/capture-core-utils/storage/StorageController.js
src/core_modules/capture-core/components/FiltersForTypes/Boolean/BooleanFilter.component.js
src/core_modules/capture-core/components/FiltersForTypes/Numeric/NumericFilter.component.js
src/core_modules/capture-core/components/FormFields/OrgUnitTree/OrgUnitTree.component.js
src/core_modules/capture-core/components/FormFields/UserField/Search.component.js
src/core_modules/capture-core/components/Pages/EditEvent/EditEvent.component.js
src/core_modules/capture-core/components/Pages/MainPage/EventsList/AddWorkingListConfigDialog/AddWorkingListConfigDialog.container.js
src/core_modules/capture-core/components/Pages/MainPage/WorkingLists/epics/templates.epics.js
src/core_modules/capture-core/components/Pages/NewEnrollment/DataEntry/actions/dataEntry.actionBatchs.js
src/core_modules/capture-core/components/Pages/NewEvent/DataEntryWrapper/NewEventDataEntryWrapper.component.js
src/core_modules/capture-core/components/Pages/NewEvent/SelectionsComplete/SelectionsComplete.component.js
src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/DataEntry/dataEntry.epics.js
src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/TrackedEntityInstance/tei.selectors.js
src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/open.epics.js
src/core_modules/capture-core/components/Pages/ViewEvent/ViewEvent.component.js
src/core_modules/capture-core/components/QuickSelector/Program/CategorySelector.component.js
src/core_modules/capture-core/rules/engine/services/VariableService/VariableService.js
src/core_modules/capture-ui/internal/AgeInput/AgeNumberInput.component.js

hey @JoakimSM as we talked about some time ago. 
I am opening this PR to fix some lgmt errors. In this series of PRs the goal is to have `eslint` checking our PRs so that if any error occurs that is `eslint` related the github checkers will spot it for us. This will include only errors and not warnings.
I am not intending to change any `eslint` rules, I will simply fix the `errors` that are being reported if any. This step is necessary so that we can then add the `eslint` check in our CI/CD pipeline.  `eslint` then will be checking our codebase for any errors and if there are none then it will give us a success or else will throw an error. The motivation is that we will have a more cohesive style on the code and that devs will not spent time looking into linting errors on PRs and will …

chore: fixes error alerts from lgtm tool 01

---

cypress/integration/NewEvent/index.js
src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/RegisterTei.component.js

@JoakimSM there is this test that sometimes failed and sometimes not. 
This is because it can happen that the request clean up sometimes doesnt take place. The user is then added in the database. Next time the test runs we have a duplicate on the person. In this case the tests passes only if the machine is quick enough to press the create user button before the server responds with possible duplicates. 
To solve this I am registering a user we already know exists in the database. And by changing the order the machine is typing. So now the machine first types the name and last name which is used to detect duplicates and then the dates. This way hopefully there will be always time the detection of the duplicates
I hope this will fix the issue.

fix: test that failed unexpectedly during CI/CD

---

cypress/integration/LockedSelector.feature
cypress/integration/LockedSelector/index.js
cypress/integration/SearchPage.feature
i18n/en.pot
src/core_modules/capture-core/components/LockedSelector/LockedSelector.actions.js
src/core_modules/capture-core/components/LockedSelector/LockedSelector.component.js
src/core_modules/capture-core/components/LockedSelector/LockedSelector.container.js
src/core_modules/capture-core/components/LockedSelector/LockedSelector.types.js
src/core_modules/capture-core/components/LockedSelector/QuickSelector/ActionButtons.component.js
src/core_modules/capture-core/components/LockedSelector/QuickSelector/QuickSelector.component.js
src/core_modules/capture-core/components/Pages/Search/SearchPage.epics.js

https://jira.dhis2.org/browse/DHIS2-9675
Adds the dropdown menu on the Find button of the LockedSelector.
The button basically has two states. 
a) when there is _no_ Tracker program selected you can only see a button. 
b) when there is  a Tracker program selected then there is a dropdown button. The dropdown has two options as we discussed in the concept. 
You can find the concept [here](https://dhis2.github.io/design-specs/capture-context/capture-context-test/?01_blank).

feat: DHIS2-9675 Redesign Find button to match the new concept

---

cypress/integration/LockedSelector.feature
cypress/integration/LockedSelector/index.js
cypress/integration/SearchPage.feature
cypress/integration/SearchPage/index.js
i18n/en.pot
src/core_modules/capture-core/components/LockedSelector/LockedSelector.actions.js
src/core_modules/capture-core/components/LockedSelector/LockedSelector.component.js
src/core_modules/capture-core/components/LockedSelector/LockedSelector.container.js
src/core_modules/capture-core/components/LockedSelector/LockedSelector.types.js
src/core_modules/capture-core/components/LockedSelector/QuickSelector/ActionButtons.component.js
src/core_modules/capture-core/components/LockedSelector/QuickSelector/QuickSelector.component.js
src/core_modules/capture-core/components/Pages/Search/SearchDomainSelector/SearchDomainSelector.component.js
src/core_modules/capture-core/components/Pages/Search/SearchDomainSelector/SearchDomainSelector.types.js
src/core_modules/capture-core/components/Pages/Search/SearchPage.component.js
src/core_modules/capture-core/components/Pages/Search/SearchPage.container.js
src/core_modules/capture-core/components/Pages/Search/SearchPage.epics.js
src/core_modules/capture-core/components/Pages/Search/SearchPage.types.js

👋   Joakim hi. This is the: https://jira.dhis2.org/browse/DHIS2-9665
After our talk with Joe we decided on showing the domain selector optionally. 
The behaviour now is the following
* the selector is visible only when the user is in the search page but hasnt selected a Tracker program
* when the user is on the search page and they select an Event type of program they are being navigated back to viewing all the events.

feat: DHIS2-9665 update the use of the Domain Selector in the search page

---

.github/workflows/cypress-tests.yml
.github/workflows/flow-checks.yml
.github/workflows/linter-checks.yml

When the check fails in the form that it is now, I will always have to click and go in the github actions area and then scroll over to see whether the flow or linter failed. 
This is sometimes annoying :) This PR splits those two. Now I will be able to see from the PR view which one fails and save myself some clicks

chore: split the jobs of linting and flow checking

---

package.json
yarn.lock

@JoakimSM merged [this](https://github.com/dhis2/capture-app/commit/a1edbf30560ba9fc37cd6e1c85eed6092b474f0b) jsdoc bot update on master and this broke the lint 
This is reverting the jsdoc change

chore: reverting jsdoc dependency update

---

src/core_modules/capture-core/components/LoadingMasks/LoadingMaskElementCenter.component.js
src/core_modules/capture-core/components/LockedSelector/LockedSelector.container.js

👋 Hey @JoakimSM. This is the ticket:  https://jira.dhis2.org/browse/DHIS2-9827
Well sometimes we have this 
This ticket aligns  the loader in the middle of the page or the component in the case of Locked selector

chore: DHIS2-9827 adds height on loading containers

---

src/core_modules/capture-core/components/Pages/New/NewPage.component.js
src/core_modules/capture-core/components/Pages/New/NewPage.container.js
src/core_modules/capture-core/components/Pages/New/NewPage.types.js
src/core_modules/capture-core/components/Pages/Search/SearchPage.component.js
src/core_modules/capture-core/components/Pages/Search/SearchPage.container.js
src/core_modules/capture-core/components/Pages/Search/SearchPage.types.js
src/core_modules/capture-core/components/TrackedEntityTypeSelector/TrackedEntityTypeSelector.component.js
src/core_modules/capture-core/components/TrackedEntityTypeSelector/TrackedEntityTypeSelector.types.js
src/core_modules/capture-core/hooks/useTrackedEntityTypesWithCorrelatedPrograms.js

Hey Joakim. This is the ticket that adds the TEType Selector on the new page. Ticket can be found here https://jira.dhis2.org/browse/DHIS2-9649 
Two things: 
1. added the Selector but selecting a new item from the dropdown wont change the url. The next PR will take care of that as it is captured in a separate ticket.
2. reused the `useTrackedEntityTypesWithCorrelatedPrograms` instead of prop drilling I was doing before

chore: adds the tetype selector on the new page

---

src/components/AppLoader/init.js
src/core_modules/capture-core/metaDataMemoryStoreBuilders/programs/programsBuilder.js

Check this out Joakim. It fixes the bug I believe.
Also I tried to annotate and followed eslint where it was saying that returning awaiting is redundant.

DHIS2-9785 Capture app crashes when there is no public access for one of the tracked entity type

---

src/core_modules/capture-core/metaDataMemoryStoreBuilders/programs/programsBuilder.js

Looks like when we fixed the https://jira.dhis2.org/browse/DHIS2-9785 I filtered out all the Event programs. 
The weird thing is that tests were passing [here](https://github.com/dhis2/capture-app/runs/1458403471) but failed when this was merged on `master`. Some [bug](https://github.com/cypress-io/github-action/issues/168) on the cypress gh action must be the reason
This is fixing the issue and makes the tests to pass _correctly_ this time :)

fix: allows event programs

---

cypress.json
src/core_modules/capture-core/metaDataMemoryStoreBuilders/programs/programsBuilder.js

This update will allow our tests to retry once when they fail.
We have this test that sometimes fails which we tried to fix but not successfully. We could fix it this way instead

chore: adds retries on cypress

---

src/core_modules/capture-core/rules/actionsCreator/inputHelpers.js
src/core_modules/capture-core/rules/actionsCreator/postProcessRulesEffects.js

This works on this ticket https://jira.dhis2.org/browse/DHIS2-10070. 
Here is how much this would take in the previous version. If you would like me to explain in more detail how to get this view, please let me know and we can get into a call
This is the same action now

fix: DHIS2-10070 improves rules engine performance

---

src/core_modules/capture-core/metaDataStoreLoaders/programs/queries/queryProgramsOutline.js
src/core_modules/capture-core/metaDataStoreLoaders/programs/quickStoreOperations/storePrograms.js

@JoakimSM and @Bekkalizer hey. 
This is taking care of the https://jira.dhis2.org/browse/DHIS2-10111. 
1. In maintenance app for a program, lets say child program and select all units _but_ one.
2. in the users app go and create a user. Add to the user a capture org unit that is _not_ the one you have added to the child program. Also give the user Facility tracker access.
3. save the user.
4. clear the cache.
5. log in with the user you created. 
you can see in the network tab that the orgUnits for that program that have been fetched are empty. 
It would fetch all the org units a program has been assigned to

chore: DHIS2-10111 adds `restrictToCaptureScope=true`

---

.github/workflows/codeql-analysis.yml
i18n/en.pot

Adds gh action for `lgtm`. This is the official suggestion from the gh people. lgtm application needs to be deactivated from the organisation after we validate this works well. 
Also this can only work after it is merged as its being said when you click in the details on the [gh action](https://github.com/dhis2/capture-app/pull/1321/checks?check_run_id=1556579734)

chore: create code commit

---

.flowconfig
src/core_modules/capture-core/trackerOffline/trackerOffline.js
src/core_modules/capture-core/trackerOffline/trackerOffline.types.js

[TECH-522](https://jira.dhis2.org/browse/TECH-522)
After moving to the app runtime data engine, Redux Offline tries to resend requests that the response dictates should only be sent once. For example of you get a 409 error as a response, the request should not be resent. This was due to the response object returned from the data engine being different than the old one.
Note: I used optional chaining in this PR. Optional chaining should be supported since create-react-app (react-scripts) 3.3.0 [v3.3.0](https://github.com/facebook/create-react-app/releases/tag/v3.3.0) We use 3.4.1 at the moment.

fix: TECH-522 redux offline retry handling

---

src/core_modules/capture-core/components/TrackedEntityTypeSelector/TrackedEntityTypeSelector.component.js
src/core_modules/capture-core/components/TrackedEntityTypeSelector/TrackedEntityTypeSelector.container.js

Hey this fixes a bug found by Geetha on the access realted topic.  https://jira.dhis2.org/browse/DHIS2-10142
Long story short:
* When the user has only view access of a TEType then they could see the TEType (Person) on the dropdown of the search page. 
* However when they dont have view access but the have _no access_ the should not be able to see the person under the drop down menu in the search page as in the image 
We hardcode the `accessNeeded` prop to be `read` when the user used the <TrackedEntityTypeSelector />` without specifying what access is needed. Looks logical to me because you will _always_ need to have at least read access to be able to view the TEType in the dropdown menu.
Happy to discuss edge cases if you see any :)

fix: DHIS2-10142 access problem in the search page

---

src/core_modules/capture-core/components/Pages/New/NewPage.container.js

https://jira.dhis2.org/browse/DHIS2-10179 Geetha have found a bug on this ticket. 
Basically the user need _both_ tetype write access _and_ program write access to be able to see that registration form for a tracker program. 
Before this fix, we would allow the user to see the registration form, for say Child Programme, while they _do not have_ write access for the type Person. 
We will then throw an error while they try to submit the form. Which basically doesnt make much sense. 
Now the user sees the same message as in the other cases explaining to them that they cannot create for their current selections

fix: DHIS2-10179  block users without tetype write access

---

cypress/integration/LockedSelector.feature
cypress/integration/LockedSelector/index.js
src/core_modules/capture-core/components/LockedSelector/LockedSelector.epics.js

Hey this fixes the https://jira.dhis2.org/browse/DHIS2-10584 and adds tests to cover it. 
Check it out and please let me know what you thinking :)

fix: program error bug

---

src/core_modules/capture-core/reducers/descriptions/currentSelections.reducerDescriptionGetter.js

There was a bug I found related to the url and is pretty easy to explain. 
Basically when you will have the url like so 
And you press to go back to the previous page by the browser button sometimes the page goes into an infinite loop. This is because the url queries aka `orgUnitId` and `programId` arent in sync with the `currentSelections`.
This PR fixes this bug by updating the store with the newest `currentSelections` and omiting the ones that were there beforehand

fix: url back and forth bug

---

package.json
src/core_modules/capture-core/metaDataMemoryStoreBuilders/programs/factory/program/ProgramFactory.js
src/core_modules/capture-core/metaDataStoreLoaders/context/context.types.js
src/core_modules/capture-core/metaDataStoreLoaders/programs/loadPrograms.js
src/core_modules/capture-core/metaDataStoreLoaders/programs/queries/queryProgramsOutline.js
src/core_modules/capture-core/metaDataStoreLoaders/programs/quickStoreOperations/index.js
src/core_modules/capture-core/metaDataStoreLoaders/programs/quickStoreOperations/storeOrganisationUnitsByProgram.js
src/core_modules/capture-core/metaDataStoreLoaders/programs/quickStoreOperations/storePrograms.js
src/core_modules/capture-core/metaDataStoreLoaders/programs/quickStoreOperations/types/apiOrganisationUnitsByProgram.types.js
src/core_modules/capture-core/metaDataStoreLoaders/programs/quickStoreOperations/types/index.js
src/core_modules/capture-core/storageControllers/stores/userStores.const.js

[TECH-542](https://jira.dhis2.org/browse/TECH-542)
The straight up switch to the new endpoint for downloading organisation units.
Will create a new issue for fixing the memory consumption part. That part will probably be merged into master only.

fix: TECH-542 Switch to new endpoint for org units

---

src/core_modules/capture-core/components/Pages/Search/SearchForm/SearchForm.epics.js

Fixes: https://jira.dhis2.org/browse/DHIS2-10739
Now the app handles the error message for the max TEI count when you are coming from a fallback.
Basically the bug was reporting that when you where doing a fallback search and there was a max number on the TEType then you would not get a warning message but a generic error message

fix: DHIS2-10739 handles tei message

---

cypress/integration/SearchPage.feature
cypress/integration/SearchPage/index.js
src/core_modules/capture-core/components/Pages/Search/SearchForm/SearchForm.epics.js
src/core_modules/capture-core/reducers/descriptions/currentSelections.reducerDescriptionGetter.js

chore: forward-ports the last two PRs 

---

.github/workflows/cypress-tests.yml

@JoakimSM this fixes the issue we had with cypress not re-running the tests. See slack [discussion](https://dhis2.slack.com/archives/G014JTQQ5UN/p1616680292001300)

fix: tests actually rerun

---

d2.config.js

This fixes two issues in the Capture app configuration:
1. In order to successfully override the bundled Capture app, the name needs to match `capture` exactly 
2. The title displayed in the Headerbar and in the browser tab bar is `capture-app` which is incorrect, this corrects it to `Capture`.

fix: correct app name and title specified in d2.config.js

---

src/core_modules/capture-core/components/DataEntries/index.js
src/core_modules/capture-core/components/DataEntryWidgetOutput/DataEntryWidgetOutput.container.js
src/core_modules/capture-core/components/Pages/New/NewPage.container.js
src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/DataEntry/useSaveButtonText.js
src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/RegisterTei.component.js
src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/RegisterTei.container.js
src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/RegisterTei.types.js
src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/open.epics.js
src/core_modules/capture-core/reducers/descriptions/activePage.reducerDescription.js
src/core_modules/capture-core/reducers/descriptions/newRelationship.reducerDescription.js
src/core_modules/capture-ui/FormBuilder/FormBuilder.component.js

https://jira.dhis2.org/browse/DHIS2-10711
How this workes is that the page will be immediately rendered _and_ fetch the relevant data. But then the page would go loading again since we based the readiness of the page on the `lockedSelectorLoads`.
When I was developing this I didnt have a clear separation in my mind, for the locked selector variable called `lockedSelectorLoads`. However, it might make sense that this value is only responsible for the loading state of the locked selector and not of whole pages as I did here.

fix: DHIS2-10711 duplicated calls on search page

---

src/core_modules/capture-core/components/Pages/Search/SearchForm/SearchForm.epics.js
src/core_modules/capture-core/components/PossibleDuplicatesDialog/possibleDuplicatesDialog.epics.js

Hey this solves the ticket https://jira.dhis2.org/browse/DHIS2-10713
Basically we want that when we search by that an attribute that has an optionSet (like the gender data element), to use EQ instead of LIKE, because we don’t need partial matching.

fix: DHIS2-10713 when optionSet use EQ to filter

---

src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.epics.js

fix: DHIS2-10723 port on 2.36.0

---

i18n/en.pot
src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/DataEntry.component.js
src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/epics/defaultColumnConfiguration/defaultConfigGetter.js
src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/NewEventDataEntryWrapper.component.js
src/core_modules/capture-core/components/LockedSelector/QuickSelector/ActionButtons.component.js
src/core_modules/capture-core/components/Pages/EditEvent/DataEntry/EditEventDataEntry.component.js
src/core_modules/capture-core/components/Pages/MainPage/EventWorkingListsCommon/useDefaultColumnConfiguration/useDefaultColumnConfig.js
src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.component.js
src/core_modules/capture-core/components/Pages/Search/SearchPage.component.js
src/core_modules/capture-core/components/Pages/ViewEvent/EventDetailsSection/EditEventDataEntry/EditEventDataEntry.component.js
src/core_modules/capture-core/components/Pages/ViewEvent/EventDetailsSection/EventDetailsSection.component.js
src/core_modules/capture-core/components/Pages/ViewEvent/EventDetailsSection/ViewEventDataEntry/ViewEventDataEntry.component.js
src/core_modules/capture-core/components/Section/SectionHeaderSimple.component.js
src/core_modules/capture-core/components/TeiSearch/SearchOrgUnitSelector/SearchOrgUnitSelector.component.js
src/core_modules/capture-core/converters/clientToList.js
src/core_modules/capture-core/converters/clientToView.js
src/core_modules/capture-core/hooks/useScopeTitleText.js
src/core_modules/capture-ui/CoordinateField/CoordinateField.component.js

Backporting to 36 from #1617, #1640 and https://github.com/dhis2/capture-app/pull/1655
cherry picked from commit 70b103e
cherry picked from commit b92350c
cherry picked from commit 475b27d142c52672efe9a7b399fb92342bcc1837

fix(translations): [DHIS2-8998] missing translation

---

package.json
yarn.lock

bumping @dhis2/ui to 6.9.0. Didn't find any problems.

chore: bump @dhis2/ui from 6.7.0 to 6.9.0

---

.env
.env.cypress
.github/workflows/cypress-tests.yml
cypress/integration/WorkingLists/EventWorkingLists/EventWorkingListsUser/index.js
src/core_modules/capture-core/components/DataEntry/withSaveHandler/withSaveHandler.js

Use 2.37 backend for tests.
There is also a fix in here. Ideally I would have created a separate PR for the fix, but the 2.36 test backend was updated and caused some tests to fail and I didn't want to fix those tests temporarily and then change them again after updating to use the 2.37 backend. The fix is: When updating I encountered a problem where a form could be submitted before the initial field validations were complete (required for compulsory fields). I would have loved to rework this from scratch, but the best solution I found for now is to wait if this happens (I don't think you should be able to experience this if you're not running this using a testing engine)

fix: TECH-622 use 2.37 backend for tests

---

.cypress-cucumber-preprocessorrc.json
.gitignore
cypress.env.json
cypress.json
cypress/plugins/index.js
cypress/support/index.js
package.json
yarn.lock

A couple of days ago Dependabot updated to `@dhis2/cli-utils-cypress` `v8` https://github.com/dhis2/capture-app/commit/ffb0b8a4415ac378d770866b79ad29f6ae9fb283. 
This version introduced breaking changes on how the Cypress tests are being run in a local environment. I followed the instructions from [cli utils cypress docs](https://cli-utils-cypress.dhis2.nu/#/guides/using-the-network-shim?id=quick-setup)  which fixed the local environment errors.

fix: breaking changes from @dhis2/cli-utils-cypress v8

---

.env.cypress
.github/workflows/cypress-tests.yml
cypress.env.json
cypress/integration/SmokeTests/LoginWithUserEnglish/index.js
cypress/integration/WorkingLists/TeiWorkingLists/TeiWorkingListsUser/index.js
cypress/plugins/index.js
cypress/support/helpers.js
cypress/support/index.js
package.json
scripts/startAppForCypress.js
src/core_modules/capture-core/components/DataEntry/withSaveHandler/withSaveHandler.js

Changes:
- Automatically start the app when running `yarn cy:open` and `yarn cy:run`
- Some time ago we made some custom scripts in our app to deal with some Cypress edge cases. An example would be be if you create a `.env.development` or `.env.development.local` file locally and then run `yarn cy:open`; in this case you would, without the scripts, run against your local instance while the api requests made in your tests will run against your test instance. To fix this we specify our Cypress config in the `.env.cypress` file and the server specified here will always be used. Updated the variable names in this file instead of `cypress.json`.
- Fixed some tests after updating the DB

fix: Cypress post upgrade

---

.env
package.json
scripts/verifyCacheVersion.js
src/core_modules/capture-core/flow/typeDeclarations.js
src/core_modules/capture-core/storageControllers/mainStorageController.js

Adding serverVersion to package.json to fix the cache versioning. We will need to change this up a bit when we start publishing to the app hub (we can go into more detail then perhaps)

fix: cache versioning

---

src/core_modules/capture-core/components/Widget/WidgetCollapsible.component.js
src/core_modules/capture-core/components/Widget/WidgetNonCollapsible.component.js
src/core_modules/capture-core/components/Widget/widgetCollapsible.types.js
src/core_modules/capture-core/components/Widget/widgetNonCollapsible.types.js

Added functionality for removing the border on the `Widget`-component as mentioned in [TECH-627](https://jira.dhis2.org/browse/TECH-627).
Pass the `Borderless`-prop (boolean). (Default behavior is false => full border)

TECH-627 Borderless mode

---

src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPage.component.js
src/core_modules/capture-core/components/ScopeSelector/QuickSelector/ActionButtons.component.js
src/core_modules/capture-core/components/ScopeSelector/QuickSelector/OrgUnitField.container.js
src/core_modules/capture-core/components/ScopeSelector/QuickSelector/OrgUnitSelector.component.js
src/core_modules/capture-core/components/ScopeSelector/QuickSelector/Program/CategorySelector.component.js
src/core_modules/capture-core/components/ScopeSelector/QuickSelector/Program/ProgramList.js
src/core_modules/capture-core/components/ScopeSelector/QuickSelector/Program/ProgramSelector.component.js
src/core_modules/capture-core/components/ScopeSelector/QuickSelector/Program/categorySelector.selectors.js
src/core_modules/capture-core/components/ScopeSelector/QuickSelector/Program/programSelector.css
src/core_modules/capture-core/components/ScopeSelector/QuickSelector/QuickSelector.component.js
src/core_modules/capture-core/components/ScopeSelector/QuickSelector/QuickSelector.container.js
src/core_modules/capture-core/components/ScopeSelector/QuickSelector/SingleLockedSelect.component.js
src/core_modules/capture-core/components/ScopeSelector/QuickSelector/actions/QuickSelector.actions.js
src/core_modules/capture-core/components/ScopeSelector/QuickSelector/actions/orgUnitList.actions.js
src/core_modules/capture-core/components/ScopeSelector/QuickSelector/epics/orgUnitList.epics.js
src/core_modules/capture-core/components/ScopeSelector/QuickSelector/index.js
src/core_modules/capture-core/components/ScopeSelector/QuickSelector/programSelector.css
src/core_modules/capture-core/components/ScopeSelector/ScopeSelector.actions.js
src/core_modules/capture-core/components/ScopeSelector/ScopeSelector.component.js
src/core_modules/capture-core/components/ScopeSelector/ScopeSelector.container.js
src/core_modules/capture-core/components/ScopeSelector/ScopeSelector.epics.js
src/core_modules/capture-core/components/ScopeSelector/ScopeSelector.types.js
src/core_modules/capture-core/components/ScopeSelector/index.js

I created a new component `ScopeSelector` and copied the files from `LockerSelector`. I used the ScopeSelector instead of the LockerSelector on the enrollment page. Nothing else changed. 
I prefer to split the refactor into 2 parts to be able to differentiate between the logic that was copy-pasted from the  `LockerSelector` and the new refactored hooks. The real changes are implemented in https://github.com/dhis2/capture-app/pull/1878

refactor: [TECH-580] ScopeSelector in enrollment page - part 1

---

src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/StageDetail.component.js

When trying to pass `sortDirection: null` on comment column , there is an error
`this prop is conditionally required but has value `undefined``
After consulting #frontend channel we should only remove the `onSortClick` when there is no `sortDirection`

fix: Fix sorting error on comment column

---

i18n/en.pot
src/core_modules/capture-core/components/Pages/common/EnrollmentOverviewDomain/enrollment.actions.js
src/core_modules/capture-core/components/WidgetEnrollmentEventNew/Validated/index.js
src/core_modules/capture-core/components/WidgetEnrollmentEventNew/Validated/validated.actions.js
src/core_modules/capture-core/components/WidgetEnrollmentEventNew/Validated/validated.epics.js
src/core_modules/capture-core/components/WidgetEnrollmentEventNew/index.js
src/core_modules/capture-core/reducers/descriptions/enrollment.reducerDescription.js
src/core_modules/capture-core/reducers/descriptions/feedback.reducerDescriptionGetter.js
src/epics/trackerCapture.epics.js

Backport to v37 with cherry-pick from https://github.com/dhis2/capture-app/pull/2083 for the bug https://jira.dhis2.org/browse/DHIS2-11745.

fix: [DHIS-11745][TECH-634] Update the enrollments collection when saving new event

---

src/core_modules/capture-core/components/WidgetEnrollmentEventNew/Validated/validated.epics.js

add `orgUnitName` to the new enrollment event in Redux to be able to display it in the Stage events table

fix: [DHIS2-11745] add orgUnitName to the new enrollment event in Redux

---

src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/epics/eventList.epics.js
src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/epics/getEventListData.js
src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/types/apiTemplate.types.js

https://jira.dhis2.org/browse/TECH-681
On initial load, the eventWorkingList adds a `programStageId=eventProgramStage`-filter. This does nothing and should probably be removed.
The /events-endpoint has now been refactored and will require an ouMode if orgUnit is not selected. Add this to the API-call from the EventWorkingList.

[TECH-681] Refactor api-calls to the /events-endpoint from the EventWorkingList

---

cypress/integration/WidgetsForEnrollmentPages/WidgetEventComment/index.js
cypress/integration/WidgetsForEnrollmentPages/WidgetsForEnrollmentEditEvent.feature
src/core_modules/capture-core/components/WidgetEventEdit/DataEntry/editEventDataEntry.actions.js

[Ticket](https://jira.dhis2.org/browse/DHIS2-11791): Comments don't load in edit mode
This is because `dataEntryNotes` is not set when loadDataEntry so I add the `dataEntryNotes` and removed unused param `foundation`

fix: [DHIS2-11791] widget comments don't show in edit mode

---

cypress/integration/WidgetsForEnrollmentPages/WidgetEventComment/index.js
cypress/integration/WidgetsForEnrollmentPages/WidgetsForEnrollmentEditEvent.feature
src/core_modules/capture-core/components/WidgetEventEdit/DataEntry/editEventDataEntry.actions.js

* fix: [DHIS2-11791] add eventnote to load event data entry
* chore: [DHIS2-11791] add cypress test to view comments in edit mode
* chore: [DHIS2-11791] change cypress wait

fix: [DHIS2-11791] widget comments don't show in edit mode (#2115)

---

i18n/en.pot
src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/EnrollmentPageDefault.component.js
src/core_modules/capture-core/components/Pages/MainPage/WithoutOrgUnitSelectedMessage/WithoutOrgUnitSelectedMessage.js
src/core_modules/capture-core/components/WidgetEnrollment/Actions/Complete/Complete.component.js
src/core_modules/capture-core/components/WidgetEnrollmentEventNew/SavingText/SavingText.component.js
src/core_modules/capture-core/components/WidgetEventEdit/ViewEventDataEntry/ViewEventDataEntry.component.js
src/core_modules/capture-core/components/WidgetIndicator/WidgetIndicator.component.js

[DHIS2-12077](https://jira.dhis2.org/browse/DHIS2-12077): Non-translatable fields in Capture
**Note**
"Complete" has two different meanings but the string is translated just once.
Complete in Save event (as a verb) and Complete as a status in the Enrollment widget
will considere "Completed" as the status in the Enrollment widget

fix: [DHIS2-12077] fix i18n string

---

src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/epics/getConvertedNewSingleEvent.js
src/core_modules/capture-core/components/WidgetEnrollmentEventNew/Validated/getConvertedAddEvent.js
src/core_modules/capture-core/components/WidgetEventEdit/EditEventDataEntry/editEventDataEntry.epics.js

When doing a POST or PUT to the events endpoint, it's unnecessary to send in empty data values (the reason this is unnecessary for the PUT, is that the old values are not preserved)

fix: prevent sending empty data values to the api

---

package.json
yarn.lock

Up app-runtime to utilize the fix here: https://github.com/dhis2/app-runtime/pull/1071
Prior to this fix the refetch function (from useDataQuery) was recreated on each render; this caused infinite loops in some of our fetching code (when refetch was added to the useEffect dependency array the hook would run on every render)

fix: refetch dependency causing infinite loop

---

cypress/integration/LockedSelector.feature
src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPage.container.js
src/core_modules/capture-core/components/Pages/common/EnrollmentOverviewDomain/useCommonEnrollmentDomainData.js

Even though we don't use app-runtime v3 in the v37 branch it makes sense to back port this.

fix: [DHIS2-12134] fetching logic in common enrollment hook

---

cypress/integration/NewPage/index.js

The test was based on a hardcoded year value. It started falling after the 1st of January.

fix: cypress test year change

---

cypress/integration/NewPage/index.js

(cherry picked from commit b658b10195e2e8dc16a8990ea26fc79ae3450b78)
The 10 failures in Cypress are [known issues ](https://github.com/dhis2/capture-app/wiki/Pull-Request-Guidelines#cypress-tests-to-follow-up-on-the-tests-are-commented-out-from-our-code-base)

fix: cypress test with hardcored 2021 year (#2390)

---

package.json

Ensure old client caches are updated when loading the 2.38 version of the app.

fix: up cache version for 2.38

---

docs/user/using-the-capture-app.md

Clarify in capture app docs that event/enrollment comments cannot be deleted.

docs: clarify comments cannot be deleted

---

.env

Make api requests use the URL `api/38/....`. There should not be any differences in what we get the from the API, the versioning doesn't do much at the moment. Seems like a good time to reset anyway though, since we're switching to the new tracker endpoints.

fix: use api version 38

---

src/core_modules/capture-core/components/Pages/Search/SearchForm/SearchForm.epics.js
src/core_modules/capture-core/components/PossibleDuplicatesDialog/possibleDuplicatesDialog.epics.js
src/core_modules/capture-core/components/TeiSearch/epics/teiSearch.epics.js

Removed `fields=*` from some api requests.

fix: remove fields query arg

---

CODEOWNERS
d2.config.js

Align all our application versions that range between 0.x.x and 36.x.x
with different semantics to a single version scheme with distinct
semantics for what constitutes a breaking change.
We have chosen to bump to v100.0.0 to signify the depature from the old
version scheme to the new.
For more information:
dhis2/notes#293
BREAKING CHANGE: App version becomes decoupled from DHIS2 versions, see
the d2.config.js or App Hub for DHIS2 version compatibility.

chore(release): migrate to new app version scheme

---

src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/Setup/TeiWorkingListsSetup.component.js
src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/Setup/useDefaultColumnConfig.js
src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/getTemplates.js
src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getTeiListData/convertToClientTeis.js
src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getTeiListData/getTeiListData.js
src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/initTeiWorkingListsView.js
src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/helpers/TEIFilters/apiTEIFilterToClientConfigConverter/convertSortToClient.js
src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/helpers/TEIFilters/getCustomColumnsConfiguration.js
src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/types/concept.types.js
src/core_modules/capture-core/components/WorkingLists/WorkingListsCommon/helpers/buildFilterQueryArgs/filterConverters/dateConverter.js

Remove the conversion and use API fields name 
`regDate` to `createdAt`
`regUnit` to `orgUnit`

fix: [DHIS2-12870] use api fields name for TEIFilters

---

.github/dependabot.yml
.github/workflows/verify-app.yml

This should fix the concurrency issue @jasminenguyennn experienced earlier (where one of the commits was missing in the build).
Also, I'm decreasing the Dependabot pull requests limit to 5, opened on a weekly basis. I think this might help us actually follow up on some of those, at the moment it feels a bit overwhelming.

chore(workflow): fix concurrency issue and decrease dependabot PRs

---

cypress/integration/LockedSelector/index.js
cypress/support/helpers.js

Test scenario: New event page > Url with invalid program id randomly failed on PRs
I look into the capture of the run, the page url has not changed when `cy.visit`, this PR tried to fix that by reassign the url, make the page reload after that.

chore: [DHIS2-13029] attempt to fix cypress test

---

cypress/integration/NewPage/index.js
src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/epics/saveNewSingleEvent.epics.js

After adding an event, the user is redirected to the main-page with the programId and orgUnitId is stored in the URL. 
The URL is missing a "?", and the Ids are therefore interpreted as a part of the pathname, and not as a query parameter.
A refresh would cause the app to lose the program- and orgUnit-context.

fix: [DHIS2-13241] URL out of sync after adding event

---

src/core_modules/capture-core/metaDataMemoryStoreBuilders/programs/getRulesAndVariablesFromIndicators.js
src/core_modules/capture-core/metaDataStoreLoaders/programs/quickStoreOperations/storeProgramIndicators.js

The app does not use program indicators with displayInForm=false, so we ask the backend to filter out these to cut down on the loading time.

fix: [DHIS2-12188] do not download program indicators unless displayInForm=true

---

src/core_modules/capture-core-utils/rulesEngine/commonUtils/index.js
src/core_modules/capture-core-utils/rulesEngine/commonUtils/numberToString.js
src/core_modules/capture-core-utils/rulesEngine/index.js
src/core_modules/capture-core-utils/rulesEngine/processors/rulesEffectsProcessor/rulesEffectsProcessor.js
src/core_modules/capture-core-utils/rulesEngine/services/VariableService/VariableService.js
src/core_modules/capture-core-utils/rulesEngine/services/VariableService/helpers/structureEvents.js
src/core_modules/capture-core-utils/rulesEngine/services/VariableService/index.js
src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.container.js
src/core_modules/capture-core/components/WidgetIndicator/WidgetIndicatorContent/WidgetIndicatorContent.js
src/core_modules/capture-core/metaDataMemoryStoreBuilders/programs/getRulesAndVariablesFromIndicators.js
src/core_modules/capture-core/rules/__tests__/ruleEffectsForEventProgram.test.js
src/core_modules/capture-core/rules/__tests__/rulesEffectsForTrackerProgram.test.js
src/core_modules/capture-core/rules/getApplicableRuleEffects.js

- Renamed `eventDate` -> `occurredAt` to fix behaviour of source type `DATAELEMENT_PREVIOUS_EVENT`.
- Changed parsing of variables appearing as `programStageId.dataElementId` in program indicator expressions.

fix: [DHIS2-12120] conversion of program indicators to program rules

---

src/core_modules/capture-core-utils/validators/form/index.js
src/core_modules/capture-core-utils/validators/form/nonFutureDate.validator.js
src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/DataEntry.component.js
src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/fieldValidators/eventDate.validatorContainersGetter.js
src/core_modules/capture-core/components/WidgetEnrollmentEventNew/DataEntry/DataEntry.component.js
src/core_modules/capture-core/components/WidgetEnrollmentEventNew/DataEntry/fieldValidators/eventDate.validatorContainersGetter.js
src/core_modules/capture-core/components/WidgetEventEdit/DataEntry/fieldValidators/eventDate.validatorContainersGetter.js
src/core_modules/capture-core/components/WidgetEventEdit/EditEventDataEntry/EditEventDataEntry.component.js

Replacement of https://github.com/dhis2/capture-app/pull/2782.
This version follows the same pattern as was used for restricting enrollment dates.

fix: [DHIS2-8613] limit report date of new events to today or earlier

---

src/core_modules/capture-core/components/List/OnlineList/OnlineList.component.js
src/core_modules/capture-core/components/WorkingLists/WorkingListsBase/ContextBuilder/ContextProviders/WorkingListsListViewUpdaterContextProvider.component.js
src/core_modules/capture-core/components/WorkingLists/WorkingListsBase/ContextBuilder/ContextProviders/workingListsListViewUpdaterContextProvider.types.js
src/core_modules/capture-core/components/WorkingLists/WorkingListsBase/ContextBuilder/WorkingListsContextBuilder.component.js
src/core_modules/capture-core/components/WorkingLists/WorkingListsBase/ListViewLoader/ListViewLoader.component.js
src/core_modules/capture-core/components/WorkingLists/WorkingListsBase/ListViewLoader/useIsContextInSync.js
src/core_modules/capture-core/components/WorkingLists/WorkingListsBase/ListViewUpdater/ListViewUpdater.component.js
src/core_modules/capture-core/components/WorkingLists/WorkingListsBase/workingListsBase.types.js
src/core_modules/capture-core/components/WorkingLists/WorkingListsCommon/hooks/useWorkingListsCommonStateManagement.js
src/core_modules/capture-core/reducers/descriptions/workingLists/meta/meta.reducerDescription.js
src/core_modules/capture-core/reducers/descriptions/workingLists/workingLists.reducerDescription.js

[DHIS2-13285](https://jira.dhis2.org/browse/DHIS2-13285)
This PR ensure that changing the org. unit doesn't reset the view settings. Data will be fetched based on the previous view settings (but reset to the first page).

feat: [DHIS2-13285] Preserve view settings when changing org unit

---

jest.config.js

Fixed an issue where jest was using stale code for internal core modules. When importing modules from capture-core, capture-core-utils or capture-ui using the absolute path, jest would get the modules from the ".d2" folder (and ".d2" is only updated when running yarn start or yarn build).

chore: jest config update

---

cypress/integration/WorkingLists/EventWorkingLists/EventWorkingListsUser/index.js
cypress/integration/WorkingLists/TeiWorkingLists/TeiWorkingListsUser/index.js
src/core_modules/capture-core/components/WorkingLists/WorkingListsBase/TemplateMaintenance/SharingDialog.component.js

[TECH-834](): migrate sharing dialog to use ui library
Demo: https://deploy-preview-2895--dhis2-capture.netlify.app/

chore: [TECH-834] using sharing dialog from ui

---

src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageOverview/StageOverview.component.js

- Uses `UI` `Tooltip` component instead of MUI.
- Only displays the stage description `i` icon (tooltip trigger) if a description exists.
After:
Before:

fix: [DHIS2-13612] use conditional UI tooltip for stage descriptions

---

cypress/integration/ScopeSelector.feature
cypress/integration/ScopeSelector/index.js

Follow up on https://github.com/dhis2/capture-app/pull/2983#discussion_r958359191
My interpretation was wrong here @simonadomnisoru. The problem was that the org unit was already visible of course. Your solution would definitely work, but to simplify it, I changed the test to select an org. unit that is not initially visible.

chore: [TECH-1345] fix cypress test

---

.github/workflows/verify-app.yml

skip CI release job for dependabot PRs.

chore: skip CI release for dependabot PRs

---

src/core_modules/capture-core-utils/rulesEngine/services/expressionService/injectVariableValues.js

Fixes a problem where program rule variable names with spaces don't work when used in some d2 functions.

fix: [DHIS2-13906] variable names with spaces in rules engine

---

src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/StageDetail.component.js

Implements [DHIS2-14081](https://dhis2.atlassian.net/browse/DHIS2-14081).
- Uses the `DataTableCell` `staticStyle` prop on the "accessory row" in the Stages -> Events table on Enrollment dashboard to prevent hover styles. This row has no `onClick` and is not a data row, so should not have hover styles.

fix: [DHIS2-14081] use static style for accessory row in events table

---

.github/workflows/verify-app.yml

As discussed: change the verify workflow to continue even though the dev-tests fail

chore: non-mandatory dev-tests

---

src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/helpers/eventFilters/clientConfigToApiEventFilterQueryCriteriaConverter/convertToEventFilterEventQueryCriteria.js

Hey all,
When upgrading to the new tracker endpoints in 2.38, for some reason, we ended up saving the occurredAt-column in the working lists as eventDate. Not sure if this was a bug in the API at the time, or if it was just a slip up from my side, but it lead to breaking tests now. The API, which would return a status code 200 until now, has changed to return a 400 bad request. 
This PR resolves that we solve both saving correct label in the `eventFilters`-endpoints and ensures correct order-label. 
Steps to reproduce bug:
1. Open `/#/?orgUnitId=DiszpKrYNg8&programId=eBAyeGv0exc`
2. Do any changes (for example changing sort order on the event date)
3. Try to save a working list view
The API should throw an error and the app will crash.

fix: [DHIS2-15109] eventDate breaks saved working lists

---

packages/rules-engine/src/services/VariableService/VariableService.js

Introduces `buildContextVariable` and `buildRawContextVariable`.
The first of these converts the given input value, the second does not.

fix: [DHIS2-14976] apply input converters on context variables

---

cypress/integration/EnrollmentAddEventPage/EnrollmentAddEventPageForm.feature
src/core_modules/capture-core/rules/postProcessRulesEffects.js

Checks if a program rule "assign effects" is targeting an option set, and if so, checks that the value to be assigned lies in the option set. If the value does not lie in the option set, it is replaced with `null` (meaning no selected option).

fix: [DHIS2-14190] restrict which values can be assigned to option sets

---

src/core_modules/capture-core/components/D2Form/D2Form.component.js
src/core_modules/capture-core/components/D2Form/D2Section.component.js

Issue: [DHIS2-13884](https://dhis2.atlassian.net/browse/DHIS2-13884)
The padding occurs because every section, hidden or not, is wrapped inside a div.
This pull request solves the problem by moving the enclosing div down the component tree, to the point right after the sections' check for emptiness is made.
[DHIS2-13884]: https://dhis2.atlassian.net/browse/DHIS2-13884?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [DHIS2-13884] remove padding caused by hidden sections

---

src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getEventListData/getEventListData.js

The solution was to sanitize the `trackedEntityIds` by removing the first `;`. The PR also fixed the [Cypress tests](https://github.com/dhis2/capture-app/wiki/Pull-Request-Guidelines#cypress-tests-to-follow-up-on-the-tests-are-commented-out-from-our-code-base) related to the Program stage WL

fix: [DHIS2-15342] program stage WL trackedEntities request

---

.github/workflows/verify-app.yml

Translation-PRs from Transifex are automatically closed when our cypress tests (dev-instance) fails. See: https://github.com/dhis2/capture-app/pulls?q=fix%28translations%29
Until we have a reliable setup I suggest we disable the Cypress tests for these PRs.

ci: skip cypress for translations

---

.github/workflows/e2e-tests.yml
.github/workflows/verify-app.yml

Reduce the number of Cypress containers running in CI. Sometimes we see that there are no runners available and it can cause the execution to timeout. By reducing it we should see a higher success rate.

ci: reduce cypress containers

---

src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/hooks/useProgramMetadata.js
src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/hooks/useProgramStages.js
src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/hooks/useEventList.js
src/core_modules/capture-core/components/WidgetStagesAndEvents/types/common.types.js

[DHIS2-15525](https://dhis2.atlassian.net/browse/DHIS2-15525)
- use the dataElement `formNames` in the StagesAndEvents widget. 
- fallback to `name` if`formNames` is undefined

fix: [DHIS2-15525] show formNames in the enrollment dashboard

---

src/core_modules/capture-core/components/DataEntries/common/TEIAndEnrollment/useMetadataForRegistrationForm/useMetadataForRegistrationForm.js

Option sets gets displayed as a text field instead of an option set in Tei Registration without an Enrollment.

fix: [DHIS2-15700] Option sets not working in TEI Registration

---

cypress/integration/WorkingLists/TeiWorkingLists/TeiWorkingListsUser.feature
cypress/integration/WorkingLists/TeiWorkingLists/TeiWorkingListsUser/index.js

[TECH-1642](https://dhis2.atlassian.net/browse/TECH-1642)
Small change to fix the `While in a program stage working list, the user can sort by both TEA and data elements` cypress test. The rest of the failures on dev are [known errors](https://github.com/dhis2/capture-app/wiki/Pull-Request-Guidelines#cypress-tests-to-follow-up-on-the-tests-are-commented-out-from-our-code-base) and will be fixed by [DHIS2-15814](https://dhis2.atlassian.net/browse/DHIS2-15814).
[TECH-1642]: https://dhis2.atlassian.net/browse/TECH-1642?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DHIS2-15814]: https://dhis2.atlassian.net/browse/DHIS2-15814?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [TECH-1642] adapt order scenario

---

src/core_modules/capture-core/components/D2Form/FormFieldPlugin/FormFieldPlugin.container.js
src/core_modules/capture-core/components/D2Form/FormFieldPlugin/FormFieldPlugin.types.js

Tech summary:
We need to pass in ProgramId and orgUnitId as part of the context for the form field plugin.

feat: [DHIS2-15830] Add orgUnitId and programId to plugin context

---

cypress/integration/WorkingLists/TeiWorkingLists/TeiWorkingListsUser.feature
cypress/integration/WorkingLists/TeiWorkingLists/TeiWorkingListsUser/index.js

[TECH-1644](https://dhis2.atlassian.net/browse/TECH-1644)
Fix the flaky custom program stage working list tests by cleaning the DB
[TECH-1644]: https://dhis2.atlassian.net/browse/TECH-1644?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [TECH-1644] flaky custom program stage working list tests

---

cypress/e2e/MainPage.feature
cypress/e2e/MainPage/index.js
src/core_modules/capture-core-utils/featuresSupport/support.js
src/core_modules/capture-core/components/NonBundledDhis2Icon/NonBundledDhis2Icon.component.js

Support custom icons
TECH-summary:
- Add feature flag for custom icons
- Check if applicable, and add .svg suffix if v<41
- Add tests

feat: [DHIS2-14275] Support custom icons

---

src/core_modules/capture-core/components/WidgetProfile/DataEntry/ProgramRules/rulesContainer.js
src/core_modules/capture-core/components/WidgetProfile/DataEntry/hooks/useEvents.js
src/core_modules/capture-core/components/WidgetProfile/DataEntry/hooks/useLifecycle.js
src/core_modules/capture-core/components/WidgetProfile/hooks/useProgram.js

[DHIS2-15686](https://dhis2.atlassian.net/browse/DHIS2-15686)
Corrects some inaccuracies in the profile widget's rule engine payload builder.
[DHIS2-15686]: https://dhis2.atlassian.net/browse/DHIS2-15686?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [DHIS2-15686] fix program rule variables for edit profile mode

---

src/core_modules/capture-core/components/DataEntries/Enrollment/actions/open.actionBatchs.js

Summary:
- Add the defaultDataEntryValues to the rules execution

fix: [DHIS2-15983] Enrollment date not assigned on form init

---

src/core_modules/capture-core/components/Pages/common/TEIRelationshipsWidget/TrackedEntityRelationshipsWrapper/TrackedEntityRelationshipsWrapper.component.js
src/core_modules/capture-core/components/WidgetsRelationship/WidgetTrackedEntityRelationship/WidgetTrackedEntityRelationship.component.js
src/core_modules/capture-core/components/WidgetsRelationship/common/RelationshipsWidget/RelationshipsWidget.component.js
src/core_modules/capture-core/components/WidgetsRelationship/common/RelationshipsWidget/relationshipsWidget.types.js
src/core_modules/capture-core/components/WidgetsRelationship/common/RelationshipsWidget/useGroupedLinkedEntities.js
src/core_modules/capture-core/components/WidgetsRelationship/common/useRelationships/useRelationships.js

Tech summary:
- Added an extra condition that removed relationships where relationship type is unidirectional and the source is in the `to`-side
Test case: https://dhis2.atlassian.net/browse/DHIS2-16239

fix: [DHIS2-16084] Filter unidirectional relationship types

---

src/core_modules/capture-core-utils/validators/form/orgUnit.validator.js
src/core_modules/capture-core/components/FormFields/New/Fields/OrgUnitField/SingleOrgUnitSelectField.component.js
src/core_modules/capture-core/components/Pages/common/TEIRelationshipsWidget/TrackedEntityRelationshipsWrapper/TrackedEntityRelationshipsWrapper.component.js

Fixes https://dhis2.atlassian.net/browse/DHIS2-16317

fix: [DHIS2-16317] Incorrect error message on orgUnit type data element

---

packages/rules-engine/src/commonUtils/normalizeRuleVariable.js
packages/rules-engine/src/constants/typeKeys.const.js
packages/rules-engine/src/constants/typeToInterfaceFnName.const.js
packages/rules-engine/src/d2Functions/getD2Functions.js
packages/rules-engine/src/d2Functions/getD2Functions.types.js
packages/rules-engine/src/helpers/OptionSetHelper.js
packages/rules-engine/src/rulesEngine.types.js
packages/rules-engine/src/services/VariableService/VariableService.js
packages/rules-engine/src/services/VariableService/index.js
packages/rules-engine/src/services/VariableService/variableService.types.js
src/core_modules/capture-core/components/FormFields/New/Fields/MultiSelectField/MultiSelectField.component.js
src/core_modules/capture-core/components/FormFields/New/Fields/MultiSelectField/MultiSelectField.types.js
src/core_modules/capture-core/rules/__tests__/postProcessRulesEffects.test.js
src/core_modules/capture-core/rules/__tests__/ruleEffectsForEventProgram.test.js
src/core_modules/capture-core/rules/__tests__/rulesEffectsForTrackerProgram.test.js
src/core_modules/capture-core/rules/converters/inputConverter.js
src/core_modules/capture-core/rules/converters/outputConverter.js
src/core_modules/capture-core/rules/postProcessRulesEffects.js

[DHIS2-15888](https://dhis2.atlassian.net/browse/DHIS2-15888)
- Right now, it is not possible to check specific multi-text values. [DHIS2-16211](https://dhis2.atlassian.net/browse/DHIS2-16211) and [DHIS2-13436](https://dhis2.atlassian.net/browse/DHIS2-13436) must be implemented first.
- I added logic to check that a multi-text field has a value, therefore rules like the one mentioned in the ticket description `A{AllergiesMulti} != ""` should work correctly.
- The same rule actions that can be applied to an element with a single value option can also be applied to an element with multiple value options (Hide, Hide option, Show error, Show warning, Make filed mandatory, Assign a value, etc.).
- To assign multiple values, the expression to be evaluated and assigned must …

fix: [DHIS2-15888] multi text element in program rules

---

i18n/en.pot
src/core_modules/capture-core/components/DataEntries/Enrollment/EnrollmentWithFirstStageDataEntry/EnrollmentWithFirstStageDataEntry.component.js
src/core_modules/capture-core/components/DataEntries/Enrollment/EnrollmentWithFirstStageDataEntry/EnrollmentWithFirstStageDataEntry.constants.js
src/core_modules/capture-core/components/DataEntries/Enrollment/EnrollmentWithFirstStageDataEntry/getDataEntryPropsToInclude.js
src/core_modules/capture-core/components/DataEntries/Enrollment/EnrollmentWithFirstStageDataEntry/hooks/useDataEntrySections.js
src/core_modules/capture-core/components/DataEntries/Enrollment/actions/open.actionBatchs.js
src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/hooks/useBuildEnrollmentPayload.js
src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/Assignee/Assignee.component.js
src/core_modules/capture-core/components/DataEntry/common/convertDataEntryValuesToClientValues.js
src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/helpers/deriveFirstStageDuringRegistrationEvent.js

[DHIS2-16527](https://dhis2.atlassian.net/browse/DHIS2-16527)
The code I added in `EnrollmentWithFirstStageDataEntry.component` was copied directly from another file, so not sure what all the properties do and whether some of them could be omitted (please have a look if you recognise them :slightly_smiling_face:).
[DHIS2-16527]: https://dhis2.atlassian.net/browse/DHIS2-16527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [DHIS2-16527] assign user on first stage registration

---

src/core_modules/capture-core/components/IncompleteSelectionsMessage/index.js
src/core_modules/capture-core/components/Pages/MainPage/MainPage.component.js
src/core_modules/capture-core/components/Pages/Search/SearchPage.component.js
src/core_modules/capture-core/components/SearchBox/SearchBox.component.js
src/core_modules/capture-core/components/SearchBox/SearchForm/SearchForm.component.js

Fixes [DHIS2-16257](https://dhis2.atlassian.net/browse/DHIS2-16257).
This PR adjusts the padding, spacing, and border usage on the search form page. There are multiple instances of the search form / search box, this PR standardises the design.
Before:
After:
[DHIS2-16257]: https://dhis2.atlassian.net/browse/DHIS2-16257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: search form padding, spacing, borders

---

packages/rules-engine/src/RulesEngine.js
packages/rules-engine/src/services/expressionService/executeExpression.js
packages/rules-engine/src/services/expressionService/executeExpression.types.js

Improve program rules verbose logging for feature parity.
- Use console.log for both rules expressions and action expressions.
- Print the actual evaluation result.
- Change errors from log.warn to log.error

fix: [DHIS2-17072] Improve verbose rules engine message

---

src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/hooks/useProgramMetadata.js
src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/hooks/useEventList.js

Tech-summary:
- Use the option set displayName instead of option set codes in the stages&events tables.
Before:
After:

fix: [DHIS2-16393] Use option name in Stages&Events

---

src/core_modules/capture-core/components/Pages/common/TEIRelationshipsWidget/useTEIRelationshipsWidgetMetadata.js
src/core_modules/capture-core/components/WidgetsRelationship/common/RelationshipsWidget/LinkedEntityTableBody.component.js
src/core_modules/capture-core/components/WidgetsRelationship/common/RelationshipsWidget/types/GroupedLinkedEntities.types.js
src/core_modules/capture-core/components/WidgetsRelationship/common/RelationshipsWidget/useRelationshipTypes.js
src/core_modules/capture-core/components/WidgetsRelationship/common/Types/RelationshipTypes.types.js
src/core_modules/capture-core/components/WidgetsRelationship/common/utils/formatRelationshipTypes.js
src/core_modules/capture-core/components/WidgetsRelationship/common/utils/replaceElementIdsWithElement.js
src/core_modules/capture-core/converters/clientToList.js

Tech-summary:
- Use Option name instead of code in the relationships widget table
Before:
After:

fix: [DHIS2-16394] use option set name in relationship table

---

src/core_modules/capture-core/components/WidgetsRelationship/common/RelationshipsWidget/useGroupedLinkedEntities.js

Tech-summary:
- Hide the delete icon in the relationships table if the user has no write access to the type

fix: [DHIS2-17110] Hide delete-icon in relationships if no write access

---

src/core_modules/capture-core/components/Pages/common/TEIRelationshipsWidget/useTEIRelationshipsWidgetMetadata.js
src/core_modules/capture-core/components/WidgetsRelationship/WidgetTrackedEntityRelationship/NewTrackedEntityRelationship/LinkedEntityMetadataSelector/useApplicableTypesAndSides.js
src/core_modules/capture-core/components/WidgetsRelationship/common/RelationshipsWidget/useRelationshipTypes.js

Tech-summary:
- Filter out any relationship types the user does not have data write access to
- Do this for both cached indexed db, but also when in self-contained mode

fix: [DHIS2-17084] Filter Relationship Types for write access

---

src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/helpers/deriveAutoGenerateEvents.js

[DHIS2-17131](https://dhis2.atlassian.net/browse/DHIS2-17131)
The dates appears to already be on standard system format (yyyy-mm-dd) in `deriveAutoGenerateEvents()`.
[DHIS2-17131]: https://dhis2.atlassian.net/browse/DHIS2-17131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [DHIS2-17131] schedule dates with format DD-MM-YYYY

---

src/core_modules/capture-core/components/WidgetProfile/WidgetProfile.component.js
src/core_modules/capture-core/components/WidgetProfile/hooks/useApiProgram.js
src/core_modules/capture-core/components/WidgetProfile/hooks/useOptionGroups.js
src/core_modules/capture-core/components/WidgetProfile/hooks/useProgram.js

[DHIS2-17096](https://dhis2.atlassian.net/browse/DHIS2-17096)
The program object downloaded for the profile widget is missing option group data.
This pull request
1. Downloads the missing data
2. Transforms this data to the expected format
3. Adds the transformed data to the `program` object.
[DHIS2-17096]: https://dhis2.atlassian.net/browse/DHIS2-17096?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [DHIS2-17096] show/hide option groups in profile widget

---

src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.epics.js
src/epics/trackerCapture.epics.js

Tech-summary:
- Remove uid from the redux store after a failed save attempt (this resets the loading states)

fix: [DHIS2-17177] Registration page stuck after failed save

---

src/core_modules/capture-core/components/ListView/withEndColumnMenu/RowMenu.component.js

Tech-summary:
- The button was actually rendered, but it was hidden behind the pagination component. Change strategy to be fixed instead of absolute

fix: [DHIS2-16931] Working list hides delete button

---

src/core_modules/capture-core/components/Pages/common/EnrollmentOverviewDomain/useCommonEnrollmentDomainData/useCommonEnrollmentDomainData.js
src/core_modules/capture-core/components/WidgetEnrollment/hooks/useEnrollment.js

https://dhis2.atlassian.net/browse/DHIS2-17161
Skip attribute values in the api GET request in the enrollment Widget as it should not be needed. 
This way, we don't potentially post stale attribute values to the api.
Also, stopped retrieving enrollment.attributes for the EnrollmentDomain in the Redux store (we use EnrollmentDomain.attributeValues)

fix: [DHIS2-17161] Do not update attribute values from enrollment Widget

---

cypress/e2e/NewPage.feature
cypress/e2e/NewPage/index.js
src/core_modules/capture-core/components/DataEntries/TrackedEntityInstance/TrackedEntityInstanceDataEntry.component.js
src/core_modules/capture-ui/CoordinateField/CoordinateField.component.js

[DHIS2-17225](https://dhis2.atlassian.net/browse/DHIS2-17225)
**Tech summary:**
- added the missing `orgUnit` to TrackedEntityInstanceDataEntry
[DHIS2-17225]: https://dhis2.atlassian.net/browse/DHIS2-17225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [DHIS2-17225] cannot add TET with polygon or coordiante

---

cypress/e2e/WorkingLists/TeiWorkingLists/TeiWorkingListsUser.feature
cypress/e2e/WorkingLists/TeiWorkingLists/TeiWorkingListsUser/index.js
src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getEventListData/getEventListData.js

[DHIS2-17291](https://dhis2.atlassian.net/browse/DHIS2-17291) and [DHIS2-16597](https://dhis2.atlassian.net/browse/DHIS2-16597)
- do not query for trackedEntities if there are no events matching the working lists filters
[DHIS2-17291]: https://dhis2.atlassian.net/browse/DHIS2-17291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DHIS2-16597]: https://dhis2.atlassian.net/browse/DHIS2-16597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [DHIS2-17291][DHIS2-16597] skip trackedEntites request when no events match the WL filters

---

.github/workflows/e2e-tests.yml
.github/workflows/verify-app.yml
README.md
cypress/support/generateTestMatrix.js

JIRA ticket: [DHIS2-17372](https://dhis2.atlassian.net/browse/DHIS2-17372)
This PR enhances our Cypress test execution setup by improving how tests are run in parallel both locally and in Cypress Cloud, and optimises the triggering mechanisms for test recordings and executions in Cypress Cloud.
- **Conditional Recording**: Introduced logic to activate recordings via commit messages ([e2e record]) or GitHub labels (e2e record), offering flexible control over when recordings are initiated in Cypress Cloud.
- **Parallel Test Execution**: Redefined how tests are grouped and executed in parallel, reducing redundancy and improving runtime efficiency.
- **Security Improvement**: Ensured the Cypress record key is used securely throughout our CI configurations.
- **Documentation Update**: Revised …

chore: [DHIS2-17372] optimize Cypress recordings with conditional triggers

---

cypress/e2e/EnrollmentAddEventPage/EnrollmentAddEventPageForm/index.js
cypress/e2e/EnrollmentPage/BreakingTheGlass/index.js
cypress/e2e/EnrollmentPage/HiddenProgramStage/index.js
cypress/e2e/NewEventThroughAddRelationship/index.js

[DHIS2-17513](https://dhis2.atlassian.net/browse/DHIS2-17513)
This PR fixes these 7 scenarios in the dev instance:
- User interacts with event working lists > Show next page
- User interacts with event working lists > Show next page then previous page
- User interacts with event working lists > Show next page then first page
- User interacts with the Enrollment New Event Workspace > User can add a new event and complete the enrollment
- User adds events > User adds event in the malaria case registration program
- User adds events > User adds event with relationship to existing person in the malaria case registration program
- Hidden program stage > The user cannot add an event in a hidden program stage
The only remaining failure is related to adding event notes and it …

refactor: [DHIS2-17513] remove deprecated endpoints calls from cypress steps

---

src/core_modules/capture-core/components/Pages/common/TEIRelationshipsWidget/TeiSearch/epics/teiSearch.epics.js
src/core_modules/capture-core/components/PossibleDuplicatesDialog/possibleDuplicatesDialog.epics.js
src/core_modules/capture-core/components/SearchBox/SearchForm/SearchForm.epics.js
src/core_modules/capture-core/components/TeiSearch/epics/teiSearch.epics.js
src/core_modules/capture-core/trackedEntityInstances/getSubValues.js
src/core_modules/capture-core/trackedEntityInstances/trackedEntityInstanceRequests.js

[DHIS2-17531](https://dhis2.atlassian.net/browse/DHIS2-17531)
Tech summary:
-  when `FEATURES.trackerImageEndpoint` is true, use the new image endpoint in the search tracked entity results card. For versions below 2.41, the old endpoints are kept. 
-  add the programId when the search is done within a program context. Used to build the image URL
[DHIS2-17531]: https://dhis2.atlassian.net/browse/DHIS2-17531?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [DHIS2-17531] use new image endpoint in search tracked entity results

---

src/core_modules/capture-core/components/FormFields/New/HOC/messages/withDisplayMessages.js

Implements [DHIS2-16852](https://dhis2.atlassian.net/browse/DHIS2-16852)
[DHIS2-16852]: https://dhis2.atlassian.net/browse/DHIS2-16852?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [DHIS2-16852] confusing-ui-when-there-is-more-than-one-warning

---

src/core_modules/capture-core/components/D2Form/D2Section.component.js

[DHIS2-8814](https://dhis2.atlassian.net/browse/DHIS2-8814?atlOrigin=eyJpIjoiN2M3OGE3YThlMzI3NDMyMGIyNTI1NTNkMmM2YjFiZTgiLCJwIjoiaiJ9)
- Add overflow to `d2-section`
[DHIS2-8814]: https://dhis2.atlassian.net/browse/DHIS2-8814?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [DHIS2-8814] Table in custom form overflows container with no scrollbar

---

src/core_modules/capture-core/components/D2Form/D2Section.component.js

[DHIS2-17736](https://dhis2.atlassian.net/browse/DHIS2-17736?atlOrigin=eyJpIjoiZmMwZjBkMWJkNGQ1NGQxYThkZjAxMGY1MTQ0NmFmNDQiLCJwIjoiaiJ9)
- Removed overflowx prop implemented in [DHIS2-8814](https://github.com/dhis2/capture-app/pull/3655)
[DHIS2-17736]: https://dhis2.atlassian.net/browse/DHIS2-17736?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DHIS2-8814]: https://dhis2.atlassian.net/browse/DHIS2-8814?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [DHIS2-17736] Dropdown Regression in Registration Form

---

cypress/e2e/EnrollmentEditEventPage/EnrollmentEditEventPageForm/EnrollmentEditEventPageForm.feature
cypress/e2e/EnrollmentEditEventPage/EnrollmentEditEventPageForm/EnrollmentEditEventPageForm.js

[DHIS2-17730](https://dhis2.atlassian.net/browse/DHIS2-17730)
- properly clean the DB
[DHIS2-17730]: https://dhis2.atlassian.net/browse/DHIS2-17730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: [DHIS2-17730] flaky scenario in EnrollmentEditEventPageForm.feature

---

cypress/e2e/EnrollmentAddEventPage/EnrollmentAddEventPageForm/EnrollmentAddEventPageForm.feature
cypress/e2e/EnrollmentAddEventPage/EnrollmentAddEventPageForm/EnrollmentAddEventPageForm.js

[DHIS2-17657](https://dhis2.atlassian.net/browse/DHIS2-17657)
**Tech summary**:
- add missing steps and properly clean the DB
[DHIS2-17657]: https://dhis2.atlassian.net/browse/DHIS2-17657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: [DHIS2-17657] flaky scenario in EnrollmentAddEventPageForm.feature

---

src/core_modules/capture-core/components/WidgetProfile/DataEntry/helpers/convertClientToView.js

[DHIS2-15687](https://dhis2.atlassian.net/browse/DHIS2-15687)
- use the translated displayName
- the fix works for both `TEXT` and `MULTI_TEXT` options sets.
[DHIS2-15687]: https://dhis2.atlassian.net/browse/DHIS2-15687?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [DHIS2-15687] display translated options in profile widget

---

src/core_modules/capture-core/components/FormFields/Generic/D2TrueOnly.component.js
src/core_modules/capture-core/components/FormFields/Options/FormGroup.component.js
src/core_modules/capture-core/components/FormFields/Options/MultiSelectBoxes/MultiSelectBoxes.component.js
src/core_modules/capture-core/components/FormFields/Options/SingleSelectBoxes/SingleSelectBoxes.component.js
src/core_modules/capture-core/components/FormFields/Options/SingleSelectBoxes/singleSelectBoxes.types.js

Implements [DHIS2-17648](https://dhis2.atlassian.net/browse/DHIS2-17648)
[DHIS2-17648]: https://dhis2.atlassian.net/browse/DHIS2-17648?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [DHIS2-17648] Replace Material UI FormGroup, FormLabel and FormControl

---

cypress/e2e/EnrollmentPage/HiddenProgramStage/HiddenProgramStage.feature
cypress/e2e/EnrollmentPage/HiddenProgramStage/HiddenProgramStage.js
src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/Stage.component.js

[DHIS2-16125](https://dhis2.atlassian.net/browse/DHIS2-16125)
- Checked if program rule `Prevent adding new events to stage` is in effect when no events are in stage. If so, the program stage is hidden.
- Change variable names for readability
- Removed `ConditionalTooltip` and `disabled` prop for the scenario where there are no events, because there are no use cases where this button can be disabled.
- Changed Cypress to verify that the stage is hidden (under the certain circumstances) instead of looking after the disabled button in the hidden program stage
[DHIS2-16125]: https://dhis2.atlassian.net/browse/DHIS2-16125?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [DHIS2-16125] hide program stage under certain circumstances

---

src/core_modules/capture-core/components/Pages/common/EnrollmentOverviewDomain/EnrollmentPageLayout/renderPageComponents/renderPageComponents.js
src/core_modules/capture-core/components/Pages/common/EnrollmentPlugin/EnrollmentPlugin.js

We were not passing in programStageId and eventId to enrollment plugins as we should. 
Picture to validate that we're actually providing the correct ids:
1. Enrollment Edit event page 
2. Enrollment new event page

fix: [DHIS2-17859] Add missing ids to Enrollment plugin

---

src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/RecentlyAddedEventsList/RecentlyAddedEventsList.component.js
src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/NewRelationshipWrapper/NewEventNewRelationshipWrapper.component.js
src/core_modules/capture-core/components/ListView/Filters/FilterRestMenu/FilterRestMenu.component.js
src/core_modules/capture-core/components/ListView/Menu/ListViewMenu.component.js
src/core_modules/capture-core/components/ListView/withEndColumnMenu/RowMenu.component.js
src/core_modules/capture-core/components/Pages/ViewEvent/Relationship/ViewEventNewRelationshipWrapper.component.js

[DHIS2-17839](https://dhis2.atlassian.net/browse/DHIS2-17849)
**Tech summary:**
- replace material ui Paper for Card
[DHIS2-17839]: https://dhis2.atlassian.net/browse/DHIS2-17839?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: [DHIS2-17839] replace material ui Paper for Card

---

i18n/en.pot
src/core_modules/capture-core/components/DataEntry/DataEntry.component.js
src/core_modules/capture-core/components/DataEntry/dataEntryOutput/withDataEntryOutput.js
src/core_modules/capture-core/components/DataEntry/dataEntryOutput/withErrorOutput.js
src/core_modules/capture-core/components/DataEntry/dataEntryOutput/withFeedbackOutput.js
src/core_modules/capture-core/components/DataEntry/dataEntryOutput/withIndicatorOutput.js
src/core_modules/capture-core/components/DataEntry/dataEntryOutput/withWarningOutput.js
src/core_modules/capture-core/components/WidgetFeedback/WidgetFeedback.component.js
src/core_modules/capture-core/components/WidgetFeedback/WidgetFeedback.types.js
src/core_modules/capture-core/components/WidgetFeedback/index.js

[DHIS2-17750](https://dhis2.atlassian.net/browse/DHIS2-17750)
- The material-ui `Card` was still used to display the program rules effects when adding a new event to a single event program. I replaced the Card for the Widgets
[DHIS2-17750]: https://dhis2.atlassian.net/browse/DHIS2-17750?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: [DHIS2-17750] replace material ui Card for Widget

---

src/core_modules/capture-core/components/WidgetProfile/DataEntry/FormFoundation/RenderFoundation.js
src/core_modules/capture-core/components/WidgetProfile/hooks/useApiProgram.js
src/core_modules/capture-core/metaDataMemoryStoreBuilders/programs/factory/enrollment/EnrollmentFactory.js
src/core_modules/capture-core/metaDataStoreLoaders/programs/quickStoreOperations/storePrograms.js
src/core_modules/capture-core/metaDataStoreLoaders/programs/quickStoreOperations/types/apiPrograms.types.js
src/core_modules/capture-core/storageControllers/cache.types.js

Summary:
- Add section descriptions on the enrollment form

feat: [DHIS2-12288] add enrollment section description

---

src/core_modules/capture-core/components/ScopeSelector/QuickSelector/Program/ProgramSelector.component.js

Summary:
- If you're in the `EnrollmentAddEvent` or `EnrollmentEditEvent` page, changing the program does nothing
- Hide the program selector menu if no `onSetProgramId`-callback is passed in to the program selector

fix: [DHIS2-17352] Changing program in event workspace does nothing

---

cypress/e2e/EnrollmentAddEventPage/ProgramStageSelector/ProgramStageSelector.feature
cypress/e2e/EnrollmentAddEventPage/ProgramStageSelector/ProgramStageSelector.js
cypress/e2e/EnrollmentPage/EnrollmentQuickActions/EnrollmentQuickActions.feature
cypress/e2e/EnrollmentPage/EnrollmentQuickActions/EnrollmentQuickActions.js
cypress/e2e/EnrollmentPage/StagesAndEventsWidget/StagesAndEventsWidget.feature
i18n/en.pot
src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/EnrollmentQuickActions/EnrollmentQuickActions.component.js
src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/ProgramStageSelector/ProgramStageSelector.component.js
src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/ProgramStageSelector/ProgramStageSelector.container.js
src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/Stage.component.js
src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageCreateNewButton/StageCreateNewButton.js
src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageCreateNewButton/index.js
src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/StageDetail.component.js

Summary:
- Unify logic for create new event buttons in stages&events widget
- Disable quick actions button if there are no stages with write access
- Disable ProgramStageSelector-buttons if user does not have write access

feat: [DHIS2-17575] disable create new buttons if no data write access

---

cypress/e2e/WidgetsForEnrollmentPages/WidgetEnrollment/index.js
cypress/e2e/WidgetsForEnrollmentPages/WidgetsForEnrollmentDashboard/WidgetsForEnrollmentDashboard.feature

[DHIS2-17925](https://dhis2.atlassian.net/browse/DHIS2-17925)
- adopt the transfer scenario to the newly added API restrictions introduced in [DHIS2-17880 ](https://dhis2.atlassian.net/browse/DHIS2-17880)
[DHIS2-17925]: https://dhis2.atlassian.net/browse/DHIS2-17925?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: [DHIS2-17925] adapt the transfer scenario to the newly added API restrictions

---

src/core_modules/capture-core/components/DataEntries/common/ProgramStage/buildProgramStageMetadata.js

[DHIS2-17971](https://dhis2.atlassian.net/browse/DHIS2-17971)
In `WidgetEnrollmentEventNew.container.js` we recently switched source for the `stage` object. The program stage's `programRules` array wasn't initialised in this new source. This PR initialises this array.
[DHIS2-17971]: https://dhis2.atlassian.net/browse/DHIS2-17971?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [DHIS2-17971] trigger program stage specific rules on opening new event page

---

.github/workflows/verify-app.yml

Reverts dhis2/capture-app#3784 which broke the release job

chore(deps): revert actions/download-artifact from 4.1.7 to 2 in /.github/workflows

---

.github/workflows/verify-app.yml

To fix the failures in the [build](https://github.com/dhis2/capture-app/actions/runs/10807955762/job/29979941872?pr=3799) and [release]( https://github.com/dhis2/capture-app/actions/runs/10697575105/job/29655274124) jobs, I bump actions/download-artifact and actions/upload-artifact to `v4`. You can read more details about the issue in the [Github artifacts deprecation notice](https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/ ) and the [artifacts compatibility](https://github.com/actions/toolkit/blob/main/packages/artifact/docs/faq.md#which-versions-of-the-artifacts-packages-are-compatible)

refactor: bump download-artifact and upload-artifact version

---

src/core_modules/capture-core/components/Pages/common/EnrollmentOverviewDomain/EnrollmentPageLayout/DefaultEnrollmentLayout.types.js
src/core_modules/capture-core/components/Pages/common/EnrollmentOverviewDomain/EnrollmentPageLayout/EnrollmentPageLayout.js
src/core_modules/capture-core/components/Widget/WidgetCollapsible.component.js

Tech-summary:
- Support custom background color in our enrollment pages
- Add a "backgroundColor" prop to the datastore config
- This prop has to be a `#` followed by 6 characters

feat: support custom background color

---

packages/rules-engine/src/services/VariableService/VariableService.js
packages/rules-engine/src/services/VariableService/helpers/structureEvents.js
packages/rules-engine/src/services/VariableService/variableService.types.js
src/core_modules/capture-core/rules/converters/dateUtils.js

The events weren't sorted because the dates weren't in the right format. Ended up removing the validation in the end as it is not needed. Without the validation the old format would probably have worked, but for consistency, the values are now converted to the right "rules engine format".
Additionally, if two events occurred on the same date, they are now sorted by their creation date, ensuring the result is idempotent.

fix: [DHIS2-18004] sort events in rules engine by occurredAt and createdAt

---

src/core_modules/capture-core/converters/formToClient.js

[DHIS2-18116](https://dhis2.atlassian.net/browse/DHIS2-18116)
The bug occurred because there was missing validation of the return value from `parseDate`.
There are other occurrences of parseDate (and parseTime) in the same file, but for some reason the obvious way to trigger these functions does not work, and therefore I don't know when or if they ever get called.
EDIT:
Regarding how to trigger the other functions, see [comment below](https://github.com/dhis2/capture-app/pull/3823#issuecomment-2388492705) (thanks @simonadomnisoru)
[DHIS2-18116]: https://dhis2.atlassian.net/browse/DHIS2-18116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [DHIS2-18116] check return value of `parseDate`

---

src/core_modules/capture-core/components/WidgetEnrollmentEventNew/Validated/getConvertedRelatedStageEvent/getConvertedRelatedStageEvent.js
src/core_modules/capture-core/components/WidgetRelatedStages/LinkToExisting/LinkToExisting.component.js
src/core_modules/capture-core/components/WidgetRelatedStages/LinkToExisting/LinkToExisting.types.js
src/core_modules/capture-core/components/WidgetRelatedStages/RelatedStagesActions/RelatedStagesActions.component.js
src/core_modules/capture-core/components/WidgetRelatedStages/RelatedStagesActions/RelatedStagesActions.types.js
src/core_modules/capture-core/components/WidgetRelatedStages/WidgetRelatedStages.component.js
src/core_modules/capture-core/components/WidgetRelatedStages/hooks/useAvailableRelatedStageEvents.js
src/core_modules/capture-core/components/WidgetRelatedStages/hooks/useCanAddNewEventToStage.js
src/core_modules/capture-core/components/WidgetRelatedStages/hooks/useRelatedStageEvents.js

Tech-summary:
- We were filtering out events that had a relationship because these are not considered linkable
- Switched this out to rather keep all events, but filter out the non-linkable as a separate array

fix: [DHIS2-18028] User is able to add invalid related stages event

---

cypress/e2e/NewPage/NewPage.feature
cypress/e2e/NewPage/NewPage.js

The bulk action working list tests are currently failing due to the new page tests are adding data without cleaning it up.

test: cleanup after running NewPage tests

---

src/core_modules/capture-core/components/Pages/NewRelationship/TeiRelationship/SearchResults/TeiRelationshipSearchResults.component.js

[DHIS2-18056](https://dhis2.atlassian.net/browse/DHIS2-18056)
- use linkedEntityFormFoundation instead of the searchFormFoundation
[DHIS2-18056]: https://dhis2.atlassian.net/browse/DHIS2-18056?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [DHIS2-18056] use linkedEntityFormFoundation instead of the searchFormFoundation

---

cypress/e2e/MainPage/MainPage.js
i18n/en.pot
src/core_modules/capture-ui/NonBundledIcon/NonBundledIcon.component.js

Tech-summary:
- Use title instead of alt on missing icons

fix: [DHIS2-17978] use title instead of alt on missing icons

---

packages/rules-engine/src/services/VariableService/variableService.types.js
src/core_modules/capture-core/components/WidgetEventEdit/DataEntry/epics/editEventDataEntry.epics.js

There was a missing piece in https://dhis2.atlassian.net/browse/DHIS2-18004. `createdAt` wasn't passed on the rules engine when editing an event.
FYI: I didn't convert the value from "server value" because the `DATE_TIME` value type conversion needs some work. I have created another ticket for this (https://dhis2.atlassian.net/browse/DHIS2-18249). This exact scenario should work without conversion though.

fix: [DHIS2-18248] pass on createdAt to rules engine when editing

---

src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/programStageTemplates.epics.js
src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/teiTemplates.epics.js
src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/helpers/TEIFilters/clientConfigToApiTEIFilterQueryConverter/convertors.js
src/core_modules/capture-core/components/WorkingLists/WorkingListsBase/TemplateMaintenance/DeleteConfirmationDialog.component.js
src/core_modules/capture-core/components/WorkingLists/WorkingListsBase/TemplateMaintenance/ExistingTemplateContents.component.js
src/core_modules/capture-core/components/WorkingLists/WorkingListsBase/TemplateMaintenance/NewTemplateContents.component.js

Summary:
When creating a list with followUp explicitly marked as `false`, this got filtered out before it was sent to the API.
I also took the opportunity to add some ButtonStrips when already editing these files. I think it makes the UI look a bit cleaner.

fix: [DHIS2-18238] incorrect criteria when saving list with follow up false

---

src/core_modules/capture-core/components/FiltersForTypes/Date/DateFilter.component.js

Implements [DHIS2-18614](https://dhis2.atlassian.net/browse/DHIS2-18614)
----------
When selecting only a `from` or `to` date in the date range filter, the application throws a runtime error, which this PR fixes 
[DHIS2-18614]: https://dhis2.atlassian.net/browse/DHIS2-18614?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [DHIS2-18614] prevent runtime error when only one date range is selected

---

src/core_modules/capture-core/components/WidgetEnrollment/Date/Date.component.js

Implement [DHIS2 15466](https://dhis2.atlassian.net/browse/DHIS2-15466)
**In Enrolment Widget:**
- Display and pick non-Gregorian dates. 
- Follow system setting format for dates.
- Display errors when date is invalid.
- Refactor code to use DateField component instead of using CalendarInput directly.

feat: [DHIS2 15466] typing the date when editing enrollment and incident date

---

src/core_modules/capture-core/components/WidgetEventEdit/EditEventDataEntry/editEventDataEntry.actions.js

Fixes https://dhis2.atlassian.net/browse/DHIS2-18654 
The only area where importStrategy=delete was used, every other area used importStrategy=DELETE. 
This is not an issue for newer backend versions (probably v41+, but v39 breaks). Easier to fix frontend than backend.

fix: [DHIS2-118654] Use importStrategy=DELETE to support older backend

---

cypress/e2e/EnrollmentPage/StagesAndEventsWidget/StagesAndEventsWidget.feature
cypress/e2e/EnrollmentPage/StagesAndEventsWidget/StagesAndEventsWidget.js
cypress/e2e/WidgetsForEnrollmentPages/WidgetEnrollment/index.js
cypress/e2e/WidgetsForEnrollmentPages/WidgetsForEnrollmentAddEventPage/WidgetsForEnrollmentAddEventPage.feature
cypress/e2e/WidgetsForEnrollmentPages/WidgetsForEnrollmentDashboard/WidgetsForEnrollmentDashboard.feature
cypress/e2e/WidgetsForEnrollmentPages/WidgetsForEnrollmentEditEvent/WidgetsForEnrollmentEditEvent.feature
cypress/e2e/WorkingLists/TeiWorkingLists/TeiBulkActions/TeiBulkActions.feature

[DHIS2-18736](https://dhis2.atlassian.net/browse/DHIS2-18736)
[DHIS2-18736]: https://dhis2.atlassian.net/browse/DHIS2-18736?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: [DHIS2-18736] fix Cypress tests broken due to the change of year

---

src/core_modules/capture-core/components/WidgetEnrollmentEventNew/Validated/Validated.container.js

Implements [DHIS2-18355](https://dhis2.atlassian.net/browse/DHIS2-18355)
[DHIS2-18355]: https://dhis2.atlassian.net/browse/DHIS2-18355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [DHIS2-18355] runtime error occurs when saving empty widget in Related stages

---

src/core_modules/capture-core/components/WidgetProfile/WidgetProfile.component.js
src/core_modules/capture-core/components/WidgetProfile/hooks/useTrackedEntityInstances.js

Summary:
- Display correct title when profile widget is loading

fix: [DHIS2-18836] show 'Profile' instead of 'False' during loading

---

cypress/e2e/NewPage/NewPage.js
cypress/e2e/WidgetsForEnrollmentPages/WidgetsForEnrollmentAddEventPage/WidgetsForEnrollmentAddEventPage.feature
cypress/e2e/WidgetsForEnrollmentPages/WidgetsForEnrollmentEditEvent/WidgetsForEnrollmentEditEvent.feature
src/core_modules/capture-core/components/WidgetProfile/OverflowMenu/OverflowMenu.component.js
src/core_modules/capture-core/components/WidgetProfile/OverflowMenu/OverflowMenu.container.js
src/core_modules/capture-core/components/WidgetProfile/OverflowMenu/OverflowMenu.types.js
src/core_modules/capture-core/components/WidgetProfile/WidgetProfile.component.js

Summary:
- Added readOnlyMode prop to OverflowMenu component
- Hide the entire overflow menu when readOnlyMode is true and changelog is disabled
- Hide only the Delete action when readOnlyMode is true but changelog is enabled
- Verified readOnlyMode settings in DefaultPageLayout files:
- true for add/edit event pages (to hide Delete)
- false for enrollment dashboard (to show Delete)

fix: [DHIS2-18668] remove delete button in enrollment event pages

---

src/core_modules/capture-core/components/SearchBox/SearchBox.actions.js
src/core_modules/capture-core/components/SearchBox/SearchForm/SearchForm.epics.js

[DHIS2-18902](https://dhis2.atlassian.net/browse/DHIS2-18902)
This should cover the main case. There are two other similar search components which are used in the context of relationships, but I think these do not lead to opening a tracked entity, and are therefore not subject to the reported issue.
[DHIS2-18902]: https://dhis2.atlassian.net/browse/DHIS2-18902?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [DHIS2-18902] keep program selection on unique id fallback search

---

cypress/e2e/EnrollmentEditEventPage/EnrollmentEditEventPageNavigation/EnrollmentEditEventPageNavigation.feature
cypress/e2e/EnrollmentEditEventPage/EnrollmentEditEventPageNavigation/EnrollmentEditEventPageNavigation.js
cypress/e2e/WidgetsForEnrollmentPages/WidgetsForEnrollmentAddEventPage/WidgetsForEnrollmentAddEventPage.js
cypress/e2e/WidgetsForEnrollmentPages/WidgetsForEnrollmentDashboard/WidgetsForEnrollmentDashboard.feature
cypress/e2e/WidgetsForEnrollmentPages/WidgetsForEnrollmentDashboard/WidgetsForEnrollmentDashboard.js
i18n/en.pot
src/core_modules/capture-core/components/Breadcrumbs/EnrollmentBreadcrumb/EnrollmentBreadcrumb.js
src/core_modules/capture-core/components/Breadcrumbs/EventBreadcrumb/EventBreadcrumb.js
src/core_modules/capture-core/components/Breadcrumbs/common/BreadcrumbItem.js
src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.component.js
src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.container.js
src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.types.js
src/core_modules/capture-core/components/Pages/ViewEvent/ViewEventComponent/ViewEvent.component.js
src/core_modules/capture-core/components/Pages/common/EnrollmentOverviewDomain/EnrollmentPageLayout/LayoutComponentConfig/LayoutComponentConfig.js
src/core_modules/capture-core/components/Pages/common/WidgetEventEditWrapper/WidgetEventEditWrapper.js
src/core_modules/capture-core/components/WidgetEventEdit/widgetEventEdit.types.js

[DHIS2-18978](https://dhis2.atlassian.net/browse/DHIS2-18978):
- Removes the `Back to all stages and events` and the `Show all events` button.
- Changes Cypress test to use the breadcrumb for navigating.
[DHIS2-18677]: https://dhis2.atlassian.net/browse/DHIS2-18677?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DHIS2-18978]: https://dhis2.atlassian.net/browse/DHIS2-18978?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [DHIS2-18978] Back buttons duplicate breadcrumbs

---

src/core_modules/capture-core/components/SearchBox/SearchResults/SearchResults.component.js

[DHIS2-18958](https://dhis2.atlassian.net/browse/DHIS2-18958):
When the button is clicked, it enters a loading state. It will remain in this state until the Redux variable `otherResults` is defined. This ensures that the button stays in a loading state while the search is in progress and updates only when results are available.
A loading spinner is also implemented when navigating between pages while searching across all programs.
[DHIS2-18958]: https://dhis2.atlassian.net/browse/DHIS2-18958?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [DHIS2-18958] Add loading functionality to Search in all programs button

---

src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/hooks/getSubValueForTei.js
src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/hooks/useFormValues.js
src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/hooks/useLifecycle.js
src/core_modules/capture-core/components/Pages/New/NewPage.container.js
src/core_modules/capture-core/components/Pages/New/hooks/useTrackedEntityInstances.js

[DHIS2-18704](https://dhis2.atlassian.net/browse/DHIS2-18704)
The bug described in the ticket occurs when the internet speed is low, causing the registration form to load before the trackedEntity attributes are retrieved and added to the form. The proposed solution is to show the loading spinner while the trackedEntity attributes are being processed.
[DHIS2-18704]: https://dhis2.atlassian.net/browse/DHIS2-18704?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [DHIS2-18704] registration form missing values

---

src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/helpers/deriveAutoGenerateEvents.js

[DHIS2-17152](https://dhis2.atlassian.net/browse/DHIS2-17152)
- All the auto-generated events will have status 'SCHEDULE'
- When openAfterEnrollment is true, we do not add minDaysFromStart to the scheduledAt date
[DHIS2-17152]: https://dhis2.atlassian.net/browse/DHIS2-17152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [DHIS2-17152] status of autogenerated events with openAfterEnrollment true

---

.gitignore
src/core_modules/capture-core/components/WidgetProfile/DataEntry/ProgramRules/rulesContainer.js
src/core_modules/capture-core/metaDataMemoryStoreBuilders/programs/getRulesAndVariablesFromIndicators.js

Currently, the app breaks if it's trying to load in a program indicator without an expression. Instead, we should skip the program indicator and log an error to the console.

fix: [DHIS2-18855] add error logging for program indicators missing expressions

---

src/core_modules/capture-core/components/D2Form/field/configs/ageField/getAgeFieldConfig.js
src/core_modules/capture-core/components/D2Form/field/defaultFormFieldGetter.js
src/core_modules/capture-core/utils/validation/getValidators.js
src/core_modules/capture-core/utils/validation/validators/form/ageValidator.js
src/core_modules/capture-core/utils/validation/validators/form/index.js
src/core_modules/capture-core/utils/validation/validators/form/isValidNonFutureAge.js
src/core_modules/capture-ui/AgeField/ageField.module.css

Implements [DHIS2-18676](https://dhis2.atlassian.net/browse/DHIS2-18676)
There are two errors displayed when a user selects a future date in the age field:
- `A date in the future is not allowed`: Displayed when a user selects a date in the future from the date field.
- `Please provide a valid positive integer`: Displayed when a user enters a negative number in the Days, Months, or Years fields.
[DHIS2-18676]: https://dhis2.atlassian.net/browse/DHIS2-18676?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [DHIS2-18676] display error for age in the future

---

src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/ViewMenuSetup/EventWorkingListsViewMenuSetup.component.js
src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/ViewMenuSetup/EventWorkingListsViewMenuSetup.types.js

Added a useEffect that listens to the last deleted ID and refreshes the app when it's updated. Currently, the list does not refresh on delete.

feat: [DHIS2-18944] add effect to refresh list on event deletion

---

src/core_modules/capture-core-utils/featuresSupport/support.js
src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/helpers/deriveFirstStageDuringRegistrationEvent.js
src/core_modules/capture-core/components/DataEntries/converters/getConvertedRelatedStageEvent/getConvertedRelatedStageEvent.js
src/core_modules/capture-core/components/WidgetEnrollmentEventNew/Validated/getConvertedAddEvent.js
src/core_modules/capture-core/components/WidgetEventEdit/DataEntry/editEventDataEntry.actions.js
src/core_modules/capture-core/components/WidgetEventEdit/EditEventDataEntry/EditEventDataEntry.component.js

1. Don't save a scheduled date when directly adding a tracker event (from version 41). 
2. Handle empty value for `scheduledAt` when editing tracker event.

fix: [DHIS2-19165] handle empty schedule date

---

src/core_modules/capture-core/components/Pages/ViewEvent/RightColumn/RelationshipsSection/ConnectedEntity/TrackedEntityInstance.js
src/core_modules/capture-core/components/Pages/common/TEIRelationshipsWidget/useLinkedRecordClick.js

[DHIS2-16918](https://dhis2.atlassian.net/browse/DHIS2-16918):
- URL is now relative
- The user is now redirected to TE in the existing tab, but the TE can still be opened in a new tab by CTRL+CLICK.
[DHIS2-16918]: https://dhis2.atlassian.net/browse/DHIS2-16918?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [DHIS2-16918] Event relationship URL link is broken

---

src/core_modules/capture-core/rules/RuleEngine/helpers/InputBuilder.js

[DHIS2-19336](https://dhis2.atlassian.net/browse/DHIS2-19336)
[RuleEnrollmentJs](https://github.com/dhis2/dhis2-rule-engine/blob/master/src/jsMain/kotlin/org/hisp/dhis/rules/RuleEnrollmentJs.kt) expects a non-null array value in the last argument.
[DHIS2-19336]: https://dhis2.atlassian.net/browse/DHIS2-19336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [DHIS2-19336] provide empty array instead of `null` to `RuleEnrollmentJs`

---

src/core_modules/capture-core/components/DataEntries/Enrollment/epics/enrollment.epics.js
src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/epics/newEventDataEntry.epics.js
src/core_modules/capture-core/components/WidgetEnrollmentEventNew/DataEntry/epics/dataEntryRules.epics.js
src/core_modules/capture-core/components/WidgetEventEdit/DataEntry/epics/editEventDataEntry.epics.js

[DHIS2-19415](https://dhis2.atlassian.net/browse/DHIS2-19415)
Replaces `switchMap` with `concatMap` so that no actions get discarded by accident.
[DHIS2-19415]: https://dhis2.atlassian.net/browse/DHIS2-19415?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [DHIS2-19415] editing two fields simultaneously blocks saving

---

cypress/e2e/WidgetsForEnrollmentPages/WidgetChangelog/Changelog.feature
cypress/e2e/WidgetsForEnrollmentPages/WidgetChangelog/Changelog.js
cypress/e2e/WidgetsForEnrollmentPages/WidgetsForEnrollmentEditEvent/WidgetsForEnrollmentEditEvent.feature
cypress/e2e/WidgetsForEnrollmentPages/WidgetsForEnrollmentEditEvent/WidgetsForEnrollmentEditEvent.js
src/core_modules/capture-core/components/WidgetsChangelog/common/ChangelogFilterBar/DropdownFilter.js
src/core_modules/capture-core/components/WidgetsChangelog/common/ChangelogTable/ChangelogTableHeader.js

[DHIS2-18642](https://dhis2.atlassian.net/browse/DHIS2-18642)
- **Sorting**: Validates sorting by Date, User, and Data item.
- **Filtering**: Tests filtering by Data item, with only one active filter at a time. Ensures the filter persists after sorting and can be reset.
- **Paging**: Verifies page size changes, page navigation, and correct footer updates.
---
- Point and Polygon
- Files and images
- Appearance of Rows for Created, Updated, and Deleted Data
_Further testing requires changes to the Sierra Leone DB_
[DHIS2-18642]: https://dhis2.atlassian.net/browse/DHIS2-18642?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: [DHIS2-18642] Cypress tests changelog

---

src/core_modules/capture-core/components/Pages/New/NewPage.component.js
src/core_modules/capture-core/components/Pages/New/NewPage.container.js
src/core_modules/capture-core/components/Pages/New/NewPage.types.js
src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.container.js
src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.types.js
src/core_modules/capture-core/components/Pages/New/TopBar.container.js
src/core_modules/capture-core/components/TopBarActions/TopBarActions.container.js
src/core_modules/capture-core/components/TopBarActions/TopBarActions.types.js

[DHIS2-18671](https://dhis2.atlassian.net/browse/DHIS2-18671):
1. A `newPageKey` state was introduced using `useState` and `uuid` to generate a unique key.  
2. The `handleRefreshNewTeForm` function updates this key, which forces the form to reload.  
3. The refresh functionality is integrated into the top bar, allowing users to trigger a form reset from there.
[DHIS2-18671]: https://dhis2.atlassian.net/browse/DHIS2-18671?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [DHIS2-18671] Discard changes dialog not responding

---

src/core_modules/capture-core/components/WidgetProfile/DataEntry/helpers/convertClientToView.js

[DHIS2-18839](https://dhis2.atlassian.net/browse/DHIS2-18839)
- Added converting from server to client value for options.
[DHIS2-18839]: https://dhis2.atlassian.net/browse/DHIS2-18839?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [DHIS2-18839] TEA with number option set value does not show in Profile widget on Capture App

---

src/core_modules/capture-core/components/D2Form/D2Section.component.js
src/core_modules/capture-core/components/D2Form/D2Section.container.js
src/core_modules/capture-core/components/Pages/New/NewPage.actions.js
src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.container.js
src/core_modules/capture-core/reducers/descriptions/dataEntry.reducerDescription.js
src/core_modules/capture-core/reducers/descriptions/form.reducerDescription.js

- Ensures form initialisation executes before rules.
- Ensures all fields have a valid Redux state for `formsSectionsFieldsUI`. 
I couldn't reproduce the error reported in the newest Capture app (in the versions mentioned in the ticket I could). However, the code was highly error-prone and didn't behave as intended. @MatiasArriola: Thanks for such a thorough description in this PR (https://github.com/EyeSeeTea/capture-app/pull/4)

fix: [DHIS2-19467] form inconsistencies

---

src/core_modules/capture-core/metaDataMemoryStoreBuilders/programs/factory/enrollment/DataElementFactory.js

[DHIS2-18951](https://dhis2.atlassian.net/browse/DHIS2-18951):
Temporary fix for error message:
`"Non-searchable attribute(s) can not be used during global search: [attributeId]"`
This change catches that specific `409` error in validation and allows the form to be saved instead of blocking the user.
Note: The error still appears in the network tab but no longer prevents saving.
[DHIS2-18951]: https://dhis2.atlassian.net/browse/DHIS2-18951?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [DHIS2-18951] Ignore Non-searchable attributes error when validating unique attribute

---

cypress/e2e/EnrollmentPage/HiddenProgramStage/HiddenProgramStage.js
cypress/e2e/EnrollmentPage/StagesAndEventsWidget/StagesAndEventsWidget.js
cypress/e2e/WidgetsForEnrollmentPages/WidgetProfile/index.js
cypress/e2e/WorkingLists/TeiWorkingLists/TeiBulkActions/TeiBulkActions.feature
src/core_modules/capture-core/components/WidgetRelatedStages/RelatedStagesActions/RelatedStagesActions.container.js
src/core_modules/capture-core/components/WidgetRelatedStages/hooks/useRelatedStageEvents.js

I investigated some flaky Cypress tests that have been intermittently failing over the past few weeks and made a few small improvements.
**Tech summary:**
- Improved the frequently failing `User can delete an event` scenario. Cleanup is now performed by calling the API directly, not through the UI.
- Skipped another frequently failing bulk actions scenario and added it to [DHIS2-18447](https://dhis2.atlassian.net/browse/DHIS2-18447).
- Fixed the RelatedStages failed tests by adding the `program` to the `tracker/events` request. These failures were caused by a recent API change that made the program field mandatory for the event exporter https://github.com/dhis2/dhis2-core/pull/20972
- To take full advantage of Cypress's retry-ability, I used the `get` query to stabilize the `User cannot …

chore: stabilize cypress flaky tests

---

src/core_modules/capture-core/components/ListView/types/listView.types.js
src/core_modules/capture-core/components/WorkingLists/EventWorkingListsCommon/types/eventWorkingListsCommon.types.js
src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/Setup/hooks/useDefaultColumnConfig.js
src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/Setup/hooks/useInjectDataFetchingMeta.js
src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/helpers/TEIFilters/apiTEIFilterToClientConfigConverter/convertToClientFilters.js
src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/helpers/TEIFilters/clientConfigToApiTEIFilterQueryConverter/convertToTEIFilterQuery.js
src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/helpers/TEIFilters/clientConfigToApiTEIFilterQueryConverter/convertors.js
src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/types/apiTemplate.types.js
src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/types/concept.types.js
src/core_modules/capture-core/components/WorkingLists/WorkingListsBase/workingListsBase.types.js
src/core_modules/capture-core/components/WorkingLists/WorkingListsCommon/helpers/buildFilterQueryArgs/buildFilterQueryArgs.js
src/core_modules/capture-core/components/WorkingLists/WorkingListsCommon/helpers/buildFilterQueryArgs/filterConverters/assigneeConverter.js
src/core_modules/capture-core/components/WorkingLists/WorkingListsCommon/helpers/buildFilterQueryArgs/filterConverters/booleanConverter.js
src/core_modules/capture-core/components/WorkingLists/WorkingListsCommon/helpers/buildFilterQueryArgs/filterConverters/dateConverter.js
src/core_modules/capture-core/components/WorkingLists/WorkingListsCommon/helpers/buildFilterQueryArgs/filterConverters/numericConverter.js
src/core_modules/capture-core/components/WorkingLists/WorkingListsCommon/helpers/buildFilterQueryArgs/filterConverters/textConverter.js
src/core_modules/capture-core/components/WorkingLists/WorkingListsCommon/helpers/buildFilterQueryArgs/filterConverters/trueOnlyConverter.js

[DHIS2-19694](https://dhis2.atlassian.net/browse/DHIS2-19694)
- use the `eq` operator when filtering by unique TEA in the Tracker programs working lists
- use the `eq` operator for [POST and PUT requests](https://github.com/dhis2/capture-app/pull/4129/files#diff-74c4f09afc76fe06368d5b756d4a3a7dd9255fb01ecdc5ca1fad46629a6d4c3dR17) to the `/trackedEntityInstanceFilters` and `/programStageWorkingLists` endpoints
- maintain backward compatibility for previously stored Tracker WL templates, by supporting [both eq and like](https://github.com/dhis2/capture-app/pull/4129/files#diff-c6cd17ddf4d6c3ba3c3925fa71b2fb5251036ea8874adadcc4d6fba63081400fR34) for unique TEAs 
[DHIS2-19694]: https://dhis2.atlassian.net/browse/DHIS2-19694?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA …

fix: [DHIS2-19694] use the EQ operator when filtering by unique TEA in the WLs

---

src/core_modules/capture-core/components/DataEntries/Enrollment/actions/open.actionBatchs.js

[DHIS2-19784](https://dhis2.atlassian.net/browse/DHIS2-19784)
The rule engine prefers ISO-formatted enrollment dates.
This PR is basically just a rewrite of the solution in https://github.com/dhis2/capture-app/pull/3475, but the result is not identical; now the output date is always in the format `YYYY-MM-DD`, whereas before it had the system format.
I'll make this PR a draft until we've investigated whether the system format can still be used.
EDIT:
There is no sensible way to automatically output dates in the system date format, so keeping it as it currently is.
[DHIS2-19784]: https://dhis2.atlassian.net/browse/DHIS2-19784?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [DHIS2-19784] send ISO-formatted enrollment date to rule engine

---

cypress/e2e/EnrollmentAddEventPage/ProgramStageSelector/ProgramStageSelector.feature
cypress/e2e/EnrollmentAddEventPage/ProgramStageSelector/ProgramStageSelector.js
cypress/e2e/EnrollmentPage/HiddenProgramStage/HiddenProgramStage.js
cypress/e2e/ScopeSelector/ScopeSelector.feature
cypress/e2e/ScopeSelector/ScopeSelector.js
i18n/en.pot
src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/EnrollmentQuickActions/EnrollmentQuickActions.component.js
src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/ProgramStageSelector/ProgramStageSelector.component.js
src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/ProgramStageSelector/ProgramStageSelector.container.js

[DHIS2-16364](https://dhis2.atlassian.net/browse/DHIS2-16364)
This pull request introduced a new `useEffect` hook in `ProgramStageSelector.container.js` to automatically select a program stage if only one is available.
In addition, non-selectable program stages are filtered away from the "Choose a stage for a new event" widget.
[DHIS2-16364]: https://dhis2.atlassian.net/browse/DHIS2-16364?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [DHIS2-16364] Stage selection still shown with only one available stage

---

src/core_modules/capture-core/components/WidgetRelatedStages/FormComponents/DateFieldForRelatedStages.tsx

[DHIS2-20028](https://dhis2.atlassian.net/browse/DHIS2-20028)
Rollback code unnecessarily changed by Devin, which was causing the red background for required fields to not appear when linking Related stages
[DHIS2-20028]: https://dhis2.atlassian.net/browse/DHIS2-20028?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [DHIS2-20028] related stages required fields red background

---

cypress/e2e/Changelog/Changelog.feature
cypress/e2e/Changelog/Changelog.js
cypress/e2e/NewPage/NewPage.js
cypress/e2e/RelatedStages/RelatedStages.js
cypress/e2e/WidgetsForEnrollmentPages/WidgetProfile/index.js
src/core_modules/capture-core/components/Pages/ViewEvent/EventDetailsSection/EventDetailsSection.component.tsx
src/core_modules/capture-core/components/Pages/ViewEvent/EventDetailsSection/EventDetailsSection.types.ts
src/core_modules/capture-core/components/Pages/ViewEvent/ViewEventComponent/ViewEvent.component.tsx
src/core_modules/capture-core/components/WidgetEventEdit/WidgetHeader/WidgetHeader.container.tsx
src/core_modules/capture-core/components/WidgetProfile/OverflowMenu/OverflowMenu.component.tsx

[DHIS2-20029](https://dhis2.atlassian.net/browse/DHIS2-20029)
* Changed the type of the `programStage` prop in `EventDetailsSection.types.ts` from `any` to the `ProgramStage` type. 
* Updated the usage of the `EventDetails` component in `ViewEvent.component.tsx` to pass the `programStage` and new `onBackToViewEvent` props, ensuring the component receives the same props as before the conversion.*
* Added Cypress tests to check that all three types of Changelog show data (Tracker, Event, Tracked Entity).
* Update Demo DB: 
[DHIS2-20029]: https://dhis2.atlassian.net/browse/DHIS2-20029?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [DHIS2-20029] Event changelog for single events does not work

---

src/core_modules/capture-core/components/Pages/common/TEIRelationshipsWidget/TeiSearch/TeiSearchForm/TeiSearchForm.component.tsx

[DHIS2-20044](https://dhis2.atlassian.net/browse/DHIS2-20044)
Rollback Devin’s changes to the `validateForm` function and restore it to the current version in master. 
[DHIS2-20044]: https://dhis2.atlassian.net/browse/DHIS2-20044?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [DHIS2-20044] add relationship from enrollment dashboard by searching

---

src/core_modules/capture-core/rules/RuleEngine/RuleEngine.ts

[DHIS2-20600](https://dhis2.atlassian.net/browse/DHIS2-20060?actionerId=61bcf639e399d700715e8abf&sourceType=assign)
The rule engine generally does not receive a user role array directly as input, and in this case it should use the one with which it was initialized.

fix: use rule engine's user roles as fallback
